//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tct.ActivityRecorderClient.LotusNotesMeetingCaptureServiceReference {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="FinishedMeetingEntry", Namespace="http://jobctrl.com/")]
    [System.SerializableAttribute()]
    public partial class FinishedMeetingEntry : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.List<Tct.ActivityRecorderClient.LotusNotesMeetingCaptureServiceReference.MeetingAttendee> AttendeesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime CreationTimeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime EndTimeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime LastmodificationTimeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LocationField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime StartTimeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TitleField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.List<Tct.ActivityRecorderClient.LotusNotesMeetingCaptureServiceReference.MeetingAttendee> Attendees {
            get {
                return this.AttendeesField;
            }
            set {
                if ((object.ReferenceEquals(this.AttendeesField, value) != true)) {
                    this.AttendeesField = value;
                    this.RaisePropertyChanged("Attendees");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime CreationTime {
            get {
                return this.CreationTimeField;
            }
            set {
                if ((this.CreationTimeField.Equals(value) != true)) {
                    this.CreationTimeField = value;
                    this.RaisePropertyChanged("CreationTime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description {
            get {
                return this.DescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescriptionField, value) != true)) {
                    this.DescriptionField = value;
                    this.RaisePropertyChanged("Description");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime EndTime {
            get {
                return this.EndTimeField;
            }
            set {
                if ((this.EndTimeField.Equals(value) != true)) {
                    this.EndTimeField = value;
                    this.RaisePropertyChanged("EndTime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Id {
            get {
                return this.IdField;
            }
            set {
                if ((object.ReferenceEquals(this.IdField, value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime LastmodificationTime {
            get {
                return this.LastmodificationTimeField;
            }
            set {
                if ((this.LastmodificationTimeField.Equals(value) != true)) {
                    this.LastmodificationTimeField = value;
                    this.RaisePropertyChanged("LastmodificationTime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Location {
            get {
                return this.LocationField;
            }
            set {
                if ((object.ReferenceEquals(this.LocationField, value) != true)) {
                    this.LocationField = value;
                    this.RaisePropertyChanged("Location");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime StartTime {
            get {
                return this.StartTimeField;
            }
            set {
                if ((this.StartTimeField.Equals(value) != true)) {
                    this.StartTimeField = value;
                    this.RaisePropertyChanged("StartTime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Title {
            get {
                return this.TitleField;
            }
            set {
                if ((object.ReferenceEquals(this.TitleField, value) != true)) {
                    this.TitleField = value;
                    this.RaisePropertyChanged("Title");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="MeetingAttendee", Namespace="http://jobctrl.com/")]
    [System.SerializableAttribute()]
    public partial class MeetingAttendee : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Tct.ActivityRecorderClient.LotusNotesMeetingCaptureServiceReference.MeetingAttendeeResponseStatus ResponseStatusField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Tct.ActivityRecorderClient.LotusNotesMeetingCaptureServiceReference.MeetingAttendeeType TypeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Email {
            get {
                return this.EmailField;
            }
            set {
                if ((object.ReferenceEquals(this.EmailField, value) != true)) {
                    this.EmailField = value;
                    this.RaisePropertyChanged("Email");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Tct.ActivityRecorderClient.LotusNotesMeetingCaptureServiceReference.MeetingAttendeeResponseStatus ResponseStatus {
            get {
                return this.ResponseStatusField;
            }
            set {
                if ((this.ResponseStatusField.Equals(value) != true)) {
                    this.ResponseStatusField = value;
                    this.RaisePropertyChanged("ResponseStatus");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Tct.ActivityRecorderClient.LotusNotesMeetingCaptureServiceReference.MeetingAttendeeType Type {
            get {
                return this.TypeField;
            }
            set {
                if ((this.TypeField.Equals(value) != true)) {
                    this.TypeField = value;
                    this.RaisePropertyChanged("Type");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="MeetingAttendeeResponseStatus", Namespace="http://jobctrl.com/")]
    public enum MeetingAttendeeResponseStatus : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ResponseNone = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ResponseOrganized = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ResponseTentative = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ResponseAccepted = 3,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ResponseDeclined = 4,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ResponseNotResponded = 5,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="MeetingAttendeeType", Namespace="http://jobctrl.com/")]
    public enum MeetingAttendeeType : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Organizer = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Required = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Optional = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Resource = 3,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="MailCaptures", Namespace="http://jobctrl.com/mail")]
    [System.SerializableAttribute()]
    public partial class MailCaptures : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.Dictionary<int, Tct.ActivityRecorderClient.LotusNotesMeetingCaptureServiceReference.MailCapture> MailCaptureByHWndField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.Dictionary<int, Tct.ActivityRecorderClient.LotusNotesMeetingCaptureServiceReference.MailCapture> MailCaptureByHWnd {
            get {
                return this.MailCaptureByHWndField;
            }
            set {
                if ((object.ReferenceEquals(this.MailCaptureByHWndField, value) != true)) {
                    this.MailCaptureByHWndField = value;
                    this.RaisePropertyChanged("MailCaptureByHWnd");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="MailCapture", Namespace="http://jobctrl.com/mail")]
    [System.SerializableAttribute()]
    public partial class MailCapture : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.List<Tct.ActivityRecorderClient.LotusNotesMeetingCaptureServiceReference.MailAddress> CcField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Tct.ActivityRecorderClient.LotusNotesMeetingCaptureServiceReference.MailAddress FromField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SubjectField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.List<Tct.ActivityRecorderClient.LotusNotesMeetingCaptureServiceReference.MailAddress> ToField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.List<Tct.ActivityRecorderClient.LotusNotesMeetingCaptureServiceReference.MailAddress> Cc {
            get {
                return this.CcField;
            }
            set {
                if ((object.ReferenceEquals(this.CcField, value) != true)) {
                    this.CcField = value;
                    this.RaisePropertyChanged("Cc");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Tct.ActivityRecorderClient.LotusNotesMeetingCaptureServiceReference.MailAddress From {
            get {
                return this.FromField;
            }
            set {
                if ((object.ReferenceEquals(this.FromField, value) != true)) {
                    this.FromField = value;
                    this.RaisePropertyChanged("From");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Id {
            get {
                return this.IdField;
            }
            set {
                if ((object.ReferenceEquals(this.IdField, value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Subject {
            get {
                return this.SubjectField;
            }
            set {
                if ((object.ReferenceEquals(this.SubjectField, value) != true)) {
                    this.SubjectField = value;
                    this.RaisePropertyChanged("Subject");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.List<Tct.ActivityRecorderClient.LotusNotesMeetingCaptureServiceReference.MailAddress> To {
            get {
                return this.ToField;
            }
            set {
                if ((object.ReferenceEquals(this.ToField, value) != true)) {
                    this.ToField = value;
                    this.RaisePropertyChanged("To");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="MailAddress", Namespace="http://jobctrl.com/mail")]
    [System.SerializableAttribute()]
    public partial class MailAddress : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Email {
            get {
                return this.EmailField;
            }
            set {
                if ((object.ReferenceEquals(this.EmailField, value) != true)) {
                    this.EmailField = value;
                    this.RaisePropertyChanged("Email");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="LotusNotesMeetingCaptureServiceReference.IMeetingCaptureService")]
    public interface IMeetingCaptureService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMeetingCaptureService/Initialize", ReplyAction="http://tempuri.org/IMeetingCaptureService/InitializeResponse")]
        void Initialize(string password, string mailServer, string mailFile);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMeetingCaptureService/GetVersionInfo", ReplyAction="http://tempuri.org/IMeetingCaptureService/GetVersionInfoResponse")]
        string GetVersionInfo();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMeetingCaptureService/CaptureMeetings", ReplyAction="http://tempuri.org/IMeetingCaptureService/CaptureMeetingsResponse")]
        System.Collections.Generic.List<Tct.ActivityRecorderClient.LotusNotesMeetingCaptureServiceReference.FinishedMeetingEntry> CaptureMeetings(System.Collections.Generic.List<string> calendarAccountEmails, System.DateTime startDate, System.DateTime endDate);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMeetingCaptureService/GetMailCaptures", ReplyAction="http://tempuri.org/IMeetingCaptureService/GetMailCapturesResponse")]
        Tct.ActivityRecorderClient.LotusNotesMeetingCaptureServiceReference.MailCaptures GetMailCaptures();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMeetingCaptureService/StopService", ReplyAction="http://tempuri.org/IMeetingCaptureService/StopServiceResponse")]
        void StopService();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IMeetingCaptureServiceChannel : Tct.ActivityRecorderClient.LotusNotesMeetingCaptureServiceReference.IMeetingCaptureService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class MeetingCaptureServiceClient : System.ServiceModel.ClientBase<Tct.ActivityRecorderClient.LotusNotesMeetingCaptureServiceReference.IMeetingCaptureService>, Tct.ActivityRecorderClient.LotusNotesMeetingCaptureServiceReference.IMeetingCaptureService {
        
        public MeetingCaptureServiceClient() {
        }
        
        public MeetingCaptureServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public MeetingCaptureServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MeetingCaptureServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MeetingCaptureServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void Initialize(string password, string mailServer, string mailFile) {
            base.Channel.Initialize(password, mailServer, mailFile);
        }
        
        public string GetVersionInfo() {
            return base.Channel.GetVersionInfo();
        }
        
        public System.Collections.Generic.List<Tct.ActivityRecorderClient.LotusNotesMeetingCaptureServiceReference.FinishedMeetingEntry> CaptureMeetings(System.Collections.Generic.List<string> calendarAccountEmails, System.DateTime startDate, System.DateTime endDate) {
            return base.Channel.CaptureMeetings(calendarAccountEmails, startDate, endDate);
        }
        
        public Tct.ActivityRecorderClient.LotusNotesMeetingCaptureServiceReference.MailCaptures GetMailCaptures() {
            return base.Channel.GetMailCaptures();
        }
        
        public void StopService() {
            base.Channel.StopService();
        }
    }
}
