//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tct.ActivityRecorderService.MobileServiceReference {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UserData", Namespace="MobileJobCTRL")]
    [System.SerializableAttribute()]
    public partial class UserData : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Tct.ActivityRecorderService.MobileServiceReference.DeviceType DeviceTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int UserIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long ImeiField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int WorkIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<short> BatteryField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ConnectionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LastCameraShotPathField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Tct.ActivityRecorderService.MobileServiceReference.DeviceType DeviceType {
            get {
                return this.DeviceTypeField;
            }
            set {
                if ((this.DeviceTypeField.Equals(value) != true)) {
                    this.DeviceTypeField = value;
                    this.RaisePropertyChanged("DeviceType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int UserId {
            get {
                return this.UserIdField;
            }
            set {
                if ((this.UserIdField.Equals(value) != true)) {
                    this.UserIdField = value;
                    this.RaisePropertyChanged("UserId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public long Imei {
            get {
                return this.ImeiField;
            }
            set {
                if ((this.ImeiField.Equals(value) != true)) {
                    this.ImeiField = value;
                    this.RaisePropertyChanged("Imei");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public int WorkId {
            get {
                return this.WorkIdField;
            }
            set {
                if ((this.WorkIdField.Equals(value) != true)) {
                    this.WorkIdField = value;
                    this.RaisePropertyChanged("WorkId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public System.Nullable<short> Battery {
            get {
                return this.BatteryField;
            }
            set {
                if ((this.BatteryField.Equals(value) != true)) {
                    this.BatteryField = value;
                    this.RaisePropertyChanged("Battery");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=5)]
        public string Connection {
            get {
                return this.ConnectionField;
            }
            set {
                if ((object.ReferenceEquals(this.ConnectionField, value) != true)) {
                    this.ConnectionField = value;
                    this.RaisePropertyChanged("Connection");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=6)]
        public string LastCameraShotPath {
            get {
                return this.LastCameraShotPathField;
            }
            set {
                if ((object.ReferenceEquals(this.LastCameraShotPathField, value) != true)) {
                    this.LastCameraShotPathField = value;
                    this.RaisePropertyChanged("LastCameraShotPath");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DeviceType", Namespace="http://schemas.datacontract.org/2004/07/JobcontrolMobileServer")]
    public enum DeviceType : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Mobile = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Beacon = 1,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="MobileJobCTRL", ConfigurationName="MobileServiceReference.IMobileJobCTRLServer")]
    public interface IMobileJobCTRLServer {
        
        // CODEGEN: Generating message contract since the operation GetOnlineUsers is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="MobileJobCTRL/IMobileJobCTRLServer/GetOnlineUsers", ReplyAction="MobileJobCTRL/IMobileJobCTRLServer/GetOnlineUsersResponse")]
        Tct.ActivityRecorderService.MobileServiceReference.GetOnlineUsersResponse GetOnlineUsers(Tct.ActivityRecorderService.MobileServiceReference.GetOnlineUsersRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetOnlineUsersRequest {
        
        public GetOnlineUsersRequest() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetOnlineUsersResponse", WrapperNamespace="MobileJobCTRL", IsWrapped=true)]
    public partial class GetOnlineUsersResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="MobileJobCTRL", Order=0)]
        public System.Collections.Generic.List<Tct.ActivityRecorderService.MobileServiceReference.UserData> Users;
        
        public GetOnlineUsersResponse() {
        }
        
        public GetOnlineUsersResponse(System.Collections.Generic.List<Tct.ActivityRecorderService.MobileServiceReference.UserData> Users) {
            this.Users = Users;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IMobileJobCTRLServerChannel : Tct.ActivityRecorderService.MobileServiceReference.IMobileJobCTRLServer, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class MobileJobCTRLServerClient : System.ServiceModel.ClientBase<Tct.ActivityRecorderService.MobileServiceReference.IMobileJobCTRLServer>, Tct.ActivityRecorderService.MobileServiceReference.IMobileJobCTRLServer {
        
        public MobileJobCTRLServerClient() {
        }
        
        public MobileJobCTRLServerClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public MobileJobCTRLServerClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MobileJobCTRLServerClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MobileJobCTRLServerClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Tct.ActivityRecorderService.MobileServiceReference.GetOnlineUsersResponse Tct.ActivityRecorderService.MobileServiceReference.IMobileJobCTRLServer.GetOnlineUsers(Tct.ActivityRecorderService.MobileServiceReference.GetOnlineUsersRequest request) {
            return base.Channel.GetOnlineUsers(request);
        }
        
        public System.Collections.Generic.List<Tct.ActivityRecorderService.MobileServiceReference.UserData> GetOnlineUsers() {
            Tct.ActivityRecorderService.MobileServiceReference.GetOnlineUsersRequest inValue = new Tct.ActivityRecorderService.MobileServiceReference.GetOnlineUsersRequest();
            Tct.ActivityRecorderService.MobileServiceReference.GetOnlineUsersResponse retVal = ((Tct.ActivityRecorderService.MobileServiceReference.IMobileJobCTRLServer)(this)).GetOnlineUsers(inValue);
            return retVal.Users;
        }
    }
}
