BEGIN TRANSACTION
SET QUOTED_IDENTIFIER ON
SET ARITHABORT ON
SET NUMERIC_ROUNDABORT OFF
SET CONCAT_NULL_YIELDS_NULL ON
SET ANSI_NULLS ON
SET ANSI_PADDING ON
SET ANSI_WARNINGS ON
COMMIT
BEGIN TRANSACTION
GO
CREATE TABLE dbo.VoiceRecordings
	(
	Id int NOT NULL IDENTITY (1, 1),
	UserId int NOT NULL,
	WorkId int NULL,
	CreateDate datetime NOT NULL,
	Length int NOT NULL,
	Codec int NOT NULL,
	Name nvarchar(200) NULL,
	Extension varchar(10) NULL,
	ReceiveDate datetime NOT NULL
	)  ON [PRIMARY]
GO
ALTER TABLE dbo.VoiceRecordings ADD CONSTRAINT
	DF_VoiceRecordings_ReceiveDate DEFAULT GETUTCDATE() FOR ReceiveDate
GO
ALTER TABLE dbo.VoiceRecordings ADD CONSTRAINT
	PK_VoiceRecordings PRIMARY KEY CLUSTERED 
	(
	Id
	) WITH( STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]

GO
ALTER TABLE dbo.VoiceRecordings SET (LOCK_ESCALATION = TABLE)
GO
COMMIT
