//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.296
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JcSend.InterProcessReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="InterProcessReference.IInterProcessService")]
    public interface IInterProcessService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IInterProcessService/AddProjectAndWorkByRule", ReplyAction="http://tempuri.org/IInterProcessService/AddProjectAndWorkByRuleResponse")]
        void AddProjectAndWorkByRule(string projectKey, string workName, string workKey, int ruleId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IInterProcessService/StartWork", ReplyAction="http://tempuri.org/IInterProcessService/StartWorkResponse")]
        void StartWork(int workId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IInterProcessService/StopWork", ReplyAction="http://tempuri.org/IInterProcessService/StopWorkResponse")]
        void StopWork();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IInterProcessService/SwitchWork", ReplyAction="http://tempuri.org/IInterProcessService/SwitchWorkResponse")]
        void SwitchWork(int workId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IInterProcessService/AddExtText", ReplyAction="http://tempuri.org/IInterProcessService/AddExtTextResponse")]
        void AddExtText(string text);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IInterProcessServiceChannel : JcSend.InterProcessReference.IInterProcessService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class InterProcessServiceClient : System.ServiceModel.ClientBase<JcSend.InterProcessReference.IInterProcessService>, JcSend.InterProcessReference.IInterProcessService {
        
        public InterProcessServiceClient() {
        }
        
        public InterProcessServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public InterProcessServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public InterProcessServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public InterProcessServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void AddProjectAndWorkByRule(string projectKey, string workName, string workKey, int ruleId) {
            base.Channel.AddProjectAndWorkByRule(projectKey, workName, workKey, ruleId);
        }
        
        public void StartWork(int workId) {
            base.Channel.StartWork(workId);
        }
        
        public void StopWork() {
            base.Channel.StopWork();
        }
        
        public void SwitchWork(int workId) {
            base.Channel.SwitchWork(workId);
        }
        
        public void AddExtText(string text) {
            base.Channel.AddExtText(text);
        }
    }
}
