<?xml version="1.0" encoding="utf-8"?><Database Name="recorder" Class="NotificationDataClassesDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=.;Initial Catalog=recorder;Integrated Security=True;Pooling=False" SettingsObjectName="Tct.ActivityRecorderService.Properties.Settings" SettingsPropertyName="recorderConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.NotificationForms" Member="NotificationForms">
    <Type Name="NotificationForm">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Column Name="CompanyId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Data" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="Description" Type="System.String" DbType="NVarChar(2000)" CanBeNull="true" />
      <Column Name="WorkId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="CreatedBy" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="CreateDate" AutoSync="Never" Type="System.DateTime" DbType="DateTime NOT NULL" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="DeleteDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Association Name="NotificationForm_ClientNotification" Member="ClientNotifications" ThisKey="Id" OtherKey="FormId" Type="ClientNotification" />
    </Type>
  </Table>
  <Table Name="dbo.ClientNotifications" Member="ClientNotifications">
    <Type Name="ClientNotification">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="UserId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="FormId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="CreatedBy" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="CreateDate" AutoSync="Never" Type="System.DateTime" DbType="DateTime NOT NULL" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="SendDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="ReceiveDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="ShowDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="ConfirmDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Result" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="DeviceId" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Association Name="NotificationForm_ClientNotification" Member="NotificationForm" ThisKey="FormId" OtherKey="Id" Type="NotificationForm" IsForeignKey="true" />
    </Type>
  </Table>
</Database>