/*
Deployment script for recorder

This code was generated by a tool.
Changes to this file may cause incorrect behavior and will be lost if
the code is regenerated.
*/

GO
SET ANSI_NULLS, ANSI_PADDING, ANSI_WARNINGS, ARITHABORT, CONCAT_NULL_YIELDS_NULL, QUOTED_IDENTIFIER ON;

SET NUMERIC_ROUNDABORT OFF;


GO
/*
:setvar DatabaseName "recorder"
:setvar DefaultFilePrefix "recorder"
:setvar DefaultDataPath ""
:setvar DefaultLogPath ""
*/

GO
:on error exit
GO
/*
Detect SQLCMD mode and disable script execution if SQLCMD mode is not supported.
To re-enable the script after enabling SQLCMD mode, execute the following:
SET NOEXEC OFF; 
*/
:setvar __IsSqlCmdEnabled "True"
GO
IF N'$(__IsSqlCmdEnabled)' NOT LIKE N'True'
    BEGIN
        PRINT N'SQLCMD mode must be enabled to successfully execute this script.';
        SET NOEXEC ON;
    END


GO
USE [$(DatabaseName)];


GO
PRINT N'Dropping [dbo].[Snippets].[IX_Guid]...';


GO
DROP INDEX [IX_Guid]
    ON [dbo].[Snippets];


GO
PRINT N'Dropping DF_CreatedAt...';


GO
ALTER TABLE [dbo].[Snippets] DROP CONSTRAINT [DF_CreatedAt];


GO
PRINT N'Dropping DF_Snippets_IsBadData...';


GO
ALTER TABLE [dbo].[Snippets] DROP CONSTRAINT [DF_Snippets_IsBadData];


GO
PRINT N'Starting rebuilding table [dbo].[Snippets]...';


GO
BEGIN TRANSACTION;

SET TRANSACTION ISOLATION LEVEL SERIALIZABLE;

SET XACT_ABORT ON;

CREATE TABLE [dbo].[tmp_ms_xx_Snippets] (
    [Guid]        UNIQUEIDENTIFIER NOT NULL,
    [ImageData]   VARBINARY (MAX)  NOT NULL,
    [Content]     NVARCHAR (500)   NULL,
    [UserId]      INT              NOT NULL,
    [CreatedAt]   DATETIME         CONSTRAINT [DF_Snippets_CreatedAt] DEFAULT GETUTCDATE() NOT NULL,
    [ProcessedAt] DATETIME         NULL,
    [RuleId]      INT              NOT NULL,
    [IsBadData]   BIT              CONSTRAINT [DF_Snippets_IsBadData] DEFAULT 0 NOT NULL,
    [ProcessName] NVARCHAR (100)   NOT NULL,
    CONSTRAINT [tmp_ms_xx_constraint_PK_Snippets] PRIMARY KEY NONCLUSTERED ([Guid] ASC)
);

CREATE CLUSTERED INDEX [tmp_ms_xx_index_IX_Snippets_ProcessedAt_RuleId]
    ON [dbo].[tmp_ms_xx_Snippets]([ProcessedAt] ASC, [RuleId] ASC);

IF EXISTS (SELECT TOP 1 1 
           FROM   [dbo].[Snippets])
    BEGIN
        INSERT INTO [dbo].[tmp_ms_xx_Snippets] ([ProcessedAt], [RuleId], [ImageData], [Content], [Guid], [UserId], [CreatedAt], [IsBadData], [ProcessName])
        SELECT   [ProcessedAt],
                 [RuleId],
                 [ImageData],
                 [Content],
                 [Guid],
                 [UserId],
                 [CreatedAt],
                 [IsBadData],
                 [ProcessName]
        FROM     [dbo].[Snippets]
        ORDER BY [ProcessedAt] ASC, [RuleId] ASC;
    END

DROP TABLE [dbo].[Snippets];

EXECUTE sp_rename N'[dbo].[tmp_ms_xx_Snippets]', N'Snippets';

EXECUTE sp_rename N'[dbo].[Snippets].[tmp_ms_xx_index_IX_Snippets_ProcessedAt_RuleId]', N'IX_Snippets_ProcessedAt_RuleId', N'INDEX';

EXECUTE sp_rename N'[dbo].[tmp_ms_xx_constraint_PK_Snippets]', N'PK_Snippets', N'OBJECT';

COMMIT TRANSACTION;

SET TRANSACTION ISOLATION LEVEL READ COMMITTED;


GO
PRINT N'Altering [dbo].[GetSchemaVersion]...';


GO
-- Don't modify this file, it's used in the build process!
ALTER PROCEDURE [dbo].[GetSchemaVersion]
AS RETURN 41
GO
PRINT N'Update complete.';


GO
