/*
Deployment script for recorder

This code was generated by a tool.
Changes to this file may cause incorrect behavior and will be lost if
the code is regenerated.
*/

GO
SET ANSI_NULLS, ANSI_PADDING, ANSI_WARNINGS, ARITHABORT, CONCAT_NULL_YIELDS_NULL, QUOTED_IDENTIFIER ON;

SET NUMERIC_ROUNDABORT OFF;


GO
/*
:setvar DatabaseName "recorder"
:setvar DefaultFilePrefix "recorder"
:setvar DefaultDataPath ""
:setvar DefaultLogPath ""
*/

GO
:on error exit
GO
/*
Detect SQLCMD mode and disable script execution if SQLCMD mode is not supported.
To re-enable the script after enabling SQLCMD mode, execute the following:
SET NOEXEC OFF; 
*/
:setvar __IsSqlCmdEnabled "True"
GO
IF N'$(__IsSqlCmdEnabled)' NOT LIKE N'True'
    BEGIN
        PRINT N'SQLCMD mode must be enabled to successfully execute this script.';
        SET NOEXEC ON;
    END


GO
USE [$(DatabaseName)];


GO
PRINT N'Altering [dbo].[UsageStats]...';


GO
ALTER TABLE [dbo].[UsageStats]
    ADD [UsedBeaconClient] BIT CONSTRAINT [DF_UsageStats_UsedBeaconClient] DEFAULT 0 NOT NULL,
        [UsedVoxCtrl]      BIT CONSTRAINT [DF_UsageStats_UsedVoxCtrl] DEFAULT 0 NOT NULL,
        [UsedMobile]       BIT CONSTRAINT [DF_UsageStats_UsedMobile] DEFAULT 0 NOT NULL;


GO
PRINT N'Altering [dbo].[GetSchemaVersion]...';


GO
-- Don't modify this file, it's used in the build process!
ALTER PROCEDURE [dbo].[GetSchemaVersion]
AS RETURN 19
GO
PRINT N'Creating [dbo].[Client_CommitUsageStatsToEcomm]...';


GO
-- =============================================
-- Author: Zoltan Torok
-- =============================================
CREATE PROCEDURE [dbo].[Client_CommitUsageStatsToEcomm]
AS

	SET NOCOUNT ON
	SET XACT_ABORT ON

	declare @c_LocalDate datetime,
			@c_UserId int,
			@c_Id int,
			@result int

	BEGIN TRAN

	DECLARE upd_cursor CURSOR FORWARD_ONLY FOR
	SELECT 
		Id,
		LocalDate,
		UserId
	FROM UsageStats (UPDLOCK)
	WHERE
		IsAcked = 0
		AND (ComputerWorkTime + IvrWorkTime + MobileWorkTime + ManuallyAddedWorkTime) > 300000 -- 5 mins

	OPEN upd_cursor

	WHILE 1=1
	BEGIN
		FETCH NEXT FROM upd_cursor INTO 
			@c_Id,
			@c_LocalDate,
			@c_UserId

		IF @@FETCH_STATUS <> 0
			BREAK

		EXEC @result = [dbo].[Client_SetWorkedUsersOnDay] @userId = @c_UserId, @Day = @c_LocalDate
		IF @result = 0
		BEGIN
			UPDATE UsageStats
				SET IsAcked = 1
				WHERE Id = @c_Id
		END

	END

	CLOSE upd_cursor
	DEALLOCATE upd_cursor

	COMMIT TRAN
	RETURN 0
GO
PRINT N'Update complete.';


GO
