/*
Deployment script for recorder

This code was generated by a tool.
Changes to this file may cause incorrect behavior and will be lost if
the code is regenerated.
*/

GO
SET ANSI_NULLS, ANSI_PADDING, ANSI_WARNINGS, ARITHABORT, CONCAT_NULL_YIELDS_NULL, QUOTED_IDENTIFIER ON;

SET NUMERIC_ROUNDABORT OFF;


GO
/*
:setvar DatabaseName "recorder"
:setvar DefaultFilePrefix "recorder"
:setvar DefaultDataPath ""
:setvar DefaultLogPath ""
*/

GO
:on error exit
GO
/*
Detect SQLCMD mode and disable script execution if SQLCMD mode is not supported.
To re-enable the script after enabling SQLCMD mode, execute the following:
SET NOEXEC OFF; 
*/
:setvar __IsSqlCmdEnabled "True"
GO
IF N'$(__IsSqlCmdEnabled)' NOT LIKE N'True'
    BEGIN
        PRINT N'SQLCMD mode must be enabled to successfully execute this script.';
        SET NOEXEC ON;
    END


GO
USE [$(DatabaseName)];


GO
PRINT N'Altering [dbo].[ClientSettings]...';


GO
ALTER TABLE [dbo].[ClientSettings]
    ADD [IsNotificationShown] INT NULL;


GO
PRINT N'Altering [dbo].[ClientSettings_Versions_U]...';


GO
ALTER TRIGGER [dbo].[ClientSettings_Versions_U]
	ON [dbo].[ClientSettings]
	AFTER UPDATE
	AS
	BEGIN
		SET NOCOUNT ON
		DECLARE @nextValue BINARY(8)
		EXEC GetNextValueForSequence @nextValue OUTPUT
		IF ( UPDATE (Menu) ) 
		BEGIN
			UPDATE [ClientSettings] SET MenuVersion = @nextValue WHERE UserId IN (SELECT i.UserId FROM inserted i JOIN deleted d ON i.UserId = d.UserId WHERE i.Menu <> d.Menu OR (i.Menu IS NOT NULL AND d.Menu IS NULL) OR (i.Menu IS NULL AND d.Menu IS NOT NULL))
		END
		IF ( UPDATE (WorkDetectorRules) ) 
		BEGIN
			UPDATE [ClientSettings] SET WorkDetectorRulesVersion = @nextValue WHERE UserId IN (SELECT i.UserId FROM inserted i JOIN deleted d ON i.UserId = d.UserId WHERE i.WorkDetectorRules <> d.WorkDetectorRules OR (i.WorkDetectorRules IS NOT NULL AND d.WorkDetectorRules IS NULL) OR (i.WorkDetectorRules IS NULL AND d.WorkDetectorRules IS NOT NULL))
		END
		IF ( UPDATE (CensorRules) ) 
		BEGIN
			UPDATE [ClientSettings] SET CensorRulesVersion = @nextValue WHERE UserId IN (SELECT i.UserId FROM inserted i JOIN deleted d ON i.UserId = d.UserId WHERE i.CensorRules <> d.CensorRules OR (i.CensorRules IS NOT NULL AND d.CensorRules IS NULL) OR (i.CensorRules IS NULL AND d.CensorRules IS NOT NULL))
		END
		IF ( UPDATE (CollectorRules) ) 
		BEGIN
			UPDATE [ClientSettings] SET CollectorRulesVersion = @nextValue WHERE UserId IN (SELECT i.UserId FROM inserted i JOIN deleted d ON i.UserId = d.UserId WHERE i.CollectorRules <> d.CollectorRules OR (i.CollectorRules IS NOT NULL AND d.CollectorRules IS NULL) OR (i.CollectorRules IS NULL AND d.CollectorRules IS NOT NULL))
		END
		IF (UPDATE(MenuUpdateInterval) OR UPDATE(CaptureWorkItemInterval) OR UPDATE(CaptureActiveWindowInterval) OR UPDATE(CaptureScreenShotInterval)
			OR UPDATE(TimeSyncThreshold) OR UPDATE(JpegQuality) OR UPDATE(JpegScalePct) OR UPDATE(WorkTimeStartInMins)
			OR UPDATE(WorkTimeEndInMins) OR UPDATE(AfterWorkTimeIdleInMins) OR UPDATE(MaxOfflineWorkItems) OR UPDATE(DuringWorkTimeIdleInMins)
			OR UPDATE(DuringWorkTimeIdleManualInterval) OR UPDATE(MaxManualMeetingInterval) OR UPDATE(RuleRestrictions) OR UPDATE(IsMeetingTrackingEnabled)
			OR UPDATE(IsMeetingSubjectMandatory) OR UPDATE(BusyTimeThreshold) OR UPDATE(CoincidentalClientsEnabled) OR UPDATE(IsManualMeetingStartsOnLock)
			OR UPDATE(IsLotusNotesMeetingTrackingEnabled) OR UPDATE(RuleMatchingInterval) OR UPDATE(EnabledFeatures) OR UPDATE([PluginFailThreshold]) OR UPDATE(DefaultWorkId) 
			OR UPDATE(MouseMovingThreshold) OR UPDATE(CaptureDeadlockInMins) OR UPDATE(IsOutlookAddinRequired) OR UPDATE(IsOutlookAddinMailTrackingId) OR UPDATE(ManualWorkItemEditAgeLimit) 
			OR UPDATE(AutoReturnFromMeeting) OR UPDATE(IsOutlookAddinMailTrackingUseSubject)
			OR UPDATE(TelemetryMaxCount) OR UPDATE(TelemetryMaxAgeInMins) OR UPDATE(TelemetryCollectedKeys) OR UPDATE(IsMeetingUploadModifications) OR UPDATE(IsMeetingTentativeSynced)
			OR Update(IsInjectedInputAllowed) OR Update(DataCollectionSettings) OR Update(IsNotificationShown))
		BEGIN
			UPDATE [ClientSettings] SET ClientSettingsVersion = @nextValue 
			WHERE UserId IN 
			(
				SELECT i.UserId FROM inserted i JOIN deleted d ON i.UserId = d.UserId 
				WHERE i.MenuUpdateInterval <> d.MenuUpdateInterval OR (i.MenuUpdateInterval IS NOT NULL AND d.MenuUpdateInterval IS NULL) OR (i.MenuUpdateInterval IS NULL AND d.MenuUpdateInterval IS NOT NULL)
				OR i.CaptureWorkItemInterval <> d.CaptureWorkItemInterval OR (i.CaptureWorkItemInterval IS NOT NULL AND d.CaptureWorkItemInterval IS NULL) OR (i.CaptureWorkItemInterval IS NULL AND d.CaptureWorkItemInterval IS NOT NULL)
				OR i.CaptureActiveWindowInterval <> d.CaptureActiveWindowInterval OR (i.CaptureActiveWindowInterval IS NOT NULL AND d.CaptureActiveWindowInterval IS NULL) OR (i.CaptureActiveWindowInterval IS NULL AND d.CaptureActiveWindowInterval IS NOT NULL)
				OR i.CaptureScreenShotInterval <> d.CaptureScreenShotInterval OR (i.CaptureScreenShotInterval IS NOT NULL AND d.CaptureScreenShotInterval IS NULL) OR (i.CaptureScreenShotInterval IS NULL AND d.CaptureScreenShotInterval IS NOT NULL)
				OR i.TimeSyncThreshold <> d.TimeSyncThreshold OR (i.TimeSyncThreshold IS NOT NULL AND d.TimeSyncThreshold IS NULL) OR (i.TimeSyncThreshold IS NULL AND d.TimeSyncThreshold IS NOT NULL)
				OR i.JpegQuality <> d.JpegQuality OR (i.JpegQuality IS NOT NULL AND d.JpegQuality IS NULL) OR (i.JpegQuality IS NULL AND d.JpegQuality IS NOT NULL)
				OR i.JpegScalePct <> d.JpegScalePct OR (i.JpegScalePct IS NOT NULL AND d.JpegScalePct IS NULL) OR (i.JpegScalePct IS NULL AND d.JpegScalePct IS NOT NULL)
				OR i.WorkTimeStartInMins <> d.WorkTimeStartInMins OR (i.WorkTimeStartInMins IS NOT NULL AND d.WorkTimeStartInMins IS NULL) OR (i.WorkTimeStartInMins IS NULL AND d.WorkTimeStartInMins IS NOT NULL)
				OR i.WorkTimeEndInMins <> d.WorkTimeEndInMins OR (i.WorkTimeEndInMins IS NOT NULL AND d.WorkTimeEndInMins IS NULL) OR (i.WorkTimeEndInMins IS NULL AND d.WorkTimeEndInMins IS NOT NULL)
				OR i.AfterWorkTimeIdleInMins <> d.AfterWorkTimeIdleInMins OR (i.AfterWorkTimeIdleInMins IS NOT NULL AND d.AfterWorkTimeIdleInMins IS NULL) OR (i.AfterWorkTimeIdleInMins IS NULL AND d.AfterWorkTimeIdleInMins IS NOT NULL)
				OR i.MaxOfflineWorkItems <> d.MaxOfflineWorkItems OR (i.MaxOfflineWorkItems IS NOT NULL AND d.MaxOfflineWorkItems IS NULL) OR (i.MaxOfflineWorkItems IS NULL AND d.MaxOfflineWorkItems IS NOT NULL)
				OR i.DuringWorkTimeIdleInMins <> d.DuringWorkTimeIdleInMins OR (i.DuringWorkTimeIdleInMins IS NOT NULL AND d.DuringWorkTimeIdleInMins IS NULL) OR (i.DuringWorkTimeIdleInMins IS NULL AND d.DuringWorkTimeIdleInMins IS NOT NULL)
				OR i.DuringWorkTimeIdleManualInterval <> d.DuringWorkTimeIdleManualInterval OR (i.DuringWorkTimeIdleManualInterval IS NOT NULL AND d.DuringWorkTimeIdleManualInterval IS NULL) OR (i.DuringWorkTimeIdleManualInterval IS NULL AND d.DuringWorkTimeIdleManualInterval IS NOT NULL)
				OR i.MaxManualMeetingInterval <> d.MaxManualMeetingInterval OR (i.MaxManualMeetingInterval IS NOT NULL AND d.MaxManualMeetingInterval IS NULL) OR (i.MaxManualMeetingInterval IS NULL AND d.MaxManualMeetingInterval IS NOT NULL)
				OR i.RuleRestrictions <> d.RuleRestrictions OR (i.RuleRestrictions IS NOT NULL AND d.RuleRestrictions IS NULL) OR (i.RuleRestrictions IS NULL AND d.RuleRestrictions IS NOT NULL)
				OR i.IsMeetingTrackingEnabled <> d.IsMeetingTrackingEnabled OR (i.IsMeetingTrackingEnabled IS NOT NULL AND d.IsMeetingTrackingEnabled IS NULL) OR (i.IsMeetingTrackingEnabled IS NULL AND d.IsMeetingTrackingEnabled IS NOT NULL)
				OR i.IsMeetingSubjectMandatory <> d.IsMeetingSubjectMandatory OR (i.IsMeetingSubjectMandatory IS NOT NULL AND d.IsMeetingSubjectMandatory IS NULL) OR (i.IsMeetingSubjectMandatory IS NULL AND d.IsMeetingSubjectMandatory IS NOT NULL)
				OR i.BusyTimeThreshold <> d.BusyTimeThreshold OR (i.BusyTimeThreshold IS NOT NULL AND d.BusyTimeThreshold IS NULL) OR (i.BusyTimeThreshold IS NULL AND d.BusyTimeThreshold IS NOT NULL)
				OR i.CoincidentalClientsEnabled <> d.CoincidentalClientsEnabled OR (i.CoincidentalClientsEnabled IS NOT NULL AND d.CoincidentalClientsEnabled IS NULL) OR (i.CoincidentalClientsEnabled IS NULL AND d.CoincidentalClientsEnabled IS NOT NULL)
				OR i.IsManualMeetingStartsOnLock <> d.IsManualMeetingStartsOnLock OR (i.IsManualMeetingStartsOnLock IS NOT NULL AND d.IsManualMeetingStartsOnLock IS NULL) OR (i.IsManualMeetingStartsOnLock IS NULL AND d.IsManualMeetingStartsOnLock IS NOT NULL)
				OR i.IsLotusNotesMeetingTrackingEnabled <> d.IsLotusNotesMeetingTrackingEnabled OR (i.IsLotusNotesMeetingTrackingEnabled IS NOT NULL AND d.IsLotusNotesMeetingTrackingEnabled IS NULL) OR (i.IsLotusNotesMeetingTrackingEnabled IS NULL AND d.IsLotusNotesMeetingTrackingEnabled IS NOT NULL)
				OR i.RuleMatchingInterval <> d.RuleMatchingInterval OR (i.RuleMatchingInterval IS NOT NULL AND d.RuleMatchingInterval IS NULL) OR (i.RuleMatchingInterval IS NULL AND d.RuleMatchingInterval IS NOT NULL)
				OR i.IsOutlookAddinRequired <> d.IsOutlookAddinRequired OR (i.IsOutlookAddinRequired IS NOT NULL AND d.IsOutlookAddinRequired IS NULL) OR (i.IsOutlookAddinRequired IS NULL and d.IsOutlookAddinRequired IS NOT NULL)
				OR i.IsOutlookAddinMailTrackingId <> d.IsOutlookAddinMailTrackingId OR (i.IsOutlookAddinMailTrackingId IS NOT NULL AND d.IsOutlookAddinMailTrackingId IS NULL) OR (i.IsOutlookAddinMailTrackingId IS NULL and d.IsOutlookAddinMailTrackingId IS NOT NULL)
				OR i.DefaultWorkId <> d.DefaultWorkId OR (i.DefaultWorkId IS NOT NULL AND d.DefaultWorkId IS NULL) OR (i.DefaultWorkId IS NULL and d.DefaultWorkId IS NOT NULL)
				OR i.CaptureDeadlockInMins <> d.CaptureDeadlockInMins OR (i.CaptureDeadlockInMins IS NOT NULL AND d.CaptureDeadlockInMins IS NULL) OR (i.CaptureDeadlockInMins IS NULL and d.CaptureDeadlockInMins IS NOT NULL)
				OR i.MouseMovingThreshold <> d.MouseMovingThreshold OR (i.MouseMovingThreshold IS NOT NULL AND d.MouseMovingThreshold IS NULL) OR (i.MouseMovingThreshold IS NULL and d.MouseMovingThreshold IS NOT NULL)
				OR i.EnabledFeatures <> d.EnabledFeatures OR (i.EnabledFeatures IS NOT NULL AND d.EnabledFeatures IS NULL) OR (i.EnabledFeatures IS NULL and d.EnabledFeatures IS NOT NULL)
				OR i.PluginFailThreshold <> d.PluginFailThreshold OR (i.PluginFailThreshold IS NOT NULL AND d.PluginFailThreshold IS NULL) OR (i.PluginFailThreshold IS NULL and d.PluginFailThreshold IS NOT NULL)
				OR i.[CollectedItemAggregateInMins] <> d.[CollectedItemAggregateInMins] OR (i.[CollectedItemAggregateInMins] IS NOT NULL AND d.[CollectedItemAggregateInMins] IS NULL) OR (i.[CollectedItemAggregateInMins] IS NULL and d.[CollectedItemAggregateInMins] IS NOT NULL)
				OR i.[ForceCountdownRules] <> d.[ForceCountdownRules] OR (i.[ForceCountdownRules] IS NOT NULL AND d.[ForceCountdownRules] IS NULL) OR (i.[ForceCountdownRules] IS NULL and d.[ForceCountdownRules] IS NOT NULL)
				OR i.ManualWorkItemEditAgeLimit <> d.ManualWorkItemEditAgeLimit OR (i.ManualWorkItemEditAgeLimit IS NOT NULL AND d.ManualWorkItemEditAgeLimit IS NULL) OR (i.ManualWorkItemEditAgeLimit IS NULL and d.ManualWorkItemEditAgeLimit IS NOT NULL)
				OR i.AutoReturnFromMeeting <> d.AutoReturnFromMeeting OR (i.AutoReturnFromMeeting IS NOT NULL AND d.AutoReturnFromMeeting IS NULL) OR (i.AutoReturnFromMeeting IS NULL and d.AutoReturnFromMeeting IS NOT NULL)
				OR i.IsOutlookAddinMailTrackingUseSubject <> d.IsOutlookAddinMailTrackingUseSubject OR (i.IsOutlookAddinMailTrackingUseSubject IS NOT NULL AND d.IsOutlookAddinMailTrackingUseSubject IS NULL) OR (i.IsOutlookAddinMailTrackingUseSubject IS NULL and d.IsOutlookAddinMailTrackingUseSubject IS NOT NULL)
				OR i.TelemetryMaxCount <> d.TelemetryMaxCount OR (i.TelemetryMaxCount IS NOT NULL AND d.TelemetryMaxCount IS NULL) OR (i.TelemetryMaxCount IS NULL and d.TelemetryMaxCount IS NOT NULL)
				OR i.TelemetryMaxAgeInMins <> d.TelemetryMaxAgeInMins OR (i.TelemetryMaxAgeInMins IS NOT NULL AND d.TelemetryMaxAgeInMins IS NULL) OR (i.TelemetryMaxAgeInMins IS NULL and d.TelemetryMaxAgeInMins IS NOT NULL)
				OR i.TelemetryCollectedKeys <> d.TelemetryCollectedKeys OR (i.TelemetryCollectedKeys IS NOT NULL AND d.TelemetryCollectedKeys IS NULL) OR (i.TelemetryCollectedKeys IS NULL and d.TelemetryCollectedKeys IS NOT NULL)
				OR i.IsMeetingUploadModifications <> d.IsMeetingUploadModifications OR (i.IsMeetingUploadModifications IS NOT NULL AND d.IsMeetingUploadModifications IS NULL) OR (i.IsMeetingUploadModifications IS NULL and d.IsMeetingUploadModifications IS NOT NULL)
				OR i.IsMeetingTentativeSynced <> d.IsMeetingTentativeSynced OR (i.IsMeetingTentativeSynced IS NOT NULL AND d.IsMeetingTentativeSynced IS NULL) OR (i.IsMeetingTentativeSynced IS NULL and d.IsMeetingTentativeSynced IS NOT NULL)
				OR i.IsInjectedInputAllowed <> d.IsInjectedInputAllowed OR (i.IsInjectedInputAllowed IS NOT NULL AND d.IsInjectedInputAllowed IS NULL) OR (i.IsInjectedInputAllowed IS NULL and d.IsInjectedInputAllowed IS NOT NULL)
				OR i.DataCollectionSettings <> d.DataCollectionSettings OR (i.DataCollectionSettings IS NOT NULL AND d.DataCollectionSettings IS NULL) OR (i.DataCollectionSettings IS NULL and d.DataCollectionSettings IS NOT NULL)
				OR i.IsNotificationShown <> d.IsNotificationShown OR (i.IsNotificationShown IS NOT NULL AND d.IsNotificationShown IS NULL) OR (i.IsNotificationShown IS NULL and d.IsNotificationShown IS NOT NULL)
				)
		END
	END
GO
PRINT N'Altering [dbo].[GetSchemaVersion]...';


GO
-- Don't modify this file, it's used in the build process!
ALTER PROCEDURE [dbo].[GetSchemaVersion]
AS RETURN 29
GO
PRINT N'Refreshing [dbo].[GetUsersForUsageStats]...';


GO
EXECUTE sp_refreshsqlmodule N'[dbo].[GetUsersForUsageStats]';


GO
PRINT N'Update complete.';


GO
