/*
Deployment script for recorder

This code was generated by a tool.
Changes to this file may cause incorrect behavior and will be lost if
the code is regenerated.
*/

GO
SET ANSI_NULLS, ANSI_PADDING, ANSI_WARNINGS, ARITHABORT, CONCAT_NULL_YIELDS_NULL, QUOTED_IDENTIFIER ON;

SET NUMERIC_ROUNDABORT OFF;


GO
/*
:setvar DatabaseName "recorder"
:setvar DefaultFilePrefix "recorder"
:setvar DefaultDataPath ""
:setvar DefaultLogPath ""
*/

GO
:on error exit
GO
/*
Detect SQLCMD mode and disable script execution if SQLCMD mode is not supported.
To re-enable the script after enabling SQLCMD mode, execute the following:
SET NOEXEC OFF; 
*/
:setvar __IsSqlCmdEnabled "True"
GO
IF N'$(__IsSqlCmdEnabled)' NOT LIKE N'True'
    BEGIN
        PRINT N'SQLCMD mode must be enabled to successfully execute this script.';
        SET NOEXEC ON;
    END


GO
USE [$(DatabaseName)];


GO
PRINT N'Altering [dbo].[GetSchemaVersion]...';


GO
-- Don't modify this file, it's used in the build process!
ALTER PROCEDURE [dbo].[GetSchemaVersion]
AS RETURN 17
GO

CREATE PROCEDURE [dbo].[SwipeOutdatedScreens]
	@tillDate datetime
as 
begin
	declare @maxCaptureId bigint, 
	@start datetime=getdate()
	set nocount on
	SET @maxCaptureId = (SELECT top 1 DesktopCaptureId
				  FROM [Screens]
				  where CreateDate < @tillDate
				  order by CreateDate desc)
	
	/* Deleting dbo.Screens */
	declare @currentStartDate datetime
	SELECT @currentStartDate = MIN(CreateDate)
	  FROM [Screens]
	  
	while @currentStartDate < @tillDate
	begin
		
		declare @currentEndDate datetime = DATEAdd(DAY, 1, @currentStartDate)

		begin transaction

			DELETE FROM Screens 
			where CreateDate between @currentStartDate and @currentEndDate
		
		commit
		
		set @currentStartDate = @currentEndDate

		WAITFOR DELAY '00:00:05';		-- wait a few seconds to let others write the table

	end
	
	/* Deleting dbo.DesktopCaptures */
	declare @numberOfRowsToDeletePerIteration int = 1000000		-- Deleting 1M records takes 5-10 sec on my laptop (aszabo)
	declare @currentId bigint
	SELECT @currentId = MIN(Id)
	  FROM [dbo].[DesktopCaptures]

	ALTER TABLE Screens NOCHECK CONSTRAINT FK_Screens_DesktopCaptures
	  
	while @currentId <= @maxCaptureId
	begin
		
		declare @currentEndId bigint = @currentId + @numberOfRowsToDeletePerIteration
		if @currentEndId > @maxCaptureId
			SET @currentEndId = @maxCaptureId

		begin transaction

			DELETE FROM DesktopCaptures 
			where Id between @currentId and @currentEndId
		
		commit
		
		set @currentId = @currentEndId+1

		WAITFOR DELAY '00:00:05';		-- wait a few seconds to let others write the table

	end

	ALTER TABLE Screens WITH NOCHECK CHECK CONSTRAINT FK_Screens_DesktopCaptures
end
GO
PRINT N'Update complete.';


GO
