/*
Deployment script for recorder

This code was generated by a tool.
Changes to this file may cause incorrect behavior and will be lost if
the code is regenerated.
*/

GO
SET ANSI_NULLS, ANSI_PADDING, ANSI_WARNINGS, ARITHABORT, CONCAT_NULL_YIELDS_NULL, QUOTED_IDENTIFIER ON;

SET NUMERIC_ROUNDABORT OFF;


GO
/*
:setvar DatabaseName "recorder"
:setvar DefaultFilePrefix "recorder"
:setvar DefaultDataPath ""
:setvar DefaultLogPath ""
*/

GO
:on error exit
GO
/*
Detect SQLCMD mode and disable script execution if SQLCMD mode is not supported.
To re-enable the script after enabling SQLCMD mode, execute the following:
SET NOEXEC OFF; 
*/
:setvar __IsSqlCmdEnabled "True"
GO
IF N'$(__IsSqlCmdEnabled)' NOT LIKE N'True'
    BEGIN
        PRINT N'SQLCMD mode must be enabled to successfully execute this script.';
        SET NOEXEC ON;
    END


GO
USE [$(DatabaseName)];


GO

PRINT N'Dropping view [dbo].[Screenshots]...';
GO

DROP VIEW [dbo].[Screenshots];
GO

PRINT N'Adding ComputerId and ReceiveDate columns to [dbo].[Screens]...';
GO

ALTER TABLE [dbo].[Screens] ADD [ComputerId] [int] NOT NULL CONSTRAINT DF_ScreenShots_ComputerId DEFAULT 0, [ReceiveDate] [datetime] NOT NULL CONSTRAINT DF_ScreenShots_ReceiveDate DEFAULT GETDATE();

PRINT N'Updating new ComputerId and ReceiveDate column values to [dbo].[Screens]...';
GO

UPDATE [dbo].[Screens] 
SET ComputerId = w.ComputerId,
	ReceiveDate = w.ReceiveDate
FROM [dbo].[WorkItems] w
JOIN [dbo].[DesktopCaptures] d ON d.WorkItemId = w.Id
WHERE d.Id = Screens.DesktopCaptureId;

PRINT N'Dropping CONSTRAINT [FK_Screens_DesktopCaptures] from [dbo].[Screens]...';
GO

ALTER TABLE [dbo].[Screens] DROP CONSTRAINT [FK_Screens_DesktopCaptures];

PRINT N'Dropping COLUMN DesktopCaptureId from [dbo].[Screens]...';
GO

ALTER TABLE [dbo].[Screens] DROP COLUMN DesktopCaptureId;

PRINT N'Renaming [dbo].[Screens] to [dbo].[ScreenShots]...';
GO

EXEC sp_rename '[dbo].[Screens].[IX_Screens_CreateDate_Clust]', 'IX_ScreenShots_CreateDate_Clust', 'INDEX';
EXEC sp_rename '[dbo].[Screens]', 'ScreenShots';
EXEC sp_rename '[dbo].[PK_Screens]', 'PK_ScreenShots';

GO
PRINT N'Creating [dbo].[ScreenShots].[IX_Screenshots_UserId_CreateDate]...';


GO
CREATE NONCLUSTERED INDEX [IX_Screenshots_UserId_CreateDate]
    ON [dbo].[ScreenShots]([UserId] ASC, [CreateDate] ASC);


GO
PRINT N'Deleting [dbo].[DesktopCaptures]...';
GO
DROP TABLE [dbo].[DesktopCaptures];
GO

PRINT N'Deleting null constraints on the new fields in [dbo].[ScreenShots]...';
GO

IF  EXISTS (SELECT * FROM dbo.sysobjects WHERE id = OBJECT_ID(N'[DF_ScreenShots_ComputerId]') AND type = 'D')
BEGIN
ALTER TABLE [dbo].[ScreenShots] DROP CONSTRAINT [DF_ScreenShots_ComputerId]
END

IF  EXISTS (SELECT * FROM dbo.sysobjects WHERE id = OBJECT_ID(N'[DF_ScreenShots_ReceiveDate]') AND type = 'D')
BEGIN
ALTER TABLE [dbo].[ScreenShots] DROP CONSTRAINT [DF_ScreenShots_ReceiveDate]
END
GO

PRINT N'Altering [dbo].[SwipeOutdatedScreens]...';
GO

ALTER PROCEDURE [dbo].[SwipeOutdatedScreens]
	@tillDate datetime
as 
begin
	declare @start datetime=getdate()
	set nocount on
	
	/* Deleting dbo.Screenshots */
	declare @currentStartDate datetime
	SELECT @currentStartDate = MIN(CreateDate)
	  FROM [ScreenShots]
	  
	while @currentStartDate < @tillDate
	begin
		
		declare @currentEndDate datetime = DATEAdd(DAY, 1, @currentStartDate)

		begin transaction

			DELETE FROM Screenshots
			where CreateDate between @currentStartDate and @currentEndDate
		
		commit
		
		set @currentStartDate = @currentEndDate

		WAITFOR DELAY '00:00:05';		-- wait a few seconds to let others write the table

	end
end
GO

PRINT N'Altering [dbo].[GetSchemaVersion]...';


GO
-- Don't modify this file, it's used in the build process!
ALTER PROCEDURE [dbo].[GetSchemaVersion]
AS RETURN 38
GO
PRINT N'Update complete.';


GO
