/*
Deployment script for recorder

This code was generated by a tool.
Changes to this file may cause incorrect behavior and will be lost if
the code is regenerated.
*/

GO
SET ANSI_NULLS, ANSI_PADDING, ANSI_WARNINGS, ARITHABORT, CONCAT_NULL_YIELDS_NULL, QUOTED_IDENTIFIER ON;

SET NUMERIC_ROUNDABORT OFF;


GO
/*
:setvar DatabaseName "recorder"
:setvar DefaultFilePrefix "recorder"
:setvar DefaultDataPath ""
:setvar DefaultLogPath ""
*/

GO
:on error exit
GO
/*
Detect SQLCMD mode and disable script execution if SQLCMD mode is not supported.
To re-enable the script after enabling SQLCMD mode, execute the following:
SET NOEXEC OFF; 
*/
:setvar __IsSqlCmdEnabled "True"
GO
IF N'$(__IsSqlCmdEnabled)' NOT LIKE N'True'
    BEGIN
        PRINT N'SQLCMD mode must be enabled to successfully execute this script.';
        SET NOEXEC ON;
    END


GO
USE [$(DatabaseName)];


GO
PRINT N'Altering [dbo].[CalendarExceptions]...';


GO
ALTER TABLE [dbo].[CalendarExceptions]
    ADD [TargetWorkTimeInMinutes] SMALLINT NULL,
        [CoreTimeEnd]             SMALLINT NULL;


GO
PRINT N'Altering [dbo].[Calendars]...';


GO
ALTER TABLE [dbo].[Calendars]
    ADD [TargetWorkTimeInMinutesMonday]    SMALLINT NULL,
        [TargetWorkTimeInMinutesTuesday]   SMALLINT NULL,
        [TargetWorkTimeInMinutesWednesday] SMALLINT NULL,
        [TargetWorkTimeInMinutesThursday]  SMALLINT NULL,
        [TargetWorkTimeInMinutesFriday]    SMALLINT NULL,
        [TargetWorkTimeInMinutesSaturday]  SMALLINT NULL,
        [TargetWorkTimeInMinutesSunday]    SMALLINT NULL,
        [CoreTimeEndMonday]                SMALLINT NULL,
        [CoreTimeEndTuesday]               SMALLINT NULL,
        [CoreTimeEndWednesday]             SMALLINT NULL,
        [CoreTimeEndThursday]              SMALLINT NULL,
        [CoreTimeEndFriday]                SMALLINT NULL,
        [CoreTimeEndSaturday]              SMALLINT NULL,
        [CoreTimeEndSunday]                SMALLINT NULL;


GO
PRINT N'Refreshing [dbo].[GetInheritedCalendarIds]...';


GO
EXECUTE sp_refreshsqlmodule N'[dbo].[GetInheritedCalendarIds]';


GO
PRINT N'Altering [dbo].[GetSchemaVersion]...';


GO
-- Don't modify this file, it's used in the build process!
ALTER PROCEDURE [dbo].[GetSchemaVersion]
AS RETURN 6
GO
PRINT N'Refreshing [dbo].[GetFlattenedCalendarExceptions]...';


GO
EXECUTE sp_refreshsqlmodule N'[dbo].[GetFlattenedCalendarExceptions]';


GO
PRINT N'Update complete.';


GO
