/*
Deployment script for recorder

This code was generated by a tool.
Changes to this file may cause incorrect behavior and will be lost if
the code is regenerated.
*/

GO
SET ANSI_NULLS, ANSI_PADDING, ANSI_WARNINGS, ARITHABORT, CONCAT_NULL_YIELDS_NULL, QUOTED_IDENTIFIER ON;

SET NUMERIC_ROUNDABORT OFF;


GO
/*
:setvar DatabaseName "recorder"
:setvar DefaultFilePrefix "recorder"
:setvar DefaultDataPath ""
:setvar DefaultLogPath ""
*/

GO
:on error exit
GO
/*
Detect SQLCMD mode and disable script execution if SQLCMD mode is not supported.
To re-enable the script after enabling SQLCMD mode, execute the following:
SET NOEXEC OFF; 
*/
:setvar __IsSqlCmdEnabled "True"
GO
IF N'$(__IsSqlCmdEnabled)' NOT LIKE N'True'
    BEGIN
        PRINT N'SQLCMD mode must be enabled to successfully execute this script.';
        SET NOEXEC ON;
    END


GO
USE [$(DatabaseName)];


GO
PRINT N'Altering [dbo].[ClientComputerAddresses]...';


GO
ALTER TABLE [dbo].[ClientComputerAddresses]
    ADD [ClientComputerLocalAddressId] INT NULL;


GO
PRINT N'Creating [dbo].[ClientComputerLocalAddresses]...';


GO
CREATE TABLE [dbo].[ClientComputerLocalAddresses] (
    [Id]          INT           IDENTITY (1, 1) NOT NULL,
    [AddressList] VARCHAR (150) NOT NULL,
    CONSTRAINT [PK_ClientComputerLocalAddresses] PRIMARY KEY CLUSTERED ([Id] ASC) ON [PRIMARY]
) ON [PRIMARY];


GO
PRINT N'Creating [dbo].[ClientComputerLocalAddresses].[IX_ClientComputerLocalAddresses]...';


GO
CREATE UNIQUE NONCLUSTERED INDEX [IX_ClientComputerLocalAddresses]
    ON [dbo].[ClientComputerLocalAddresses]([AddressList] ASC)
    ON [PRIMARY];


GO
PRINT N'Altering [dbo].[ReportClientComputerAddress]...';


GO
-- =============================================
-- Author: Zoltan Torok
-- Update: Ferenc Buzas
-- =============================================
ALTER PROCEDURE [dbo].[ReportClientComputerAddress]
	(
	@userId int,
	@computerId int,
	@address varchar(39),
	@locals varchar(150)
	)
AS
	SET NOCOUNT ON
	-- SET XACT_ABORT ON will cause the transaction to be uncommittable  
	-- when the constraint violation occurs.  
	SET XACT_ABORT ON

	IF @userId IS NULL OR @computerId IS NULL
	BEGIN
		RAISERROR('@userId and @computerId cannot be NULL', 16, 1)
		RETURN
	END

BEGIN TRAN

	declare @cId int, @cAddress varchar(39), @clientComputerAddressesId int, @localsId int

	SELECT @cId = [Id]
		  ,@cAddress = [Address]
	  FROM [dbo].[ClientComputerAddresses] WITH (UPDLOCK, HOLDLOCK)
	 WHERE [UserId] = @userId
	   AND [ComputerId] = @computerId
	   AND [IsCurrent] = 1

	IF (@@ROWCOUNT > 1)
	BEGIN
		RAISERROR('More than one current versions', 16, 1)
		ROLLBACK
		RETURN
	END

	SELECT @localsId = [Id]
	  FROM [dbo].[ClientComputerLocalAddresses]
	 WHERE [AddressList] = @locals
	 
	BEGIN TRY
		--lookup rec
		IF( @localsId IS NULL AND @locals IS NOT NULL)
		BEGIN
			INSERT INTO [dbo].[ClientComputerLocalAddresses]([AddressList]) 
				 VALUES (@locals);
			SELECT @localsId = @@IDENTITY
		END

		SELECT @clientComputerAddressesId=Id 
		  FROM [dbo].[ClientComputerAddresses]
		 WHERE [UserId] = @userId
		   AND [ComputerId] = @computerId
		   AND [IsCurrent] = 1

		--same version
		IF (@cId IS NOT NULL AND ((@address IS NULL AND @cAddress IS NULL) OR (@address IS NOT NULL AND @cAddress IS NOT NULL AND @address = @cAddress)))
		BEGIN
			UPDATE [dbo].[ClientComputerAddresses]
			   SET [LastReceiveDate] = GETUTCDATE(),
				   [ClientComputerLocalAddressId] = @localsId
			 WHERE [Id] = @clientComputerAddressesId
		END
		ELSE --new version
		BEGIN
			UPDATE [dbo].[ClientComputerAddresses]
			   SET [IsCurrent] = 0
			 WHERE [Id] = @clientComputerAddressesId

			INSERT INTO [dbo].[ClientComputerAddresses]
					   ([UserId]
					   ,[ComputerId]
					   ,[Address]
					   ,[IsCurrent]
					   ,[FirstReceiveDate]
					   ,[LastReceiveDate]
					   ,[ClientComputerLocalAddressId])
				 VALUES
					   (@userId
					   ,@computerId
					   ,@address
					   ,1
					   ,GETUTCDATE()
					   ,GETUTCDATE()
					   ,@localsId)
		END
		COMMIT TRAN
	END TRY
	BEGIN CATCH
		IF @@TRANCOUNT > 0
			ROLLBACK TRANSACTION;
 
		DECLARE @ErrorNumber INT = ERROR_NUMBER();
		DECLARE @ErrorLine INT = ERROR_LINE();
		DECLARE @ErrorMessage NVARCHAR(4000) = ERROR_MESSAGE();
		DECLARE @ErrorSeverity INT = ERROR_SEVERITY();
		DECLARE @ErrorState INT = ERROR_STATE();
 
		RAISERROR(N'IP:%s', @ErrorSeverity, @ErrorState, @locals);
	END CATCH
RETURN
GO
PRINT N'Altering [dbo].[GetSchemaVersion]...';


GO
-- Don't modify this file, it's used in the build process!
ALTER PROCEDURE [dbo].[GetSchemaVersion]
AS RETURN 24
GO
PRINT N'Update complete.';


GO
