/*
Deployment script for recorder

This code was generated by a tool.
Changes to this file may cause incorrect behavior and will be lost if
the code is regenerated.
*/

GO
SET ANSI_NULLS, ANSI_PADDING, ANSI_WARNINGS, ARITHABORT, CONCAT_NULL_YIELDS_NULL, QUOTED_IDENTIFIER ON;

SET NUMERIC_ROUNDABORT OFF;


GO
/*
:setvar DatabaseName "recorder"
:setvar DefaultFilePrefix "recorder"
:setvar DefaultDataPath ""
:setvar DefaultLogPath ""
*/

GO
:on error exit
GO
/*
Detect SQLCMD mode and disable script execution if SQLCMD mode is not supported.
To re-enable the script after enabling SQLCMD mode, execute the following:
SET NOEXEC OFF; 
*/
:setvar __IsSqlCmdEnabled "True"
GO
IF N'$(__IsSqlCmdEnabled)' NOT LIKE N'True'
    BEGIN
        PRINT N'SQLCMD mode must be enabled to successfully execute this script.';
        SET NOEXEC ON;
    END


GO
USE [$(DatabaseName)];


GO
PRINT N'Dropping [dbo].[ClientComputerVersions].[IX_ClientComputerVersions_UserId_ComputerId_IsCurrent]...';


GO
DROP INDEX [IX_ClientComputerVersions_UserId_ComputerId_IsCurrent]
    ON [dbo].[ClientComputerVersions];


GO
PRINT N'Altering [dbo].[ClientComputerVersions]...';


GO
ALTER TABLE [dbo].[ClientComputerVersions]
    ADD [Application] NVARCHAR (50) NULL;


GO
PRINT N'Creating [dbo].[ClientComputerVersions].[IX_ClientComputerVersions_UserId_ComputerId_Application_IsCurrent]...';


GO
CREATE NONCLUSTERED INDEX [IX_ClientComputerVersions_UserId_ComputerId_Application_IsCurrent]
    ON [dbo].[ClientComputerVersions]([UserId] ASC, [ComputerId] ASC, [Application] ASC, [IsCurrent] ASC);


GO
PRINT N'Altering [dbo].[ReportClientComputerVersion]...';


GO
-- =============================================
-- Author: Zoltan Torok
-- =============================================
ALTER PROCEDURE [dbo].[ReportClientComputerVersion]
	(
	@userId int,
	@computerId int,
	@major int,
	@minor int,
	@build int,
	@revision int,
	@application nvarchar(50)
	)
AS
	SET NOCOUNT ON
	SET XACT_ABORT ON

	IF @userId IS NULL OR @computerId IS NULL OR @major IS NULL OR @minor IS NULL OR @build IS NULL OR @revision IS NULL
	BEGIN
		RAISERROR('@userId, @computerId, @major, @minor, @build and @revision cannot be NULL', 16, 1)
		RETURN
	END

BEGIN TRAN

declare @cId int, @cMajor int, @cMinor int, @cBuild int, @cRevision int

SELECT @cId = [Id]
      ,@cMajor = [Major]
      ,@cMinor = [Minor]
      ,@cBuild = [Build]
      ,@cRevision = [Revision]
  FROM [dbo].[ClientComputerVersions] WITH (UPDLOCK, HOLDLOCK)
 WHERE [UserId] = @userId
   AND [ComputerId] = @computerId
   AND [Application] = @application
   AND [IsCurrent] = 1

IF (@@rowcount > 1)
BEGIN
	RAISERROR('More than one current versions', 16, 1)
	ROLLBACK
	RETURN
END

--same version
IF (@cMajor IS NOT NULL AND @major = @cMajor AND @minor = @cMinor AND @build = @cBuild AND @revision = @cRevision)
BEGIN
	UPDATE [dbo].[ClientComputerVersions]
	   SET [LastReceiveDate] = GETUTCDATE()
	 WHERE [UserId] = @userId
	   AND [ComputerId] = @computerId
	   AND [Application] = @application
	   AND [IsCurrent] = 1
END
ELSE --new version
BEGIN
	UPDATE [dbo].[ClientComputerVersions]
	   SET [IsCurrent] = 0
	 WHERE [UserId] = @userId
	   AND [ComputerId] = @computerId
	   AND [Application] = @application
	   AND [IsCurrent] = 1

	INSERT INTO [dbo].[ClientComputerVersions]
			   ([UserId]
			   ,[ComputerId]
			   ,[Major]
			   ,[Minor]
			   ,[Build]
			   ,[Revision]
			   ,[IsCurrent]
			   ,[FirstReceiveDate]
			   ,[LastReceiveDate]
			   ,[Application])
		 VALUES
			   (@userId
			   ,@computerId
			   ,@major
			   ,@minor
			   ,@build
			   ,@revision
			   ,1
			   ,GETUTCDATE()
			   ,GETUTCDATE()
			   ,@application)
END

COMMIT TRAN
	RETURN
GO
PRINT N'Altering [dbo].[GetSchemaVersion]...';


GO
-- Don't modify this file, it's used in the build process!
ALTER PROCEDURE [dbo].[GetSchemaVersion]
AS RETURN 47
GO
PRINT N'Update complete.';


GO
