--This script is generated by hand
GO
SET ANSI_NULLS, ANSI_PADDING, ANSI_WARNINGS, ARITHABORT, CONCAT_NULL_YIELDS_NULL, QUOTED_IDENTIFIER ON;

SET NUMERIC_ROUNDABORT OFF;


GO
/*
:setvar DatabaseName "recorder"
:setvar DefaultFilePrefix "recorder"
:setvar DefaultDataPath ""
:setvar DefaultLogPath ""
*/

GO
:on error exit
GO
/*
Detect SQLCMD mode and disable script execution if SQLCMD mode is not supported.
To re-enable the script after enabling SQLCMD mode, execute the following:
SET NOEXEC OFF; 
*/
:setvar __IsSqlCmdEnabled "True"
GO
IF N'$(__IsSqlCmdEnabled)' NOT LIKE N'True'
    BEGIN
        PRINT N'SQLCMD mode must be enabled to successfully execute this script.';
        SET NOEXEC ON;
    END


GO
USE [$(DatabaseName)];


GO
PRINT N'Altering [dbo].[GetSchemaVersion]...';

GO
-- Don't modify this file, it's used in the build process!
ALTER PROCEDURE [dbo].[GetSchemaVersion]
AS RETURN 3
GO
PRINT N'Invalidating [dbo].[MobileWorkItems]...';

GO
update MobileWorkItems SET Imei=Imei
GO
PRINT N'Invalidating [dbo].[IvrWorkItems]...';
GO
update IvrWorkItems SET GroupId=GroupId
GO
PRINT N'Invalidating [dbo].[ManualWorkItems]...';
GO
update ManualWorkItems SET GroupId=GroupId
GO
PRINT N'Invalidating [dbo].[AggregateWorkItemIntervals]...';
GO

MERGE [dbo].[AggregateDailyWorkTimes] WITH (HOLDLOCK) AS a
USING (
	SELECT DISTINCT UserId, CAST(StartDate as DATE) AS [Day] from AggregateWorkItemIntervals
	UNION
	SELECT DISTINCT UserId, CAST(EndDate as DATE) AS [Day] from AggregateWorkItemIntervals
	  ) AS i
   ON  i.[UserId] = a.[UserId] AND i.[Day] = a.[Day]
 WHEN NOT MATCHED THEN
		INSERT ([UserId], [Day]) VALUES (i.[UserId], i.[Day])
 WHEN MATCHED THEN
		UPDATE SET [IsValid] = 0;
GO