/*
Deployment script for recorder

This code was generated by a tool.
Changes to this file may cause incorrect behavior and will be lost if
the code is regenerated.
*/

GO
SET ANSI_NULLS, ANSI_PADDING, ANSI_WARNINGS, ARITHABORT, CONCAT_NULL_YIELDS_NULL, QUOTED_IDENTIFIER ON;

SET NUMERIC_ROUNDABORT OFF;


GO
/*
:setvar DatabaseName "recorder"
:setvar DefaultFilePrefix "recorder"
:setvar DefaultDataPath ""
:setvar DefaultLogPath ""
*/

GO
:on error exit
GO
/*
Detect SQLCMD mode and disable script execution if SQLCMD mode is not supported.
To re-enable the script after enabling SQLCMD mode, execute the following:
SET NOEXEC OFF; 
*/
:setvar __IsSqlCmdEnabled "True"
GO
IF N'$(__IsSqlCmdEnabled)' NOT LIKE N'True'
    BEGIN
        PRINT N'SQLCMD mode must be enabled to successfully execute this script.';
        SET NOEXEC ON;
    END


GO
USE [$(DatabaseName)];


GO
PRINT N'Altering [dbo].[GetSchemaVersion]...';


GO
-- Don't modify this file, it's used in the build process!
ALTER PROCEDURE [dbo].[GetSchemaVersion]
AS RETURN 54
GO
PRINT N'Altering [dbo].[InsertCollectedItems]...';


GO
ALTER PROCEDURE [dbo].[InsertCollectedItems]
(
	 @CollectedItems As [dbo].[CollectedItemsDataType] Readonly
	,@ReportServerAddress nvarchar(50) = null
)
AS
BEGIN
	SET NOCOUNT ON;
	SET XACT_ABORT ON

	BEGIN DISTRIBUTED TRANSACTION TestTran

	INSERT INTO [dbo].[CollectedItems]
			   ([UserId]
			   ,[CreateDate]
			   ,[ComputerId]
			   ,[KeyId]
			   ,[ValueId])
		 SELECT
			   [UserId]
			   ,[CreateDate]
			   ,[ComputerId]
			   ,[KeyId]
			   ,[ValueId]
		FROM
				@CollectedItems 

	IF @ReportServerAddress IS NOT NULL
	BEGIN
		DECLARE @script nvarchar(1000);
		CREATE TABLE #CollectedItems 
		(
			 UserId INT
			,CreateDate DATETIME
			,ComputerId INT
			,KeyId INT
			,ValueId INT
		)

		INSERT INTO #CollectedItems (UserId, CreateDate, ComputerId, KeyId, ValueId)
			SELECT UserId, CreateDate, ComputerId, KeyId, ValueId
			FROM @CollectedItems

		SET @script = N'INSERT INTO [' + @ReportServerAddress + N'].[jobcontrol].[dbo].[CollectedItems]
							([UserId]
							,[CreateDate]
							,[ComputerId]
							,[KeyId]
							,[ValueId])
						SELECT
							[UserId]
							,[CreateDate]
							,[ComputerId]
							,[KeyId]
							,[ValueId]
						FROM
							#CollectedItems';

		EXECUTE sp_executesql @script;
	  END

	  COMMIT TRAN
END
GO
PRINT N'Update complete.';


GO
