<?xml version="1.0" encoding="utf-8"?><Database Name="playback" Class="PlaybackClientDataClassesDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=.;Initial Catalog=playback;Integrated Security=True;Pooling=False" SettingsObjectName="PlaybackClient.Properties.Settings" SettingsPropertyName="playbackConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.PlaybackSchedules" Member="PlaybackSchedules">
    <Type Name="PlaybackSchedule">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="UserId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="StartDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="EndDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="FirstScheduleDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="LastScheduleDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="TimeZoneId" Type="System.String" DbType="VarChar(32)" CanBeNull="true" />
      <Column Name="ScheduleType" Type="System.Byte" DbType="TinyInt NOT NULL" CanBeNull="false" />
      <Column Name="Interval" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="WeeklyEffectiveDays" Type="System.Byte" DbType="TinyInt" CanBeNull="true" />
      <Column Name="FirstDayOfWeek" Type="System.Byte" DbType="TinyInt" CanBeNull="true" />
      <Column Name="MonthlyEffectiveDay" Type="System.Byte" DbType="TinyInt" CanBeNull="true" />
      <Column Name="CreateDate" AutoSync="Never" Type="System.DateTime" DbType="DateTime NOT NULL" IsDbGenerated="true" CanBeNull="false" />
    </Type>
  </Table>
</Database>