#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1008
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PlaybackClient
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="playback")]
	public partial class PlaybackClientDataClassesDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertPlaybackSchedule(PlaybackSchedule instance);
    partial void UpdatePlaybackSchedule(PlaybackSchedule instance);
    partial void DeletePlaybackSchedule(PlaybackSchedule instance);
    #endregion
		
		public PlaybackClientDataClassesDataContext() : 
				base(global::PlaybackClient.Properties.Settings.Default.playbackConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public PlaybackClientDataClassesDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public PlaybackClientDataClassesDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public PlaybackClientDataClassesDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public PlaybackClientDataClassesDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<PlaybackSchedule> PlaybackSchedules
		{
			get
			{
				return this.GetTable<PlaybackSchedule>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.PlaybackSchedules")]
	public partial class PlaybackSchedule : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id;
		
		private int _UserId;
		
		private System.DateTime _StartDate;
		
		private System.DateTime _EndDate;
		
		private System.DateTime _FirstScheduleDate;
		
		private System.Nullable<System.DateTime> _LastScheduleDate;
		
		private string _TimeZoneId;
		
		private byte _ScheduleType;
		
		private System.Nullable<int> _Interval;
		
		private System.Nullable<byte> _WeeklyEffectiveDays;
		
		private System.Nullable<byte> _FirstDayOfWeek;
		
		private System.Nullable<byte> _MonthlyEffectiveDay;
		
		private System.DateTime _CreateDate;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OnUserIdChanging(int value);
    partial void OnUserIdChanged();
    partial void OnStartDateChanging(System.DateTime value);
    partial void OnStartDateChanged();
    partial void OnEndDateChanging(System.DateTime value);
    partial void OnEndDateChanged();
    partial void OnFirstScheduleDateChanging(System.DateTime value);
    partial void OnFirstScheduleDateChanged();
    partial void OnLastScheduleDateChanging(System.Nullable<System.DateTime> value);
    partial void OnLastScheduleDateChanged();
    partial void OnTimeZoneIdChanging(string value);
    partial void OnTimeZoneIdChanged();
    partial void OnScheduleTypeChanging(byte value);
    partial void OnScheduleTypeChanged();
    partial void OnIntervalChanging(System.Nullable<int> value);
    partial void OnIntervalChanged();
    partial void OnWeeklyEffectiveDaysChanging(System.Nullable<byte> value);
    partial void OnWeeklyEffectiveDaysChanged();
    partial void OnFirstDayOfWeekChanging(System.Nullable<byte> value);
    partial void OnFirstDayOfWeekChanged();
    partial void OnMonthlyEffectiveDayChanging(System.Nullable<byte> value);
    partial void OnMonthlyEffectiveDayChanged();
    partial void OnCreateDateChanging(System.DateTime value);
    partial void OnCreateDateChanged();
    #endregion
		
		public PlaybackSchedule()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UserId", DbType="Int NOT NULL")]
		public int UserId
		{
			get
			{
				return this._UserId;
			}
			set
			{
				if ((this._UserId != value))
				{
					this.OnUserIdChanging(value);
					this.SendPropertyChanging();
					this._UserId = value;
					this.SendPropertyChanged("UserId");
					this.OnUserIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_StartDate", DbType="DateTime NOT NULL")]
		public System.DateTime StartDate
		{
			get
			{
				return this._StartDate;
			}
			set
			{
				if ((this._StartDate != value))
				{
					this.OnStartDateChanging(value);
					this.SendPropertyChanging();
					this._StartDate = value;
					this.SendPropertyChanged("StartDate");
					this.OnStartDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EndDate", DbType="DateTime NOT NULL")]
		public System.DateTime EndDate
		{
			get
			{
				return this._EndDate;
			}
			set
			{
				if ((this._EndDate != value))
				{
					this.OnEndDateChanging(value);
					this.SendPropertyChanging();
					this._EndDate = value;
					this.SendPropertyChanged("EndDate");
					this.OnEndDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FirstScheduleDate", DbType="DateTime NOT NULL")]
		public System.DateTime FirstScheduleDate
		{
			get
			{
				return this._FirstScheduleDate;
			}
			set
			{
				if ((this._FirstScheduleDate != value))
				{
					this.OnFirstScheduleDateChanging(value);
					this.SendPropertyChanging();
					this._FirstScheduleDate = value;
					this.SendPropertyChanged("FirstScheduleDate");
					this.OnFirstScheduleDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LastScheduleDate", DbType="DateTime")]
		public System.Nullable<System.DateTime> LastScheduleDate
		{
			get
			{
				return this._LastScheduleDate;
			}
			set
			{
				if ((this._LastScheduleDate != value))
				{
					this.OnLastScheduleDateChanging(value);
					this.SendPropertyChanging();
					this._LastScheduleDate = value;
					this.SendPropertyChanged("LastScheduleDate");
					this.OnLastScheduleDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TimeZoneId", DbType="VarChar(32)")]
		public string TimeZoneId
		{
			get
			{
				return this._TimeZoneId;
			}
			set
			{
				if ((this._TimeZoneId != value))
				{
					this.OnTimeZoneIdChanging(value);
					this.SendPropertyChanging();
					this._TimeZoneId = value;
					this.SendPropertyChanged("TimeZoneId");
					this.OnTimeZoneIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ScheduleType", DbType="TinyInt NOT NULL")]
		public byte ScheduleType
		{
			get
			{
				return this._ScheduleType;
			}
			set
			{
				if ((this._ScheduleType != value))
				{
					this.OnScheduleTypeChanging(value);
					this.SendPropertyChanging();
					this._ScheduleType = value;
					this.SendPropertyChanged("ScheduleType");
					this.OnScheduleTypeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Interval", DbType="Int")]
		public System.Nullable<int> Interval
		{
			get
			{
				return this._Interval;
			}
			set
			{
				if ((this._Interval != value))
				{
					this.OnIntervalChanging(value);
					this.SendPropertyChanging();
					this._Interval = value;
					this.SendPropertyChanged("Interval");
					this.OnIntervalChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_WeeklyEffectiveDays", DbType="TinyInt")]
		public System.Nullable<byte> WeeklyEffectiveDays
		{
			get
			{
				return this._WeeklyEffectiveDays;
			}
			set
			{
				if ((this._WeeklyEffectiveDays != value))
				{
					this.OnWeeklyEffectiveDaysChanging(value);
					this.SendPropertyChanging();
					this._WeeklyEffectiveDays = value;
					this.SendPropertyChanged("WeeklyEffectiveDays");
					this.OnWeeklyEffectiveDaysChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FirstDayOfWeek", DbType="TinyInt")]
		public System.Nullable<byte> FirstDayOfWeek
		{
			get
			{
				return this._FirstDayOfWeek;
			}
			set
			{
				if ((this._FirstDayOfWeek != value))
				{
					this.OnFirstDayOfWeekChanging(value);
					this.SendPropertyChanging();
					this._FirstDayOfWeek = value;
					this.SendPropertyChanged("FirstDayOfWeek");
					this.OnFirstDayOfWeekChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MonthlyEffectiveDay", DbType="TinyInt")]
		public System.Nullable<byte> MonthlyEffectiveDay
		{
			get
			{
				return this._MonthlyEffectiveDay;
			}
			set
			{
				if ((this._MonthlyEffectiveDay != value))
				{
					this.OnMonthlyEffectiveDayChanging(value);
					this.SendPropertyChanging();
					this._MonthlyEffectiveDay = value;
					this.SendPropertyChanged("MonthlyEffectiveDay");
					this.OnMonthlyEffectiveDayChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CreateDate", DbType="DateTime NOT NULL", IsDbGenerated=true)]
		public System.DateTime CreateDate
		{
			get
			{
				return this._CreateDate;
			}
			set
			{
				if ((this._CreateDate != value))
				{
					this.OnCreateDateChanging(value);
					this.SendPropertyChanging();
					this._CreateDate = value;
					this.SendPropertyChanged("CreateDate");
					this.OnCreateDateChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
