//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VoxCTRL.ActivityRecorderServiceReference {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AuthData", Namespace="http://schemas.datacontract.org/2004/07/Tct.ActivityRecorderService")]
    [System.SerializableAttribute()]
    public partial class AuthData : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Email {
            get {
                return this.EmailField;
            }
            set {
                if ((object.ReferenceEquals(this.EmailField, value) != true)) {
                    this.EmailField = value;
                    this.RaisePropertyChanged("Email");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="VoiceRecording", Namespace="http://schemas.datacontract.org/2004/07/Tct.ActivityRecorderService.Voice")]
    [System.SerializableAttribute()]
    public partial class VoiceRecording : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Guid ClientIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int UserIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> WorkIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime StartDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> EndDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int DurationField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CodecField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ExtensionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int OffsetField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private byte[] DataField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid ClientId {
            get {
                return this.ClientIdField;
            }
            set {
                if ((this.ClientIdField.Equals(value) != true)) {
                    this.ClientIdField = value;
                    this.RaisePropertyChanged("ClientId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int UserId {
            get {
                return this.UserIdField;
            }
            set {
                if ((this.UserIdField.Equals(value) != true)) {
                    this.UserIdField = value;
                    this.RaisePropertyChanged("UserId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> WorkId {
            get {
                return this.WorkIdField;
            }
            set {
                if ((this.WorkIdField.Equals(value) != true)) {
                    this.WorkIdField = value;
                    this.RaisePropertyChanged("WorkId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public System.DateTime StartDate {
            get {
                return this.StartDateField;
            }
            set {
                if ((this.StartDateField.Equals(value) != true)) {
                    this.StartDateField = value;
                    this.RaisePropertyChanged("StartDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public System.Nullable<System.DateTime> EndDate {
            get {
                return this.EndDateField;
            }
            set {
                if ((this.EndDateField.Equals(value) != true)) {
                    this.EndDateField = value;
                    this.RaisePropertyChanged("EndDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=5)]
        public int Duration {
            get {
                return this.DurationField;
            }
            set {
                if ((this.DurationField.Equals(value) != true)) {
                    this.DurationField = value;
                    this.RaisePropertyChanged("Duration");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=6)]
        public int Codec {
            get {
                return this.CodecField;
            }
            set {
                if ((this.CodecField.Equals(value) != true)) {
                    this.CodecField = value;
                    this.RaisePropertyChanged("Codec");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=7)]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=8)]
        public string Extension {
            get {
                return this.ExtensionField;
            }
            set {
                if ((object.ReferenceEquals(this.ExtensionField, value) != true)) {
                    this.ExtensionField = value;
                    this.RaisePropertyChanged("Extension");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=9)]
        public int Offset {
            get {
                return this.OffsetField;
            }
            set {
                if ((this.OffsetField.Equals(value) != true)) {
                    this.OffsetField = value;
                    this.RaisePropertyChanged("Offset");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=10)]
        public byte[] Data {
            get {
                return this.DataField;
            }
            set {
                if ((object.ReferenceEquals(this.DataField, value) != true)) {
                    this.DataField = value;
                    this.RaisePropertyChanged("Data");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DownloadSessionInfo", Namespace="http://schemas.datacontract.org/2004/07/Tct.ActivityRecorderService")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(VoxCTRL.ActivityRecorderServiceReference.ApplicationUpdateInfo))]
    public partial class DownloadSessionInfo : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long ChunkCountField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Guid FileIdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long ChunkCount {
            get {
                return this.ChunkCountField;
            }
            set {
                if ((this.ChunkCountField.Equals(value) != true)) {
                    this.ChunkCountField = value;
                    this.RaisePropertyChanged("ChunkCount");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid FileId {
            get {
                return this.FileIdField;
            }
            set {
                if ((this.FileIdField.Equals(value) != true)) {
                    this.FileIdField = value;
                    this.RaisePropertyChanged("FileId");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ApplicationUpdateInfo", Namespace="http://schemas.datacontract.org/2004/07/Tct.ActivityRecorderService")]
    [System.SerializableAttribute()]
    public partial class ApplicationUpdateInfo : VoxCTRL.ActivityRecorderServiceReference.DownloadSessionInfo {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string VersionField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Version {
            get {
                return this.VersionField;
            }
            set {
                if ((object.ReferenceEquals(this.VersionField, value) != true)) {
                    this.VersionField = value;
                    this.RaisePropertyChanged("Version");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ClientSetting", Namespace="http://schemas.datacontract.org/2004/07/Tct.ActivityRecorderService")]
    [System.SerializableAttribute()]
    public partial class ClientSetting : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> MenuUpdateIntervalField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> CaptureWorkItemIntervalField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> CaptureActiveWindowIntervalField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> CaptureScreenShotIntervalField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> TimeSyncThresholdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> JpegQualityField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> JpegScalePctField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> WorkTimeStartInMinsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> WorkTimeEndInMinsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> AfterWorkTimeIdleInMinsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> MaxOfflineWorkItemsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> DuringWorkTimeIdleInMinsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> DuringWorkTimeIdleManualIntervalField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> MaxManualMeetingIntervalField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> RuleRestrictionsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<bool> IsMeetingTrackingEnabledField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<bool> IsMeetingSubjectMandatoryField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> BusyTimeThresholdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<bool> CoincidentalClientsEnabledField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<bool> IsManualMeetingStartsOnLockField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<bool> IsLotusNotesMeetingTrackingEnabledField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> RuleMatchingIntervalField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<bool> IsOutlookAddinRequiredField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<bool> IsOutlookAddinMailTrackingIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> DefaultWorkIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> CaptureDeadlockInMinsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> MouseMovingThresholdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EnabledFeatureField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> PluginFailThresholdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> CollectedItemAggregateInMinsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<bool> ForceCountdownRulesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MsProjectAddressField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> ManualWorkItemEditAgeLimitField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<bool> AutoReturnFromMeetingField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<bool> IsOutlookAddinMailTrackingUseSubjectField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> TelemetryMaxCountField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> TelemetryMaxAgeInMinsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TelemetryCollectedKeysField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<bool> IsMeetingUploadModificationsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<bool> IsMeetingTentativeSyncedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<bool> IsInjectedInputAllowedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> DataCollectionSettingsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> IsNotificationShownField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsTodoListEnabledField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> MailTrackingSettingsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> DiagnosticOperationModeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<bool> IsGoogleCalendarTrackingEnabledField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<bool> IsAnonymModeEnabledField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<bool> VoxIsNameMandatoryField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> VoxQualityField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<bool> VoxIsManualStartStopEnabledField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> MenuUpdateInterval {
            get {
                return this.MenuUpdateIntervalField;
            }
            set {
                if ((this.MenuUpdateIntervalField.Equals(value) != true)) {
                    this.MenuUpdateIntervalField = value;
                    this.RaisePropertyChanged("MenuUpdateInterval");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public System.Nullable<int> CaptureWorkItemInterval {
            get {
                return this.CaptureWorkItemIntervalField;
            }
            set {
                if ((this.CaptureWorkItemIntervalField.Equals(value) != true)) {
                    this.CaptureWorkItemIntervalField = value;
                    this.RaisePropertyChanged("CaptureWorkItemInterval");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public System.Nullable<int> CaptureActiveWindowInterval {
            get {
                return this.CaptureActiveWindowIntervalField;
            }
            set {
                if ((this.CaptureActiveWindowIntervalField.Equals(value) != true)) {
                    this.CaptureActiveWindowIntervalField = value;
                    this.RaisePropertyChanged("CaptureActiveWindowInterval");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public System.Nullable<int> CaptureScreenShotInterval {
            get {
                return this.CaptureScreenShotIntervalField;
            }
            set {
                if ((this.CaptureScreenShotIntervalField.Equals(value) != true)) {
                    this.CaptureScreenShotIntervalField = value;
                    this.RaisePropertyChanged("CaptureScreenShotInterval");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public System.Nullable<int> TimeSyncThreshold {
            get {
                return this.TimeSyncThresholdField;
            }
            set {
                if ((this.TimeSyncThresholdField.Equals(value) != true)) {
                    this.TimeSyncThresholdField = value;
                    this.RaisePropertyChanged("TimeSyncThreshold");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=5)]
        public System.Nullable<int> JpegQuality {
            get {
                return this.JpegQualityField;
            }
            set {
                if ((this.JpegQualityField.Equals(value) != true)) {
                    this.JpegQualityField = value;
                    this.RaisePropertyChanged("JpegQuality");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=6)]
        public System.Nullable<int> JpegScalePct {
            get {
                return this.JpegScalePctField;
            }
            set {
                if ((this.JpegScalePctField.Equals(value) != true)) {
                    this.JpegScalePctField = value;
                    this.RaisePropertyChanged("JpegScalePct");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=7)]
        public System.Nullable<int> WorkTimeStartInMins {
            get {
                return this.WorkTimeStartInMinsField;
            }
            set {
                if ((this.WorkTimeStartInMinsField.Equals(value) != true)) {
                    this.WorkTimeStartInMinsField = value;
                    this.RaisePropertyChanged("WorkTimeStartInMins");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=8)]
        public System.Nullable<int> WorkTimeEndInMins {
            get {
                return this.WorkTimeEndInMinsField;
            }
            set {
                if ((this.WorkTimeEndInMinsField.Equals(value) != true)) {
                    this.WorkTimeEndInMinsField = value;
                    this.RaisePropertyChanged("WorkTimeEndInMins");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=9)]
        public System.Nullable<int> AfterWorkTimeIdleInMins {
            get {
                return this.AfterWorkTimeIdleInMinsField;
            }
            set {
                if ((this.AfterWorkTimeIdleInMinsField.Equals(value) != true)) {
                    this.AfterWorkTimeIdleInMinsField = value;
                    this.RaisePropertyChanged("AfterWorkTimeIdleInMins");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=10)]
        public System.Nullable<int> MaxOfflineWorkItems {
            get {
                return this.MaxOfflineWorkItemsField;
            }
            set {
                if ((this.MaxOfflineWorkItemsField.Equals(value) != true)) {
                    this.MaxOfflineWorkItemsField = value;
                    this.RaisePropertyChanged("MaxOfflineWorkItems");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=11)]
        public System.Nullable<int> DuringWorkTimeIdleInMins {
            get {
                return this.DuringWorkTimeIdleInMinsField;
            }
            set {
                if ((this.DuringWorkTimeIdleInMinsField.Equals(value) != true)) {
                    this.DuringWorkTimeIdleInMinsField = value;
                    this.RaisePropertyChanged("DuringWorkTimeIdleInMins");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=12)]
        public System.Nullable<int> DuringWorkTimeIdleManualInterval {
            get {
                return this.DuringWorkTimeIdleManualIntervalField;
            }
            set {
                if ((this.DuringWorkTimeIdleManualIntervalField.Equals(value) != true)) {
                    this.DuringWorkTimeIdleManualIntervalField = value;
                    this.RaisePropertyChanged("DuringWorkTimeIdleManualInterval");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=13)]
        public System.Nullable<int> MaxManualMeetingInterval {
            get {
                return this.MaxManualMeetingIntervalField;
            }
            set {
                if ((this.MaxManualMeetingIntervalField.Equals(value) != true)) {
                    this.MaxManualMeetingIntervalField = value;
                    this.RaisePropertyChanged("MaxManualMeetingInterval");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=14)]
        public System.Nullable<int> RuleRestrictions {
            get {
                return this.RuleRestrictionsField;
            }
            set {
                if ((this.RuleRestrictionsField.Equals(value) != true)) {
                    this.RuleRestrictionsField = value;
                    this.RaisePropertyChanged("RuleRestrictions");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=15)]
        public System.Nullable<bool> IsMeetingTrackingEnabled {
            get {
                return this.IsMeetingTrackingEnabledField;
            }
            set {
                if ((this.IsMeetingTrackingEnabledField.Equals(value) != true)) {
                    this.IsMeetingTrackingEnabledField = value;
                    this.RaisePropertyChanged("IsMeetingTrackingEnabled");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=16)]
        public System.Nullable<bool> IsMeetingSubjectMandatory {
            get {
                return this.IsMeetingSubjectMandatoryField;
            }
            set {
                if ((this.IsMeetingSubjectMandatoryField.Equals(value) != true)) {
                    this.IsMeetingSubjectMandatoryField = value;
                    this.RaisePropertyChanged("IsMeetingSubjectMandatory");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=17)]
        public System.Nullable<int> BusyTimeThreshold {
            get {
                return this.BusyTimeThresholdField;
            }
            set {
                if ((this.BusyTimeThresholdField.Equals(value) != true)) {
                    this.BusyTimeThresholdField = value;
                    this.RaisePropertyChanged("BusyTimeThreshold");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=18)]
        public System.Nullable<bool> CoincidentalClientsEnabled {
            get {
                return this.CoincidentalClientsEnabledField;
            }
            set {
                if ((this.CoincidentalClientsEnabledField.Equals(value) != true)) {
                    this.CoincidentalClientsEnabledField = value;
                    this.RaisePropertyChanged("CoincidentalClientsEnabled");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=19)]
        public System.Nullable<bool> IsManualMeetingStartsOnLock {
            get {
                return this.IsManualMeetingStartsOnLockField;
            }
            set {
                if ((this.IsManualMeetingStartsOnLockField.Equals(value) != true)) {
                    this.IsManualMeetingStartsOnLockField = value;
                    this.RaisePropertyChanged("IsManualMeetingStartsOnLock");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=20)]
        public System.Nullable<bool> IsLotusNotesMeetingTrackingEnabled {
            get {
                return this.IsLotusNotesMeetingTrackingEnabledField;
            }
            set {
                if ((this.IsLotusNotesMeetingTrackingEnabledField.Equals(value) != true)) {
                    this.IsLotusNotesMeetingTrackingEnabledField = value;
                    this.RaisePropertyChanged("IsLotusNotesMeetingTrackingEnabled");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=21)]
        public System.Nullable<int> RuleMatchingInterval {
            get {
                return this.RuleMatchingIntervalField;
            }
            set {
                if ((this.RuleMatchingIntervalField.Equals(value) != true)) {
                    this.RuleMatchingIntervalField = value;
                    this.RaisePropertyChanged("RuleMatchingInterval");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=22)]
        public System.Nullable<bool> IsOutlookAddinRequired {
            get {
                return this.IsOutlookAddinRequiredField;
            }
            set {
                if ((this.IsOutlookAddinRequiredField.Equals(value) != true)) {
                    this.IsOutlookAddinRequiredField = value;
                    this.RaisePropertyChanged("IsOutlookAddinRequired");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=23)]
        public System.Nullable<bool> IsOutlookAddinMailTrackingId {
            get {
                return this.IsOutlookAddinMailTrackingIdField;
            }
            set {
                if ((this.IsOutlookAddinMailTrackingIdField.Equals(value) != true)) {
                    this.IsOutlookAddinMailTrackingIdField = value;
                    this.RaisePropertyChanged("IsOutlookAddinMailTrackingId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=24)]
        public System.Nullable<int> DefaultWorkId {
            get {
                return this.DefaultWorkIdField;
            }
            set {
                if ((this.DefaultWorkIdField.Equals(value) != true)) {
                    this.DefaultWorkIdField = value;
                    this.RaisePropertyChanged("DefaultWorkId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=25)]
        public System.Nullable<int> CaptureDeadlockInMins {
            get {
                return this.CaptureDeadlockInMinsField;
            }
            set {
                if ((this.CaptureDeadlockInMinsField.Equals(value) != true)) {
                    this.CaptureDeadlockInMinsField = value;
                    this.RaisePropertyChanged("CaptureDeadlockInMins");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=26)]
        public System.Nullable<int> MouseMovingThreshold {
            get {
                return this.MouseMovingThresholdField;
            }
            set {
                if ((this.MouseMovingThresholdField.Equals(value) != true)) {
                    this.MouseMovingThresholdField = value;
                    this.RaisePropertyChanged("MouseMovingThreshold");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=27)]
        public string EnabledFeature {
            get {
                return this.EnabledFeatureField;
            }
            set {
                if ((object.ReferenceEquals(this.EnabledFeatureField, value) != true)) {
                    this.EnabledFeatureField = value;
                    this.RaisePropertyChanged("EnabledFeature");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=28)]
        public System.Nullable<int> PluginFailThreshold {
            get {
                return this.PluginFailThresholdField;
            }
            set {
                if ((this.PluginFailThresholdField.Equals(value) != true)) {
                    this.PluginFailThresholdField = value;
                    this.RaisePropertyChanged("PluginFailThreshold");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=29)]
        public System.Nullable<int> CollectedItemAggregateInMins {
            get {
                return this.CollectedItemAggregateInMinsField;
            }
            set {
                if ((this.CollectedItemAggregateInMinsField.Equals(value) != true)) {
                    this.CollectedItemAggregateInMinsField = value;
                    this.RaisePropertyChanged("CollectedItemAggregateInMins");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=30)]
        public System.Nullable<bool> ForceCountdownRules {
            get {
                return this.ForceCountdownRulesField;
            }
            set {
                if ((this.ForceCountdownRulesField.Equals(value) != true)) {
                    this.ForceCountdownRulesField = value;
                    this.RaisePropertyChanged("ForceCountdownRules");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=31)]
        public string MsProjectAddress {
            get {
                return this.MsProjectAddressField;
            }
            set {
                if ((object.ReferenceEquals(this.MsProjectAddressField, value) != true)) {
                    this.MsProjectAddressField = value;
                    this.RaisePropertyChanged("MsProjectAddress");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=32)]
        public System.Nullable<int> ManualWorkItemEditAgeLimit {
            get {
                return this.ManualWorkItemEditAgeLimitField;
            }
            set {
                if ((this.ManualWorkItemEditAgeLimitField.Equals(value) != true)) {
                    this.ManualWorkItemEditAgeLimitField = value;
                    this.RaisePropertyChanged("ManualWorkItemEditAgeLimit");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=33)]
        public System.Nullable<bool> AutoReturnFromMeeting {
            get {
                return this.AutoReturnFromMeetingField;
            }
            set {
                if ((this.AutoReturnFromMeetingField.Equals(value) != true)) {
                    this.AutoReturnFromMeetingField = value;
                    this.RaisePropertyChanged("AutoReturnFromMeeting");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=34)]
        public System.Nullable<bool> IsOutlookAddinMailTrackingUseSubject {
            get {
                return this.IsOutlookAddinMailTrackingUseSubjectField;
            }
            set {
                if ((this.IsOutlookAddinMailTrackingUseSubjectField.Equals(value) != true)) {
                    this.IsOutlookAddinMailTrackingUseSubjectField = value;
                    this.RaisePropertyChanged("IsOutlookAddinMailTrackingUseSubject");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=35)]
        public System.Nullable<int> TelemetryMaxCount {
            get {
                return this.TelemetryMaxCountField;
            }
            set {
                if ((this.TelemetryMaxCountField.Equals(value) != true)) {
                    this.TelemetryMaxCountField = value;
                    this.RaisePropertyChanged("TelemetryMaxCount");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=36)]
        public System.Nullable<int> TelemetryMaxAgeInMins {
            get {
                return this.TelemetryMaxAgeInMinsField;
            }
            set {
                if ((this.TelemetryMaxAgeInMinsField.Equals(value) != true)) {
                    this.TelemetryMaxAgeInMinsField = value;
                    this.RaisePropertyChanged("TelemetryMaxAgeInMins");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=37)]
        public string TelemetryCollectedKeys {
            get {
                return this.TelemetryCollectedKeysField;
            }
            set {
                if ((object.ReferenceEquals(this.TelemetryCollectedKeysField, value) != true)) {
                    this.TelemetryCollectedKeysField = value;
                    this.RaisePropertyChanged("TelemetryCollectedKeys");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=38)]
        public System.Nullable<bool> IsMeetingUploadModifications {
            get {
                return this.IsMeetingUploadModificationsField;
            }
            set {
                if ((this.IsMeetingUploadModificationsField.Equals(value) != true)) {
                    this.IsMeetingUploadModificationsField = value;
                    this.RaisePropertyChanged("IsMeetingUploadModifications");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=39)]
        public System.Nullable<bool> IsMeetingTentativeSynced {
            get {
                return this.IsMeetingTentativeSyncedField;
            }
            set {
                if ((this.IsMeetingTentativeSyncedField.Equals(value) != true)) {
                    this.IsMeetingTentativeSyncedField = value;
                    this.RaisePropertyChanged("IsMeetingTentativeSynced");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=40)]
        public System.Nullable<bool> IsInjectedInputAllowed {
            get {
                return this.IsInjectedInputAllowedField;
            }
            set {
                if ((this.IsInjectedInputAllowedField.Equals(value) != true)) {
                    this.IsInjectedInputAllowedField = value;
                    this.RaisePropertyChanged("IsInjectedInputAllowed");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=41)]
        public System.Nullable<int> DataCollectionSettings {
            get {
                return this.DataCollectionSettingsField;
            }
            set {
                if ((this.DataCollectionSettingsField.Equals(value) != true)) {
                    this.DataCollectionSettingsField = value;
                    this.RaisePropertyChanged("DataCollectionSettings");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=42)]
        public System.Nullable<int> IsNotificationShown {
            get {
                return this.IsNotificationShownField;
            }
            set {
                if ((this.IsNotificationShownField.Equals(value) != true)) {
                    this.IsNotificationShownField = value;
                    this.RaisePropertyChanged("IsNotificationShown");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=43)]
        public bool IsTodoListEnabled {
            get {
                return this.IsTodoListEnabledField;
            }
            set {
                if ((this.IsTodoListEnabledField.Equals(value) != true)) {
                    this.IsTodoListEnabledField = value;
                    this.RaisePropertyChanged("IsTodoListEnabled");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=44)]
        public System.Nullable<int> MailTrackingSettings {
            get {
                return this.MailTrackingSettingsField;
            }
            set {
                if ((this.MailTrackingSettingsField.Equals(value) != true)) {
                    this.MailTrackingSettingsField = value;
                    this.RaisePropertyChanged("MailTrackingSettings");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=45)]
        public System.Nullable<int> DiagnosticOperationMode {
            get {
                return this.DiagnosticOperationModeField;
            }
            set {
                if ((this.DiagnosticOperationModeField.Equals(value) != true)) {
                    this.DiagnosticOperationModeField = value;
                    this.RaisePropertyChanged("DiagnosticOperationMode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=46)]
        public System.Nullable<bool> IsGoogleCalendarTrackingEnabled {
            get {
                return this.IsGoogleCalendarTrackingEnabledField;
            }
            set {
                if ((this.IsGoogleCalendarTrackingEnabledField.Equals(value) != true)) {
                    this.IsGoogleCalendarTrackingEnabledField = value;
                    this.RaisePropertyChanged("IsGoogleCalendarTrackingEnabled");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=47)]
        public System.Nullable<bool> IsAnonymModeEnabled {
            get {
                return this.IsAnonymModeEnabledField;
            }
            set {
                if ((this.IsAnonymModeEnabledField.Equals(value) != true)) {
                    this.IsAnonymModeEnabledField = value;
                    this.RaisePropertyChanged("IsAnonymModeEnabled");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=48)]
        public System.Nullable<bool> VoxIsNameMandatory {
            get {
                return this.VoxIsNameMandatoryField;
            }
            set {
                if ((this.VoxIsNameMandatoryField.Equals(value) != true)) {
                    this.VoxIsNameMandatoryField = value;
                    this.RaisePropertyChanged("VoxIsNameMandatory");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=49)]
        public System.Nullable<int> VoxQuality {
            get {
                return this.VoxQualityField;
            }
            set {
                if ((this.VoxQualityField.Equals(value) != true)) {
                    this.VoxQualityField = value;
                    this.RaisePropertyChanged("VoxQuality");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=50)]
        public System.Nullable<bool> VoxIsManualStartStopEnabled {
            get {
                return this.VoxIsManualStartStopEnabledField;
            }
            set {
                if ((this.VoxIsManualStartStopEnabledField.Equals(value) != true)) {
                    this.VoxIsManualStartStopEnabledField = value;
                    this.RaisePropertyChanged("VoxIsManualStartStopEnabled");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ClientLoginTicket", Namespace="http://jobctrl.com/Authentication")]
    [System.SerializableAttribute()]
    public partial class ClientLoginTicket : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime ExpirationDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TicketField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int UserIdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime ExpirationDate {
            get {
                return this.ExpirationDateField;
            }
            set {
                if ((this.ExpirationDateField.Equals(value) != true)) {
                    this.ExpirationDateField = value;
                    this.RaisePropertyChanged("ExpirationDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Ticket {
            get {
                return this.TicketField;
            }
            set {
                if ((object.ReferenceEquals(this.TicketField, value) != true)) {
                    this.TicketField = value;
                    this.RaisePropertyChanged("Ticket");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int UserId {
            get {
                return this.UserIdField;
            }
            set {
                if ((this.UserIdField.Equals(value) != true)) {
                    this.UserIdField = value;
                    this.RaisePropertyChanged("UserId");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="Tct.ActivityRecorderService.IVoiceRecorder", ConfigurationName="ActivityRecorderServiceReference.IVoiceRecorder")]
    public interface IVoiceRecorder {
        
        [System.ServiceModel.OperationContractAttribute(Action="Tct.ActivityRecorderService.IVoiceRecorder/IVoiceRecorder/Authenticate", ReplyAction="Tct.ActivityRecorderService.IVoiceRecorder/IVoiceRecorder/AuthenticateResponse")]
        VoxCTRL.ActivityRecorderServiceReference.AuthData Authenticate(string clientInfo);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="Tct.ActivityRecorderService.IVoiceRecorder/IVoiceRecorder/Authenticate", ReplyAction="Tct.ActivityRecorderService.IVoiceRecorder/IVoiceRecorder/AuthenticateResponse")]
        System.IAsyncResult BeginAuthenticate(string clientInfo, System.AsyncCallback callback, object asyncState);
        
        VoxCTRL.ActivityRecorderServiceReference.AuthData EndAuthenticate(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(Action="Tct.ActivityRecorderService.IVoiceRecorder/IVoiceRecorder/UpsertVoiceRecording", ReplyAction="Tct.ActivityRecorderService.IVoiceRecorder/IVoiceRecorder/UpsertVoiceRecordingRes" +
            "ponse")]
        void UpsertVoiceRecording(VoxCTRL.ActivityRecorderServiceReference.VoiceRecording voiceRecording);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="Tct.ActivityRecorderService.IVoiceRecorder/IVoiceRecorder/UpsertVoiceRecording", ReplyAction="Tct.ActivityRecorderService.IVoiceRecorder/IVoiceRecorder/UpsertVoiceRecordingRes" +
            "ponse")]
        System.IAsyncResult BeginUpsertVoiceRecording(VoxCTRL.ActivityRecorderServiceReference.VoiceRecording voiceRecording, System.AsyncCallback callback, object asyncState);
        
        void EndUpsertVoiceRecording(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(Action="Tct.ActivityRecorderService.IVoiceRecorder/IVoiceRecorder/DeleteVoiceRecording", ReplyAction="Tct.ActivityRecorderService.IVoiceRecorder/IVoiceRecorder/DeleteVoiceRecordingRes" +
            "ponse")]
        void DeleteVoiceRecording(VoxCTRL.ActivityRecorderServiceReference.VoiceRecording voiceRecording);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="Tct.ActivityRecorderService.IVoiceRecorder/IVoiceRecorder/DeleteVoiceRecording", ReplyAction="Tct.ActivityRecorderService.IVoiceRecorder/IVoiceRecorder/DeleteVoiceRecordingRes" +
            "ponse")]
        System.IAsyncResult BeginDeleteVoiceRecording(VoxCTRL.ActivityRecorderServiceReference.VoiceRecording voiceRecording, System.AsyncCallback callback, object asyncState);
        
        void EndDeleteVoiceRecording(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(Action="Tct.ActivityRecorderService.IVoiceRecorder/IVoiceRecorder/GetApplicationUpdate", ReplyAction="Tct.ActivityRecorderService.IVoiceRecorder/IVoiceRecorder/GetApplicationUpdateRes" +
            "ponse")]
        VoxCTRL.ActivityRecorderServiceReference.ApplicationUpdateInfo GetApplicationUpdate(int userId, string application, string currentVersion);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="Tct.ActivityRecorderService.IVoiceRecorder/IVoiceRecorder/GetApplicationUpdate", ReplyAction="Tct.ActivityRecorderService.IVoiceRecorder/IVoiceRecorder/GetApplicationUpdateRes" +
            "ponse")]
        System.IAsyncResult BeginGetApplicationUpdate(int userId, string application, string currentVersion, System.AsyncCallback callback, object asyncState);
        
        VoxCTRL.ActivityRecorderServiceReference.ApplicationUpdateInfo EndGetApplicationUpdate(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(Action="Tct.ActivityRecorderService.IVoiceRecorder/IVoiceRecorder/GetUpdateChunk", ReplyAction="Tct.ActivityRecorderService.IVoiceRecorder/IVoiceRecorder/GetUpdateChunkResponse")]
        byte[] GetUpdateChunk(System.Guid fileId, long chunkIndex);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="Tct.ActivityRecorderService.IVoiceRecorder/IVoiceRecorder/GetUpdateChunk", ReplyAction="Tct.ActivityRecorderService.IVoiceRecorder/IVoiceRecorder/GetUpdateChunkResponse")]
        System.IAsyncResult BeginGetUpdateChunk(System.Guid fileId, long chunkIndex, System.AsyncCallback callback, object asyncState);
        
        byte[] EndGetUpdateChunk(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(Action="Tct.ActivityRecorderService.IVoiceRecorder/IVoiceRecorder/GetClientSettings", ReplyAction="Tct.ActivityRecorderService.IVoiceRecorder/IVoiceRecorder/GetClientSettingsRespon" +
            "se")]
        VoxCTRL.ActivityRecorderServiceReference.ClientSetting GetClientSettings(out string newVersion, int userId, string oldVersion);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="Tct.ActivityRecorderService.IVoiceRecorder/IVoiceRecorder/GetClientSettings", ReplyAction="Tct.ActivityRecorderService.IVoiceRecorder/IVoiceRecorder/GetClientSettingsRespon" +
            "se")]
        System.IAsyncResult BeginGetClientSettings(int userId, string oldVersion, System.AsyncCallback callback, object asyncState);
        
        VoxCTRL.ActivityRecorderServiceReference.ClientSetting EndGetClientSettings(out string newVersion, System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(Action="Tct.ActivityRecorderService.IVoiceRecorder/IVoiceRecorder/ReportClientVersion", ReplyAction="Tct.ActivityRecorderService.IVoiceRecorder/IVoiceRecorder/ReportClientVersionResp" +
            "onse")]
        void ReportClientVersion(int userId, int computerId, int major, int minor, int build, int revision, string application);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="Tct.ActivityRecorderService.IVoiceRecorder/IVoiceRecorder/ReportClientVersion", ReplyAction="Tct.ActivityRecorderService.IVoiceRecorder/IVoiceRecorder/ReportClientVersionResp" +
            "onse")]
        System.IAsyncResult BeginReportClientVersion(int userId, int computerId, int major, int minor, int build, int revision, string application, System.AsyncCallback callback, object asyncState);
        
        void EndReportClientVersion(System.IAsyncResult result);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IVoiceRecorderChannel : VoxCTRL.ActivityRecorderServiceReference.IVoiceRecorder, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class AuthenticateCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public AuthenticateCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public VoxCTRL.ActivityRecorderServiceReference.AuthData Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((VoxCTRL.ActivityRecorderServiceReference.AuthData)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GetApplicationUpdateCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public GetApplicationUpdateCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public VoxCTRL.ActivityRecorderServiceReference.ApplicationUpdateInfo Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((VoxCTRL.ActivityRecorderServiceReference.ApplicationUpdateInfo)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GetUpdateChunkCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public GetUpdateChunkCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public byte[] Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((byte[])(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GetClientSettingsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public GetClientSettingsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public string newVersion {
            get {
                base.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
        
        public VoxCTRL.ActivityRecorderServiceReference.ClientSetting Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((VoxCTRL.ActivityRecorderServiceReference.ClientSetting)(this.results[1]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class VoiceRecorderClient : System.ServiceModel.ClientBase<VoxCTRL.ActivityRecorderServiceReference.IVoiceRecorder>, VoxCTRL.ActivityRecorderServiceReference.IVoiceRecorder {
        
        private BeginOperationDelegate onBeginAuthenticateDelegate;
        
        private EndOperationDelegate onEndAuthenticateDelegate;
        
        private System.Threading.SendOrPostCallback onAuthenticateCompletedDelegate;
        
        private BeginOperationDelegate onBeginUpsertVoiceRecordingDelegate;
        
        private EndOperationDelegate onEndUpsertVoiceRecordingDelegate;
        
        private System.Threading.SendOrPostCallback onUpsertVoiceRecordingCompletedDelegate;
        
        private BeginOperationDelegate onBeginDeleteVoiceRecordingDelegate;
        
        private EndOperationDelegate onEndDeleteVoiceRecordingDelegate;
        
        private System.Threading.SendOrPostCallback onDeleteVoiceRecordingCompletedDelegate;
        
        private BeginOperationDelegate onBeginGetApplicationUpdateDelegate;
        
        private EndOperationDelegate onEndGetApplicationUpdateDelegate;
        
        private System.Threading.SendOrPostCallback onGetApplicationUpdateCompletedDelegate;
        
        private BeginOperationDelegate onBeginGetUpdateChunkDelegate;
        
        private EndOperationDelegate onEndGetUpdateChunkDelegate;
        
        private System.Threading.SendOrPostCallback onGetUpdateChunkCompletedDelegate;
        
        private BeginOperationDelegate onBeginGetClientSettingsDelegate;
        
        private EndOperationDelegate onEndGetClientSettingsDelegate;
        
        private System.Threading.SendOrPostCallback onGetClientSettingsCompletedDelegate;
        
        private BeginOperationDelegate onBeginReportClientVersionDelegate;
        
        private EndOperationDelegate onEndReportClientVersionDelegate;
        
        private System.Threading.SendOrPostCallback onReportClientVersionCompletedDelegate;
        
        public VoiceRecorderClient() {
        }
        
        public VoiceRecorderClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public VoiceRecorderClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public VoiceRecorderClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public VoiceRecorderClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public event System.EventHandler<AuthenticateCompletedEventArgs> AuthenticateCompleted;
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> UpsertVoiceRecordingCompleted;
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> DeleteVoiceRecordingCompleted;
        
        public event System.EventHandler<GetApplicationUpdateCompletedEventArgs> GetApplicationUpdateCompleted;
        
        public event System.EventHandler<GetUpdateChunkCompletedEventArgs> GetUpdateChunkCompleted;
        
        public event System.EventHandler<GetClientSettingsCompletedEventArgs> GetClientSettingsCompleted;
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> ReportClientVersionCompleted;
        
        public VoxCTRL.ActivityRecorderServiceReference.AuthData Authenticate(string clientInfo) {
            return base.Channel.Authenticate(clientInfo);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public System.IAsyncResult BeginAuthenticate(string clientInfo, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginAuthenticate(clientInfo, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public VoxCTRL.ActivityRecorderServiceReference.AuthData EndAuthenticate(System.IAsyncResult result) {
            return base.Channel.EndAuthenticate(result);
        }
        
        private System.IAsyncResult OnBeginAuthenticate(object[] inValues, System.AsyncCallback callback, object asyncState) {
            string clientInfo = ((string)(inValues[0]));
            return this.BeginAuthenticate(clientInfo, callback, asyncState);
        }
        
        private object[] OnEndAuthenticate(System.IAsyncResult result) {
            VoxCTRL.ActivityRecorderServiceReference.AuthData retVal = this.EndAuthenticate(result);
            return new object[] {
                    retVal};
        }
        
        private void OnAuthenticateCompleted(object state) {
            if ((this.AuthenticateCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.AuthenticateCompleted(this, new AuthenticateCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void AuthenticateAsync(string clientInfo) {
            this.AuthenticateAsync(clientInfo, null);
        }
        
        public void AuthenticateAsync(string clientInfo, object userState) {
            if ((this.onBeginAuthenticateDelegate == null)) {
                this.onBeginAuthenticateDelegate = new BeginOperationDelegate(this.OnBeginAuthenticate);
            }
            if ((this.onEndAuthenticateDelegate == null)) {
                this.onEndAuthenticateDelegate = new EndOperationDelegate(this.OnEndAuthenticate);
            }
            if ((this.onAuthenticateCompletedDelegate == null)) {
                this.onAuthenticateCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnAuthenticateCompleted);
            }
            base.InvokeAsync(this.onBeginAuthenticateDelegate, new object[] {
                        clientInfo}, this.onEndAuthenticateDelegate, this.onAuthenticateCompletedDelegate, userState);
        }
        
        public void UpsertVoiceRecording(VoxCTRL.ActivityRecorderServiceReference.VoiceRecording voiceRecording) {
            base.Channel.UpsertVoiceRecording(voiceRecording);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public System.IAsyncResult BeginUpsertVoiceRecording(VoxCTRL.ActivityRecorderServiceReference.VoiceRecording voiceRecording, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginUpsertVoiceRecording(voiceRecording, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public void EndUpsertVoiceRecording(System.IAsyncResult result) {
            base.Channel.EndUpsertVoiceRecording(result);
        }
        
        private System.IAsyncResult OnBeginUpsertVoiceRecording(object[] inValues, System.AsyncCallback callback, object asyncState) {
            VoxCTRL.ActivityRecorderServiceReference.VoiceRecording voiceRecording = ((VoxCTRL.ActivityRecorderServiceReference.VoiceRecording)(inValues[0]));
            return this.BeginUpsertVoiceRecording(voiceRecording, callback, asyncState);
        }
        
        private object[] OnEndUpsertVoiceRecording(System.IAsyncResult result) {
            this.EndUpsertVoiceRecording(result);
            return null;
        }
        
        private void OnUpsertVoiceRecordingCompleted(object state) {
            if ((this.UpsertVoiceRecordingCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.UpsertVoiceRecordingCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void UpsertVoiceRecordingAsync(VoxCTRL.ActivityRecorderServiceReference.VoiceRecording voiceRecording) {
            this.UpsertVoiceRecordingAsync(voiceRecording, null);
        }
        
        public void UpsertVoiceRecordingAsync(VoxCTRL.ActivityRecorderServiceReference.VoiceRecording voiceRecording, object userState) {
            if ((this.onBeginUpsertVoiceRecordingDelegate == null)) {
                this.onBeginUpsertVoiceRecordingDelegate = new BeginOperationDelegate(this.OnBeginUpsertVoiceRecording);
            }
            if ((this.onEndUpsertVoiceRecordingDelegate == null)) {
                this.onEndUpsertVoiceRecordingDelegate = new EndOperationDelegate(this.OnEndUpsertVoiceRecording);
            }
            if ((this.onUpsertVoiceRecordingCompletedDelegate == null)) {
                this.onUpsertVoiceRecordingCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnUpsertVoiceRecordingCompleted);
            }
            base.InvokeAsync(this.onBeginUpsertVoiceRecordingDelegate, new object[] {
                        voiceRecording}, this.onEndUpsertVoiceRecordingDelegate, this.onUpsertVoiceRecordingCompletedDelegate, userState);
        }
        
        public void DeleteVoiceRecording(VoxCTRL.ActivityRecorderServiceReference.VoiceRecording voiceRecording) {
            base.Channel.DeleteVoiceRecording(voiceRecording);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public System.IAsyncResult BeginDeleteVoiceRecording(VoxCTRL.ActivityRecorderServiceReference.VoiceRecording voiceRecording, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginDeleteVoiceRecording(voiceRecording, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public void EndDeleteVoiceRecording(System.IAsyncResult result) {
            base.Channel.EndDeleteVoiceRecording(result);
        }
        
        private System.IAsyncResult OnBeginDeleteVoiceRecording(object[] inValues, System.AsyncCallback callback, object asyncState) {
            VoxCTRL.ActivityRecorderServiceReference.VoiceRecording voiceRecording = ((VoxCTRL.ActivityRecorderServiceReference.VoiceRecording)(inValues[0]));
            return this.BeginDeleteVoiceRecording(voiceRecording, callback, asyncState);
        }
        
        private object[] OnEndDeleteVoiceRecording(System.IAsyncResult result) {
            this.EndDeleteVoiceRecording(result);
            return null;
        }
        
        private void OnDeleteVoiceRecordingCompleted(object state) {
            if ((this.DeleteVoiceRecordingCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.DeleteVoiceRecordingCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void DeleteVoiceRecordingAsync(VoxCTRL.ActivityRecorderServiceReference.VoiceRecording voiceRecording) {
            this.DeleteVoiceRecordingAsync(voiceRecording, null);
        }
        
        public void DeleteVoiceRecordingAsync(VoxCTRL.ActivityRecorderServiceReference.VoiceRecording voiceRecording, object userState) {
            if ((this.onBeginDeleteVoiceRecordingDelegate == null)) {
                this.onBeginDeleteVoiceRecordingDelegate = new BeginOperationDelegate(this.OnBeginDeleteVoiceRecording);
            }
            if ((this.onEndDeleteVoiceRecordingDelegate == null)) {
                this.onEndDeleteVoiceRecordingDelegate = new EndOperationDelegate(this.OnEndDeleteVoiceRecording);
            }
            if ((this.onDeleteVoiceRecordingCompletedDelegate == null)) {
                this.onDeleteVoiceRecordingCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnDeleteVoiceRecordingCompleted);
            }
            base.InvokeAsync(this.onBeginDeleteVoiceRecordingDelegate, new object[] {
                        voiceRecording}, this.onEndDeleteVoiceRecordingDelegate, this.onDeleteVoiceRecordingCompletedDelegate, userState);
        }
        
        public VoxCTRL.ActivityRecorderServiceReference.ApplicationUpdateInfo GetApplicationUpdate(int userId, string application, string currentVersion) {
            return base.Channel.GetApplicationUpdate(userId, application, currentVersion);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public System.IAsyncResult BeginGetApplicationUpdate(int userId, string application, string currentVersion, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginGetApplicationUpdate(userId, application, currentVersion, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public VoxCTRL.ActivityRecorderServiceReference.ApplicationUpdateInfo EndGetApplicationUpdate(System.IAsyncResult result) {
            return base.Channel.EndGetApplicationUpdate(result);
        }
        
        private System.IAsyncResult OnBeginGetApplicationUpdate(object[] inValues, System.AsyncCallback callback, object asyncState) {
            int userId = ((int)(inValues[0]));
            string application = ((string)(inValues[1]));
            string currentVersion = ((string)(inValues[2]));
            return this.BeginGetApplicationUpdate(userId, application, currentVersion, callback, asyncState);
        }
        
        private object[] OnEndGetApplicationUpdate(System.IAsyncResult result) {
            VoxCTRL.ActivityRecorderServiceReference.ApplicationUpdateInfo retVal = this.EndGetApplicationUpdate(result);
            return new object[] {
                    retVal};
        }
        
        private void OnGetApplicationUpdateCompleted(object state) {
            if ((this.GetApplicationUpdateCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.GetApplicationUpdateCompleted(this, new GetApplicationUpdateCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void GetApplicationUpdateAsync(int userId, string application, string currentVersion) {
            this.GetApplicationUpdateAsync(userId, application, currentVersion, null);
        }
        
        public void GetApplicationUpdateAsync(int userId, string application, string currentVersion, object userState) {
            if ((this.onBeginGetApplicationUpdateDelegate == null)) {
                this.onBeginGetApplicationUpdateDelegate = new BeginOperationDelegate(this.OnBeginGetApplicationUpdate);
            }
            if ((this.onEndGetApplicationUpdateDelegate == null)) {
                this.onEndGetApplicationUpdateDelegate = new EndOperationDelegate(this.OnEndGetApplicationUpdate);
            }
            if ((this.onGetApplicationUpdateCompletedDelegate == null)) {
                this.onGetApplicationUpdateCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnGetApplicationUpdateCompleted);
            }
            base.InvokeAsync(this.onBeginGetApplicationUpdateDelegate, new object[] {
                        userId,
                        application,
                        currentVersion}, this.onEndGetApplicationUpdateDelegate, this.onGetApplicationUpdateCompletedDelegate, userState);
        }
        
        public byte[] GetUpdateChunk(System.Guid fileId, long chunkIndex) {
            return base.Channel.GetUpdateChunk(fileId, chunkIndex);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public System.IAsyncResult BeginGetUpdateChunk(System.Guid fileId, long chunkIndex, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginGetUpdateChunk(fileId, chunkIndex, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public byte[] EndGetUpdateChunk(System.IAsyncResult result) {
            return base.Channel.EndGetUpdateChunk(result);
        }
        
        private System.IAsyncResult OnBeginGetUpdateChunk(object[] inValues, System.AsyncCallback callback, object asyncState) {
            System.Guid fileId = ((System.Guid)(inValues[0]));
            long chunkIndex = ((long)(inValues[1]));
            return this.BeginGetUpdateChunk(fileId, chunkIndex, callback, asyncState);
        }
        
        private object[] OnEndGetUpdateChunk(System.IAsyncResult result) {
            byte[] retVal = this.EndGetUpdateChunk(result);
            return new object[] {
                    retVal};
        }
        
        private void OnGetUpdateChunkCompleted(object state) {
            if ((this.GetUpdateChunkCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.GetUpdateChunkCompleted(this, new GetUpdateChunkCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void GetUpdateChunkAsync(System.Guid fileId, long chunkIndex) {
            this.GetUpdateChunkAsync(fileId, chunkIndex, null);
        }
        
        public void GetUpdateChunkAsync(System.Guid fileId, long chunkIndex, object userState) {
            if ((this.onBeginGetUpdateChunkDelegate == null)) {
                this.onBeginGetUpdateChunkDelegate = new BeginOperationDelegate(this.OnBeginGetUpdateChunk);
            }
            if ((this.onEndGetUpdateChunkDelegate == null)) {
                this.onEndGetUpdateChunkDelegate = new EndOperationDelegate(this.OnEndGetUpdateChunk);
            }
            if ((this.onGetUpdateChunkCompletedDelegate == null)) {
                this.onGetUpdateChunkCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnGetUpdateChunkCompleted);
            }
            base.InvokeAsync(this.onBeginGetUpdateChunkDelegate, new object[] {
                        fileId,
                        chunkIndex}, this.onEndGetUpdateChunkDelegate, this.onGetUpdateChunkCompletedDelegate, userState);
        }
        
        public VoxCTRL.ActivityRecorderServiceReference.ClientSetting GetClientSettings(out string newVersion, int userId, string oldVersion) {
            return base.Channel.GetClientSettings(out newVersion, userId, oldVersion);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public System.IAsyncResult BeginGetClientSettings(int userId, string oldVersion, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginGetClientSettings(userId, oldVersion, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public VoxCTRL.ActivityRecorderServiceReference.ClientSetting EndGetClientSettings(out string newVersion, System.IAsyncResult result) {
            return base.Channel.EndGetClientSettings(out newVersion, result);
        }
        
        private System.IAsyncResult OnBeginGetClientSettings(object[] inValues, System.AsyncCallback callback, object asyncState) {
            int userId = ((int)(inValues[0]));
            string oldVersion = ((string)(inValues[1]));
            return this.BeginGetClientSettings(userId, oldVersion, callback, asyncState);
        }
        
        private object[] OnEndGetClientSettings(System.IAsyncResult result) {
            string newVersion = this.GetDefaultValueForInitialization<string>();
            VoxCTRL.ActivityRecorderServiceReference.ClientSetting retVal = this.EndGetClientSettings(out newVersion, result);
            return new object[] {
                    newVersion,
                    retVal};
        }
        
        private void OnGetClientSettingsCompleted(object state) {
            if ((this.GetClientSettingsCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.GetClientSettingsCompleted(this, new GetClientSettingsCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void GetClientSettingsAsync(int userId, string oldVersion) {
            this.GetClientSettingsAsync(userId, oldVersion, null);
        }
        
        public void GetClientSettingsAsync(int userId, string oldVersion, object userState) {
            if ((this.onBeginGetClientSettingsDelegate == null)) {
                this.onBeginGetClientSettingsDelegate = new BeginOperationDelegate(this.OnBeginGetClientSettings);
            }
            if ((this.onEndGetClientSettingsDelegate == null)) {
                this.onEndGetClientSettingsDelegate = new EndOperationDelegate(this.OnEndGetClientSettings);
            }
            if ((this.onGetClientSettingsCompletedDelegate == null)) {
                this.onGetClientSettingsCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnGetClientSettingsCompleted);
            }
            base.InvokeAsync(this.onBeginGetClientSettingsDelegate, new object[] {
                        userId,
                        oldVersion}, this.onEndGetClientSettingsDelegate, this.onGetClientSettingsCompletedDelegate, userState);
        }
        
        public void ReportClientVersion(int userId, int computerId, int major, int minor, int build, int revision, string application) {
            base.Channel.ReportClientVersion(userId, computerId, major, minor, build, revision, application);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public System.IAsyncResult BeginReportClientVersion(int userId, int computerId, int major, int minor, int build, int revision, string application, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginReportClientVersion(userId, computerId, major, minor, build, revision, application, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public void EndReportClientVersion(System.IAsyncResult result) {
            base.Channel.EndReportClientVersion(result);
        }
        
        private System.IAsyncResult OnBeginReportClientVersion(object[] inValues, System.AsyncCallback callback, object asyncState) {
            int userId = ((int)(inValues[0]));
            int computerId = ((int)(inValues[1]));
            int major = ((int)(inValues[2]));
            int minor = ((int)(inValues[3]));
            int build = ((int)(inValues[4]));
            int revision = ((int)(inValues[5]));
            string application = ((string)(inValues[6]));
            return this.BeginReportClientVersion(userId, computerId, major, minor, build, revision, application, callback, asyncState);
        }
        
        private object[] OnEndReportClientVersion(System.IAsyncResult result) {
            this.EndReportClientVersion(result);
            return null;
        }
        
        private void OnReportClientVersionCompleted(object state) {
            if ((this.ReportClientVersionCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.ReportClientVersionCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void ReportClientVersionAsync(int userId, int computerId, int major, int minor, int build, int revision, string application) {
            this.ReportClientVersionAsync(userId, computerId, major, minor, build, revision, application, null);
        }
        
        public void ReportClientVersionAsync(int userId, int computerId, int major, int minor, int build, int revision, string application, object userState) {
            if ((this.onBeginReportClientVersionDelegate == null)) {
                this.onBeginReportClientVersionDelegate = new BeginOperationDelegate(this.OnBeginReportClientVersion);
            }
            if ((this.onEndReportClientVersionDelegate == null)) {
                this.onEndReportClientVersionDelegate = new EndOperationDelegate(this.OnEndReportClientVersion);
            }
            if ((this.onReportClientVersionCompletedDelegate == null)) {
                this.onReportClientVersionCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnReportClientVersionCompleted);
            }
            base.InvokeAsync(this.onBeginReportClientVersionDelegate, new object[] {
                        userId,
                        computerId,
                        major,
                        minor,
                        build,
                        revision,
                        application}, this.onEndReportClientVersionDelegate, this.onReportClientVersionCompletedDelegate, userState);
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ActivityRecorderServiceReference.IActiveDirectoryLoginService")]
    public interface IActiveDirectoryLoginService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IActiveDirectoryLoginService/GetClientLoginTicket", ReplyAction="http://tempuri.org/IActiveDirectoryLoginService/GetClientLoginTicketResponse")]
        VoxCTRL.ActivityRecorderServiceReference.ClientLoginTicket GetClientLoginTicket();
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IActiveDirectoryLoginService/GetClientLoginTicket", ReplyAction="http://tempuri.org/IActiveDirectoryLoginService/GetClientLoginTicketResponse")]
        System.IAsyncResult BeginGetClientLoginTicket(System.AsyncCallback callback, object asyncState);
        
        VoxCTRL.ActivityRecorderServiceReference.ClientLoginTicket EndGetClientLoginTicket(System.IAsyncResult result);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IActiveDirectoryLoginServiceChannel : VoxCTRL.ActivityRecorderServiceReference.IActiveDirectoryLoginService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GetClientLoginTicketCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public GetClientLoginTicketCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public VoxCTRL.ActivityRecorderServiceReference.ClientLoginTicket Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((VoxCTRL.ActivityRecorderServiceReference.ClientLoginTicket)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ActiveDirectoryLoginServiceClient : System.ServiceModel.ClientBase<VoxCTRL.ActivityRecorderServiceReference.IActiveDirectoryLoginService>, VoxCTRL.ActivityRecorderServiceReference.IActiveDirectoryLoginService {
        
        private BeginOperationDelegate onBeginGetClientLoginTicketDelegate;
        
        private EndOperationDelegate onEndGetClientLoginTicketDelegate;
        
        private System.Threading.SendOrPostCallback onGetClientLoginTicketCompletedDelegate;
        
        public ActiveDirectoryLoginServiceClient() {
        }
        
        public ActiveDirectoryLoginServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ActiveDirectoryLoginServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ActiveDirectoryLoginServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ActiveDirectoryLoginServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public event System.EventHandler<GetClientLoginTicketCompletedEventArgs> GetClientLoginTicketCompleted;
        
        public VoxCTRL.ActivityRecorderServiceReference.ClientLoginTicket GetClientLoginTicket() {
            return base.Channel.GetClientLoginTicket();
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public System.IAsyncResult BeginGetClientLoginTicket(System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginGetClientLoginTicket(callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public VoxCTRL.ActivityRecorderServiceReference.ClientLoginTicket EndGetClientLoginTicket(System.IAsyncResult result) {
            return base.Channel.EndGetClientLoginTicket(result);
        }
        
        private System.IAsyncResult OnBeginGetClientLoginTicket(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return this.BeginGetClientLoginTicket(callback, asyncState);
        }
        
        private object[] OnEndGetClientLoginTicket(System.IAsyncResult result) {
            VoxCTRL.ActivityRecorderServiceReference.ClientLoginTicket retVal = this.EndGetClientLoginTicket(result);
            return new object[] {
                    retVal};
        }
        
        private void OnGetClientLoginTicketCompleted(object state) {
            if ((this.GetClientLoginTicketCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.GetClientLoginTicketCompleted(this, new GetClientLoginTicketCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void GetClientLoginTicketAsync() {
            this.GetClientLoginTicketAsync(null);
        }
        
        public void GetClientLoginTicketAsync(object userState) {
            if ((this.onBeginGetClientLoginTicketDelegate == null)) {
                this.onBeginGetClientLoginTicketDelegate = new BeginOperationDelegate(this.OnBeginGetClientLoginTicket);
            }
            if ((this.onEndGetClientLoginTicketDelegate == null)) {
                this.onEndGetClientLoginTicketDelegate = new EndOperationDelegate(this.OnEndGetClientLoginTicket);
            }
            if ((this.onGetClientLoginTicketCompletedDelegate == null)) {
                this.onGetClientLoginTicketCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnGetClientLoginTicketCompleted);
            }
            base.InvokeAsync(this.onBeginGetClientLoginTicketDelegate, null, this.onEndGetClientLoginTicketDelegate, this.onGetClientLoginTicketCompletedDelegate, userState);
        }
    }
}
