#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tct.ActivityRecorderService
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="recorder")]
	public partial class IvrDataClassesDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertCalendarException(CalendarException instance);
    partial void UpdateCalendarException(CalendarException instance);
    partial void DeleteCalendarException(CalendarException instance);
    partial void InsertCalendar(Calendar instance);
    partial void UpdateCalendar(Calendar instance);
    partial void DeleteCalendar(Calendar instance);
    #endregion
		
		public IvrDataClassesDataContext() : 
				base(global::Tct.ActivityRecorderService.Properties.Settings.Default.recorderConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public IvrDataClassesDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public IvrDataClassesDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public IvrDataClassesDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public IvrDataClassesDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<CalendarException> CalendarExceptions
		{
			get
			{
				return this.GetTable<CalendarException>();
			}
		}
		
		public System.Data.Linq.Table<Calendar> Calendars
		{
			get
			{
				return this.GetTable<Calendar>();
			}
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.IsWorkDay", IsComposable=true)]
		public System.Nullable<bool> IsWorkDay([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> calendarId, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="DateTime")] System.Nullable<System.DateTime> date)
		{
			return ((System.Nullable<bool>)(this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), calendarId, date).ReturnValue));
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.CalendarExceptions")]
	public partial class CalendarException : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id;
		
		private string _Name;
		
		private System.DateTime _CreateDate;
		
		private int _CalendarId;
		
		private System.DateTime _Date;
		
		private bool _IsWorkDay;
		
		private System.Nullable<short> _TargetWorkTimeInMinutes;
		
		private System.Nullable<short> _CoreTimeEnd;
		
		private EntityRef<Calendar> _Calendar;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OnNameChanging(string value);
    partial void OnNameChanged();
    partial void OnCreateDateChanging(System.DateTime value);
    partial void OnCreateDateChanged();
    partial void OnCalendarIdChanging(int value);
    partial void OnCalendarIdChanged();
    partial void OnDateChanging(System.DateTime value);
    partial void OnDateChanged();
    partial void OnIsWorkDayChanging(bool value);
    partial void OnIsWorkDayChanged();
    partial void OnTargetWorkTimeInMinutesChanging(System.Nullable<short> value);
    partial void OnTargetWorkTimeInMinutesChanged();
    partial void OnCoreTimeEndChanging(System.Nullable<short> value);
    partial void OnCoreTimeEndChanged();
    #endregion
		
		public CalendarException()
		{
			this._Calendar = default(EntityRef<Calendar>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Name", DbType="NVarChar(500)")]
		public string Name
		{
			get
			{
				return this._Name;
			}
			set
			{
				if ((this._Name != value))
				{
					this.OnNameChanging(value);
					this.SendPropertyChanging();
					this._Name = value;
					this.SendPropertyChanged("Name");
					this.OnNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CreateDate", DbType="DateTime NOT NULL", IsDbGenerated=true)]
		public System.DateTime CreateDate
		{
			get
			{
				return this._CreateDate;
			}
			set
			{
				if ((this._CreateDate != value))
				{
					this.OnCreateDateChanging(value);
					this.SendPropertyChanging();
					this._CreateDate = value;
					this.SendPropertyChanged("CreateDate");
					this.OnCreateDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CalendarId", DbType="Int NOT NULL")]
		public int CalendarId
		{
			get
			{
				return this._CalendarId;
			}
			set
			{
				if ((this._CalendarId != value))
				{
					if (this._Calendar.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnCalendarIdChanging(value);
					this.SendPropertyChanging();
					this._CalendarId = value;
					this.SendPropertyChanged("CalendarId");
					this.OnCalendarIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Date", DbType="DateTime NOT NULL")]
		public System.DateTime Date
		{
			get
			{
				return this._Date;
			}
			set
			{
				if ((this._Date != value))
				{
					this.OnDateChanging(value);
					this.SendPropertyChanging();
					this._Date = value;
					this.SendPropertyChanged("Date");
					this.OnDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IsWorkDay", DbType="Bit NOT NULL")]
		public bool IsWorkDay
		{
			get
			{
				return this._IsWorkDay;
			}
			set
			{
				if ((this._IsWorkDay != value))
				{
					this.OnIsWorkDayChanging(value);
					this.SendPropertyChanging();
					this._IsWorkDay = value;
					this.SendPropertyChanged("IsWorkDay");
					this.OnIsWorkDayChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TargetWorkTimeInMinutes", DbType="smallint")]
		public System.Nullable<short> TargetWorkTimeInMinutes
		{
			get
			{
				return this._TargetWorkTimeInMinutes;
			}
			set
			{
				if ((this._TargetWorkTimeInMinutes != value))
				{
					this.OnTargetWorkTimeInMinutesChanging(value);
					this.SendPropertyChanging();
					this._TargetWorkTimeInMinutes = value;
					this.SendPropertyChanged("TargetWorkTimeInMinutes");
					this.OnTargetWorkTimeInMinutesChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CoreTimeEnd", DbType="smallint")]
		public System.Nullable<short> CoreTimeEnd
		{
			get
			{
				return this._CoreTimeEnd;
			}
			set
			{
				if ((this._CoreTimeEnd != value))
				{
					this.OnCoreTimeEndChanging(value);
					this.SendPropertyChanging();
					this._CoreTimeEnd = value;
					this.SendPropertyChanged("CoreTimeEnd");
					this.OnCoreTimeEndChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Calendar_CalendarException", Storage="_Calendar", ThisKey="CalendarId", OtherKey="Id", IsForeignKey=true)]
		public Calendar Calendar
		{
			get
			{
				return this._Calendar.Entity;
			}
			set
			{
				Calendar previousValue = this._Calendar.Entity;
				if (((previousValue != value) 
							|| (this._Calendar.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Calendar.Entity = null;
						previousValue.CalendarExceptions.Remove(this);
					}
					this._Calendar.Entity = value;
					if ((value != null))
					{
						value.CalendarExceptions.Add(this);
						this._CalendarId = value.Id;
					}
					else
					{
						this._CalendarId = default(int);
					}
					this.SendPropertyChanged("Calendar");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Calendars")]
	public partial class Calendar : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id;
		
		private string _Name;
		
		private System.DateTime _CreateDate;
		
		private bool _IsMondayWorkDay;
		
		private bool _IsTuesdayWorkDay;
		
		private bool _IsWednesdayWorkDay;
		
		private bool _IsThursdayWorkDay;
		
		private bool _IsFridayWorkDay;
		
		private bool _IsSaturdayWorkDay;
		
		private bool _IsSundayWorkDay;
		
		private System.Nullable<int> _InheritedFrom;
		
		private System.Nullable<short> _TargetWorkTimeInMinutesMonday;
		
		private System.Nullable<short> _TargetWorkTimeInMinutesTuesday;
		
		private System.Nullable<short> _TargetWorkTimeInMinutesWednesday;
		
		private System.Nullable<short> _TargetWorkTimeInMinutesThursday;
		
		private System.Nullable<short> _TargetWorkTimeInMinutesFriday;
		
		private System.Nullable<short> _TargetWorkTimeInMinutesSaturday;
		
		private System.Nullable<short> _TargetWorkTimeInMinutesSunday;
		
		private System.Nullable<short> _CoreTimeEndMonday;
		
		private System.Nullable<short> _CoreTimeEndTuesday;
		
		private System.Nullable<short> _CoreTimeEndWednesday;
		
		private System.Nullable<short> _CoreTimeEndThursday;
		
		private System.Nullable<short> _CoreTimeEndFriday;
		
		private System.Nullable<short> _CoreTimeEndSaturday;
		
		private System.Nullable<short> _CoreTimeEndSunday;
		
		private EntitySet<CalendarException> _CalendarExceptions;
		
		private EntitySet<Calendar> _Calendars;
		
		private EntityRef<Calendar> _Calendar1;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OnNameChanging(string value);
    partial void OnNameChanged();
    partial void OnCreateDateChanging(System.DateTime value);
    partial void OnCreateDateChanged();
    partial void OnIsMondayWorkDayChanging(bool value);
    partial void OnIsMondayWorkDayChanged();
    partial void OnIsTuesdayWorkDayChanging(bool value);
    partial void OnIsTuesdayWorkDayChanged();
    partial void OnIsWednesdayWorkDayChanging(bool value);
    partial void OnIsWednesdayWorkDayChanged();
    partial void OnIsThursdayWorkDayChanging(bool value);
    partial void OnIsThursdayWorkDayChanged();
    partial void OnIsFridayWorkDayChanging(bool value);
    partial void OnIsFridayWorkDayChanged();
    partial void OnIsSaturdayWorkDayChanging(bool value);
    partial void OnIsSaturdayWorkDayChanged();
    partial void OnIsSundayWorkDayChanging(bool value);
    partial void OnIsSundayWorkDayChanged();
    partial void OnInheritedFromChanging(System.Nullable<int> value);
    partial void OnInheritedFromChanged();
    partial void OnTargetWorkTimeInMinutesMondayChanging(System.Nullable<short> value);
    partial void OnTargetWorkTimeInMinutesMondayChanged();
    partial void OnTargetWorkTimeInMinutesTuesdayChanging(System.Nullable<short> value);
    partial void OnTargetWorkTimeInMinutesTuesdayChanged();
    partial void OnTargetWorkTimeInMinutesWednesdayChanging(System.Nullable<short> value);
    partial void OnTargetWorkTimeInMinutesWednesdayChanged();
    partial void OnTargetWorkTimeInMinutesThursdayChanging(System.Nullable<short> value);
    partial void OnTargetWorkTimeInMinutesThursdayChanged();
    partial void OnTargetWorkTimeInMinutesFridayChanging(System.Nullable<short> value);
    partial void OnTargetWorkTimeInMinutesFridayChanged();
    partial void OnTargetWorkTimeInMinutesSaturdayChanging(System.Nullable<short> value);
    partial void OnTargetWorkTimeInMinutesSaturdayChanged();
    partial void OnTargetWorkTimeInMinutesSundayChanging(System.Nullable<short> value);
    partial void OnTargetWorkTimeInMinutesSundayChanged();
    partial void OnCoreTimeEndMondayChanging(System.Nullable<short> value);
    partial void OnCoreTimeEndMondayChanged();
    partial void OnCoreTimeEndTuesdayChanging(System.Nullable<short> value);
    partial void OnCoreTimeEndTuesdayChanged();
    partial void OnCoreTimeEndWednesdayChanging(System.Nullable<short> value);
    partial void OnCoreTimeEndWednesdayChanged();
    partial void OnCoreTimeEndThursdayChanging(System.Nullable<short> value);
    partial void OnCoreTimeEndThursdayChanged();
    partial void OnCoreTimeEndFridayChanging(System.Nullable<short> value);
    partial void OnCoreTimeEndFridayChanged();
    partial void OnCoreTimeEndSaturdayChanging(System.Nullable<short> value);
    partial void OnCoreTimeEndSaturdayChanged();
    partial void OnCoreTimeEndSundayChanging(System.Nullable<short> value);
    partial void OnCoreTimeEndSundayChanged();
    #endregion
		
		public Calendar()
		{
			this._CalendarExceptions = new EntitySet<CalendarException>(new Action<CalendarException>(this.attach_CalendarExceptions), new Action<CalendarException>(this.detach_CalendarExceptions));
			this._Calendars = new EntitySet<Calendar>(new Action<Calendar>(this.attach_Calendars), new Action<Calendar>(this.detach_Calendars));
			this._Calendar1 = default(EntityRef<Calendar>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Name", DbType="NVarChar(500)")]
		public string Name
		{
			get
			{
				return this._Name;
			}
			set
			{
				if ((this._Name != value))
				{
					this.OnNameChanging(value);
					this.SendPropertyChanging();
					this._Name = value;
					this.SendPropertyChanged("Name");
					this.OnNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CreateDate", DbType="DateTime NOT NULL", IsDbGenerated=true)]
		public System.DateTime CreateDate
		{
			get
			{
				return this._CreateDate;
			}
			set
			{
				if ((this._CreateDate != value))
				{
					this.OnCreateDateChanging(value);
					this.SendPropertyChanging();
					this._CreateDate = value;
					this.SendPropertyChanged("CreateDate");
					this.OnCreateDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IsMondayWorkDay", DbType="Bit NOT NULL")]
		public bool IsMondayWorkDay
		{
			get
			{
				return this._IsMondayWorkDay;
			}
			set
			{
				if ((this._IsMondayWorkDay != value))
				{
					this.OnIsMondayWorkDayChanging(value);
					this.SendPropertyChanging();
					this._IsMondayWorkDay = value;
					this.SendPropertyChanged("IsMondayWorkDay");
					this.OnIsMondayWorkDayChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IsTuesdayWorkDay", DbType="Bit NOT NULL")]
		public bool IsTuesdayWorkDay
		{
			get
			{
				return this._IsTuesdayWorkDay;
			}
			set
			{
				if ((this._IsTuesdayWorkDay != value))
				{
					this.OnIsTuesdayWorkDayChanging(value);
					this.SendPropertyChanging();
					this._IsTuesdayWorkDay = value;
					this.SendPropertyChanged("IsTuesdayWorkDay");
					this.OnIsTuesdayWorkDayChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IsWednesdayWorkDay", DbType="Bit NOT NULL")]
		public bool IsWednesdayWorkDay
		{
			get
			{
				return this._IsWednesdayWorkDay;
			}
			set
			{
				if ((this._IsWednesdayWorkDay != value))
				{
					this.OnIsWednesdayWorkDayChanging(value);
					this.SendPropertyChanging();
					this._IsWednesdayWorkDay = value;
					this.SendPropertyChanged("IsWednesdayWorkDay");
					this.OnIsWednesdayWorkDayChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IsThursdayWorkDay", DbType="Bit NOT NULL")]
		public bool IsThursdayWorkDay
		{
			get
			{
				return this._IsThursdayWorkDay;
			}
			set
			{
				if ((this._IsThursdayWorkDay != value))
				{
					this.OnIsThursdayWorkDayChanging(value);
					this.SendPropertyChanging();
					this._IsThursdayWorkDay = value;
					this.SendPropertyChanged("IsThursdayWorkDay");
					this.OnIsThursdayWorkDayChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IsFridayWorkDay", DbType="Bit NOT NULL")]
		public bool IsFridayWorkDay
		{
			get
			{
				return this._IsFridayWorkDay;
			}
			set
			{
				if ((this._IsFridayWorkDay != value))
				{
					this.OnIsFridayWorkDayChanging(value);
					this.SendPropertyChanging();
					this._IsFridayWorkDay = value;
					this.SendPropertyChanged("IsFridayWorkDay");
					this.OnIsFridayWorkDayChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IsSaturdayWorkDay", DbType="Bit NOT NULL")]
		public bool IsSaturdayWorkDay
		{
			get
			{
				return this._IsSaturdayWorkDay;
			}
			set
			{
				if ((this._IsSaturdayWorkDay != value))
				{
					this.OnIsSaturdayWorkDayChanging(value);
					this.SendPropertyChanging();
					this._IsSaturdayWorkDay = value;
					this.SendPropertyChanged("IsSaturdayWorkDay");
					this.OnIsSaturdayWorkDayChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IsSundayWorkDay", DbType="Bit NOT NULL")]
		public bool IsSundayWorkDay
		{
			get
			{
				return this._IsSundayWorkDay;
			}
			set
			{
				if ((this._IsSundayWorkDay != value))
				{
					this.OnIsSundayWorkDayChanging(value);
					this.SendPropertyChanging();
					this._IsSundayWorkDay = value;
					this.SendPropertyChanged("IsSundayWorkDay");
					this.OnIsSundayWorkDayChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_InheritedFrom", DbType="Int")]
		public System.Nullable<int> InheritedFrom
		{
			get
			{
				return this._InheritedFrom;
			}
			set
			{
				if ((this._InheritedFrom != value))
				{
					if (this._Calendar1.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnInheritedFromChanging(value);
					this.SendPropertyChanging();
					this._InheritedFrom = value;
					this.SendPropertyChanged("InheritedFrom");
					this.OnInheritedFromChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TargetWorkTimeInMinutesMonday", DbType="smallint")]
		public System.Nullable<short> TargetWorkTimeInMinutesMonday
		{
			get
			{
				return this._TargetWorkTimeInMinutesMonday;
			}
			set
			{
				if ((this._TargetWorkTimeInMinutesMonday != value))
				{
					this.OnTargetWorkTimeInMinutesMondayChanging(value);
					this.SendPropertyChanging();
					this._TargetWorkTimeInMinutesMonday = value;
					this.SendPropertyChanged("TargetWorkTimeInMinutesMonday");
					this.OnTargetWorkTimeInMinutesMondayChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TargetWorkTimeInMinutesTuesday", DbType="smallint")]
		public System.Nullable<short> TargetWorkTimeInMinutesTuesday
		{
			get
			{
				return this._TargetWorkTimeInMinutesTuesday;
			}
			set
			{
				if ((this._TargetWorkTimeInMinutesTuesday != value))
				{
					this.OnTargetWorkTimeInMinutesTuesdayChanging(value);
					this.SendPropertyChanging();
					this._TargetWorkTimeInMinutesTuesday = value;
					this.SendPropertyChanged("TargetWorkTimeInMinutesTuesday");
					this.OnTargetWorkTimeInMinutesTuesdayChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TargetWorkTimeInMinutesWednesday", DbType="smallint")]
		public System.Nullable<short> TargetWorkTimeInMinutesWednesday
		{
			get
			{
				return this._TargetWorkTimeInMinutesWednesday;
			}
			set
			{
				if ((this._TargetWorkTimeInMinutesWednesday != value))
				{
					this.OnTargetWorkTimeInMinutesWednesdayChanging(value);
					this.SendPropertyChanging();
					this._TargetWorkTimeInMinutesWednesday = value;
					this.SendPropertyChanged("TargetWorkTimeInMinutesWednesday");
					this.OnTargetWorkTimeInMinutesWednesdayChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TargetWorkTimeInMinutesThursday", DbType="smallint")]
		public System.Nullable<short> TargetWorkTimeInMinutesThursday
		{
			get
			{
				return this._TargetWorkTimeInMinutesThursday;
			}
			set
			{
				if ((this._TargetWorkTimeInMinutesThursday != value))
				{
					this.OnTargetWorkTimeInMinutesThursdayChanging(value);
					this.SendPropertyChanging();
					this._TargetWorkTimeInMinutesThursday = value;
					this.SendPropertyChanged("TargetWorkTimeInMinutesThursday");
					this.OnTargetWorkTimeInMinutesThursdayChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TargetWorkTimeInMinutesFriday", DbType="smallint")]
		public System.Nullable<short> TargetWorkTimeInMinutesFriday
		{
			get
			{
				return this._TargetWorkTimeInMinutesFriday;
			}
			set
			{
				if ((this._TargetWorkTimeInMinutesFriday != value))
				{
					this.OnTargetWorkTimeInMinutesFridayChanging(value);
					this.SendPropertyChanging();
					this._TargetWorkTimeInMinutesFriday = value;
					this.SendPropertyChanged("TargetWorkTimeInMinutesFriday");
					this.OnTargetWorkTimeInMinutesFridayChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TargetWorkTimeInMinutesSaturday", DbType="smallint")]
		public System.Nullable<short> TargetWorkTimeInMinutesSaturday
		{
			get
			{
				return this._TargetWorkTimeInMinutesSaturday;
			}
			set
			{
				if ((this._TargetWorkTimeInMinutesSaturday != value))
				{
					this.OnTargetWorkTimeInMinutesSaturdayChanging(value);
					this.SendPropertyChanging();
					this._TargetWorkTimeInMinutesSaturday = value;
					this.SendPropertyChanged("TargetWorkTimeInMinutesSaturday");
					this.OnTargetWorkTimeInMinutesSaturdayChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TargetWorkTimeInMinutesSunday", DbType="smallint")]
		public System.Nullable<short> TargetWorkTimeInMinutesSunday
		{
			get
			{
				return this._TargetWorkTimeInMinutesSunday;
			}
			set
			{
				if ((this._TargetWorkTimeInMinutesSunday != value))
				{
					this.OnTargetWorkTimeInMinutesSundayChanging(value);
					this.SendPropertyChanging();
					this._TargetWorkTimeInMinutesSunday = value;
					this.SendPropertyChanged("TargetWorkTimeInMinutesSunday");
					this.OnTargetWorkTimeInMinutesSundayChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CoreTimeEndMonday", DbType="smallint")]
		public System.Nullable<short> CoreTimeEndMonday
		{
			get
			{
				return this._CoreTimeEndMonday;
			}
			set
			{
				if ((this._CoreTimeEndMonday != value))
				{
					this.OnCoreTimeEndMondayChanging(value);
					this.SendPropertyChanging();
					this._CoreTimeEndMonday = value;
					this.SendPropertyChanged("CoreTimeEndMonday");
					this.OnCoreTimeEndMondayChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CoreTimeEndTuesday", DbType="smallint")]
		public System.Nullable<short> CoreTimeEndTuesday
		{
			get
			{
				return this._CoreTimeEndTuesday;
			}
			set
			{
				if ((this._CoreTimeEndTuesday != value))
				{
					this.OnCoreTimeEndTuesdayChanging(value);
					this.SendPropertyChanging();
					this._CoreTimeEndTuesday = value;
					this.SendPropertyChanged("CoreTimeEndTuesday");
					this.OnCoreTimeEndTuesdayChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CoreTimeEndWednesday", DbType="smallint")]
		public System.Nullable<short> CoreTimeEndWednesday
		{
			get
			{
				return this._CoreTimeEndWednesday;
			}
			set
			{
				if ((this._CoreTimeEndWednesday != value))
				{
					this.OnCoreTimeEndWednesdayChanging(value);
					this.SendPropertyChanging();
					this._CoreTimeEndWednesday = value;
					this.SendPropertyChanged("CoreTimeEndWednesday");
					this.OnCoreTimeEndWednesdayChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CoreTimeEndThursday", DbType="smallint")]
		public System.Nullable<short> CoreTimeEndThursday
		{
			get
			{
				return this._CoreTimeEndThursday;
			}
			set
			{
				if ((this._CoreTimeEndThursday != value))
				{
					this.OnCoreTimeEndThursdayChanging(value);
					this.SendPropertyChanging();
					this._CoreTimeEndThursday = value;
					this.SendPropertyChanged("CoreTimeEndThursday");
					this.OnCoreTimeEndThursdayChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CoreTimeEndFriday", DbType="smallint")]
		public System.Nullable<short> CoreTimeEndFriday
		{
			get
			{
				return this._CoreTimeEndFriday;
			}
			set
			{
				if ((this._CoreTimeEndFriday != value))
				{
					this.OnCoreTimeEndFridayChanging(value);
					this.SendPropertyChanging();
					this._CoreTimeEndFriday = value;
					this.SendPropertyChanged("CoreTimeEndFriday");
					this.OnCoreTimeEndFridayChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CoreTimeEndSaturday", DbType="smallint")]
		public System.Nullable<short> CoreTimeEndSaturday
		{
			get
			{
				return this._CoreTimeEndSaturday;
			}
			set
			{
				if ((this._CoreTimeEndSaturday != value))
				{
					this.OnCoreTimeEndSaturdayChanging(value);
					this.SendPropertyChanging();
					this._CoreTimeEndSaturday = value;
					this.SendPropertyChanged("CoreTimeEndSaturday");
					this.OnCoreTimeEndSaturdayChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CoreTimeEndSunday", DbType="smallint")]
		public System.Nullable<short> CoreTimeEndSunday
		{
			get
			{
				return this._CoreTimeEndSunday;
			}
			set
			{
				if ((this._CoreTimeEndSunday != value))
				{
					this.OnCoreTimeEndSundayChanging(value);
					this.SendPropertyChanging();
					this._CoreTimeEndSunday = value;
					this.SendPropertyChanged("CoreTimeEndSunday");
					this.OnCoreTimeEndSundayChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Calendar_CalendarException", Storage="_CalendarExceptions", ThisKey="Id", OtherKey="CalendarId")]
		public EntitySet<CalendarException> CalendarExceptions
		{
			get
			{
				return this._CalendarExceptions;
			}
			set
			{
				this._CalendarExceptions.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Calendar_Calendar", Storage="_Calendars", ThisKey="Id", OtherKey="InheritedFrom")]
		public EntitySet<Calendar> Calendars
		{
			get
			{
				return this._Calendars;
			}
			set
			{
				this._Calendars.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Calendar_Calendar", Storage="_Calendar1", ThisKey="InheritedFrom", OtherKey="Id", IsForeignKey=true)]
		public Calendar InheritedCalendar
		{
			get
			{
				return this._Calendar1.Entity;
			}
			set
			{
				Calendar previousValue = this._Calendar1.Entity;
				if (((previousValue != value) 
							|| (this._Calendar1.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Calendar1.Entity = null;
						previousValue.Calendars.Remove(this);
					}
					this._Calendar1.Entity = value;
					if ((value != null))
					{
						value.Calendars.Add(this);
						this._InheritedFrom = value.Id;
					}
					else
					{
						this._InheritedFrom = default(Nullable<int>);
					}
					this.SendPropertyChanged("InheritedCalendar");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_CalendarExceptions(CalendarException entity)
		{
			this.SendPropertyChanging();
			entity.Calendar = this;
		}
		
		private void detach_CalendarExceptions(CalendarException entity)
		{
			this.SendPropertyChanging();
			entity.Calendar = null;
		}
		
		private void attach_Calendars(Calendar entity)
		{
			this.SendPropertyChanging();
			entity.InheritedCalendar = this;
		}
		
		private void detach_Calendars(Calendar entity)
		{
			this.SendPropertyChanging();
			entity.InheritedCalendar = null;
		}
	}
}
#pragma warning restore 1591
