 using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Text.RegularExpressions;
using System.Threading.Tasks;

namespace Reporter
{
	public class UsefulLookup
	{
		private readonly Dictionary<string, AppCategory> usefulLookup = new Dictionary<string, AppCategory>(StringComparer.InvariantCultureIgnoreCase);

		public UsefulLookup()
		{
			usefulLookup = new Dictionary<string, AppCategory>(StringComparer.InvariantCultureIgnoreCase){
				{
					"explorer.exe", AppCategory.Neutral
				},
				{
					"Idle", AppCategory.Neutral
				},
				{
					"OUTLOOK.EXE", AppCategory.Neutral
				},
				{
					"devenv.exe", AppCategory.Productive
				},
				{
					"chrome.exe", AppCategory.Neutral
				},
				{
					"photoshop.exe", AppCategory.Productive
				},
				{
					"winword.exe", AppCategory.Productive
				},
				{
					"excel.exe", AppCategory.Productive
				},
				{
					"taskmgr.exe", AppCategory.NotProductive
				},
				{
					"iexplore.exe", AppCategory.Neutral
				},
				{
					"notepad.exe", AppCategory.Neutral
				},
				{
					"mstsc.exe", AppCategory.Productive
				},
				{
					"mspaint.exe", AppCategory.NotProductive
				},
				{
					"firefox.exe", AppCategory.Neutral
				},
				{
					"viber.exe", AppCategory.NotProductive
				},
				{
					"pycharm.exe", AppCategory.NotProductive
				},
				{
					"visio.exe", AppCategory.Productive
				},
				{
					"vlc.exe", AppCategory.NotProductive
				},
				{
					"skype.exe", AppCategory.NotProductive
				},
				{
					"wmplayer.exe", AppCategory.NotProductive
				},
				{
					"ssms.exe", AppCategory.Productive
				},
				{
					"thgw", AppCategory.Productive
				},
				{
					"notepad++.exe", AppCategory.Neutral
				},
				{
					"linqpad.exe", AppCategory.Productive
				},
				{
					"logexpert.exe", AppCategory.NotProductive
				},
				{
					"totalcmd64.exe", AppCategory.Neutral
				},
				{
					"jobctrl-uat.exe", AppCategory.Neutral
				},
			};
		}

		public UsefulLookup(Dictionary<string, AppCategory> lookup)
		{
			this.usefulLookup = new Dictionary<string, AppCategory>(lookup, StringComparer.InvariantCultureIgnoreCase);
		}

		public AppCategory GetCategory(string processName)
		{
			AppCategory category;
			if (processName == null) return AppCategory.Unknown;
			if (!usefulLookup.TryGetValue(processName, out category))
			{
				return AppCategory.Unknown;
			}

			return category;
		}
	}

	public static class EfficiencyHelper
	{
		private readonly static Dictionary<string, Efficiency> appLookup = new Dictionary<string, Efficiency>(StringComparer.OrdinalIgnoreCase)
			{
				{"devenv.exe", Efficiency.Productive},
				{"mstsc.exe", Efficiency.Productive},
				{"excel.exe", Efficiency.Productive},
				{"winword.exe", Efficiency.Productive},
				{"explorer.exe", Efficiency.Productive},
				{"ssms.exe", Efficiency.Productive},
				{"totalcmd64.exe", Efficiency.Productive},
				{"xcode.app", Efficiency.Productive},
				{"eclipse.app", Efficiency.Productive},
				{"powerpnt.exe", Efficiency.Productive},
				{"totalcmd.exe", Efficiency.Productive},
				{"vmware.exe", Efficiency.Productive},
				{"virtualbox.exe", Efficiency.Productive},
				{"thgw.exe", Efficiency.Productive},
				{"ddts.exe", Efficiency.Productive},
				{"notepad.exe", Efficiency.Productive},
				{"notepad++.exe", Efficiency.Productive},
				{"afterfx.exe", Efficiency.Productive},
				{"coreldrw.exe", Efficiency.Productive},
				{"photoshop.exe", Efficiency.Productive},
				{"acrord32.exe", Efficiency.Productive},
				{"jobctrl.exe", Efficiency.Productive},
				{"thunderbird.app", Efficiency.Productive},
				{"msmanager.exe", Efficiency.Productive},
				{"adobe premiere pro.exe", Efficiency.Productive},
				{"eclipse.exe", Efficiency.Productive},
				{"acad.exe", Efficiency.Productive},
				{"thg.exe", Efficiency.Productive},
				{"tmeditor.exe", Efficiency.Productive},
				{"tctjcl.exe", Efficiency.Productive},
				{"ios simulator.app", Efficiency.Productive},
				{"electrosmog.wpf.vshost.exe", Efficiency.Productive},
				{"jobctrl-uat.exe", Efficiency.Productive},
				{"callmixclient.exe", Efficiency.Productive},
				{"acrobat.exe", Efficiency.Productive},
				{"callmixclient.vshost.exe", Efficiency.Productive},
				{"loginwindow.app", Efficiency.Productive},
				{"cmd.exe", Efficiency.Productive},
				{"ccmanagecontrol.exe", Efficiency.Productive},
				{"baretail.exe", Efficiency.Productive},
				{"pycharm.exe", Efficiency.Productive},
				{"stikynot.exe", Efficiency.Productive},
				{"mspaint.exe", Efficiency.Productive},
				{"regexbuddy.exe", Efficiency.Productive},
				{"taskmgr.exe", Efficiency.Productive},
				{"jp2launcher.exe", Efficiency.Productive},
				{"tortoisehg.app", Efficiency.Productive},
				{"i_view32.exe", Efficiency.Productive},
				{"calc.exe", Efficiency.Productive},
				{"vpnui.exe", Efficiency.Productive},
				{"powershell_ise.exe", Efficiency.Productive},
				{"visio.exe", Efficiency.Productive},
				{"vpngui.exe", Efficiency.Productive},
				{"wcfstorm.exe", Efficiency.Productive},
				{"terminal.app", Efficiency.Productive},
				{"glcnd.exe", Efficiency.Productive},
				{"rc.exe", Efficiency.Productive},
				{"goldwave.exe", Efficiency.Productive},
				{"android studio.app", Efficiency.Productive},
				{"double commander.app", Efficiency.Productive},
				{"putty.exe", Efficiency.Productive},
				{"revit.exe", Efficiency.Productive},
				{"ilspy.exe", Efficiency.Productive},
				{"kdiff3.exe", Efficiency.Productive},
				{"microsoft remote desktop.app", Efficiency.Productive},
				{"sublime text.app", Efficiency.Productive},
				{"acdsee5.exe", Efficiency.Productive},
				{"mmc.exe", Efficiency.Productive},
				{"logexpert.exe", Efficiency.Productive},
				{"gitextensions.exe", Efficiency.Productive},
				{"inttalkccclient.exe", Efficiency.Productive},
				{"illustrator.exe", Efficiency.Productive},
				{"google chrome.app", Efficiency.Productive},
				{"viewer.exe", Efficiency.Productive},
				{"foxitreader.exe", Efficiency.Productive},
				{"acdseepro7.exe", Efficiency.Productive},
				{"jobctrl-dev.exe", Efficiency.Productive},
				{"sublime text 2.app", Efficiency.Productive},
				{"wcftestclient.exe", Efficiency.Productive},
				{"mysqlworkbench.exe", Efficiency.Productive},
				{"tcptrace.exe", Efficiency.Productive},
				{"mucommander.app", Efficiency.Productive},
				{"icszamla.exe", Efficiency.Productive},
				{"metspy.exe", Efficiency.Productive},
				{"provenmassetester.exe", Efficiency.Productive},
				{"electrosmog.wpf.exe", Efficiency.Productive},
				{"nds.exe", Efficiency.Productive},
				{"cctray.exe", Efficiency.Productive},
				{"finder.app", Efficiency.Productive},
				{"dcshelper.exe", Efficiency.Productive},
				{"raktar.exe", Efficiency.Productive},
				{"vpxclient.exe", Efficiency.Productive},
				{"camtasiastudio.exe", Efficiency.Productive},
				{"svcconfigeditor.exe", Efficiency.Productive},
				{"screensaverengine.app", Efficiency.Productive},
				{"balsamiq mockups.exe", Efficiency.Productive},
				{"bbqscreenclient2.exe", Efficiency.Productive},
				{"mdx.exe", Efficiency.Productive},
				{"hpiscnapp.exe", Efficiency.Productive},
				{"cfaphost.exe", Efficiency.Productive},
				{"fiddler.exe", Efficiency.Productive},
				{"3dsmax.exe", Efficiency.Productive},
				{"xnview.app", Efficiency.Productive},
				{"teamviewer.exe", Efficiency.Productive},
				{"doxywizard.exe", Efficiency.Productive},
				{"paintdotnet.exe", Efficiency.Productive},
				{"microsoft powerpoint.app", Efficiency.Productive},
				{"dtswizard.exe", Efficiency.Productive},
				{"pgadmin3.exe", Efficiency.Productive},
				{"ivrtreesrv.exe", Efficiency.Productive},
				{"megasync.exe", Efficiency.Productive},
				{"studio64.exe", Efficiency.Productive},
				{"calltester.exe", Efficiency.Productive},
				{"trgui.exe", Efficiency.Productive},
				{"snippingtool.exe", Efficiency.Productive},
				{"ccmanagecontrol_mkb.exe", Efficiency.Productive},
				{"camrecorder.exe", Efficiency.Productive},
				{"linqpad.exe", Efficiency.Productive},
				{"winscp.exe", Efficiency.Productive},
				{"mosaic.exe", Efficiency.Productive},
				{"memento.exe", Efficiency.Productive},
				{"linecounter.application.exe", Efficiency.Productive},
				{"starter.vshost.exe", Efficiency.Productive},
				{"sourcetree.app", Efficiency.Productive},
				{"dreamweaver.exe", Efficiency.Productive},
				{"ctireplyer.exe", Efficiency.Productive},
				{"vmwindow.exe", Efficiency.Productive},
				{"sqliteexpertpers.exe", Efficiency.Productive},
				{"customreportsender.vshost.exe", Efficiency.Productive},
				{"bizagimodeler.exe", Efficiency.Productive},
				{"ssmsee.exe", Efficiency.Productive},
				{"cfaphost.vshost.exe", Efficiency.Productive},
				{"inetmgr.exe", Efficiency.Productive},
				{"swgvc.exe", Efficiency.Productive},
				{"regedit.exe", Efficiency.Productive},
				{"lightshot.exe", Efficiency.Productive},
				{"sql sentry plan explorer.exe", Efficiency.Productive},
				{"ipsecc.exe", Efficiency.Productive},
				{"vpndownloader.exe", Efficiency.Productive},
				{"foxit reader.exe", Efficiency.Productive},
				{"app store.app", Efficiency.Productive},
				{"pspad.exe", Efficiency.Productive},
				{"procexp64.exe", Efficiency.Productive},
				{"photosapp.exe", Efficiency.Productive},
				{"markdownpad2.exe", Efficiency.Productive},
				{"sqlpro for sqlite.app", Efficiency.Productive},
				{"soapui-4.5.1.exe", Efficiency.Productive},
				{"android file transfer.app", Efficiency.Productive},
				{"ccapiserver.exe", Efficiency.Productive},
				{"sqlitemanager.app", Efficiency.Productive},
				{"reflector.exe", Efficiency.Productive},
				{"mysqlworkbench.app", Efficiency.Productive},
				{"wjview.exe", Efficiency.Productive},
				{"ois.exe", Efficiency.Productive},
				{"fnr.exe", Efficiency.Productive},
				{"metlistener.exe", Efficiency.Productive},
				{"tortoisemerge.exe", Efficiency.Productive},
				{"cegeditor.exe", Efficiency.Productive},
				{"dellsystemdetect.exe", Efficiency.Productive},
				{"sharpreader.exe", Efficiency.Productive},
				{"sharemouse.exe", Efficiency.Productive},
				{"ivrcontrollertester.vshost.exe", Efficiency.Productive},
				{"systemsettings.exe", Efficiency.Productive},
				{"ivrengine2console.vshost.exe", Efficiency.Productive},
				{"redgate.sqlcompare.ui.exe", Efficiency.Productive},
				{"expresso.exe", Efficiency.Productive},
				{"wswc.exe", Efficiency.Productive},
				{"onenote.exe", Efficiency.Productive},
				{"emulator64-x86.app", Efficiency.Productive},
				{"google drive.app", Efficiency.Productive},
				{"mbam.exe", Efficiency.Productive},
				{"pccompanion.exe", Efficiency.Productive},
				{"preview.app", Efficiency.Productive},
				{"regulator.exe", Efficiency.Productive},
				{"csrss.exe", Efficiency.Productive},
				{"tester.exe", Efficiency.Productive},
				{"vncviewer.exe", Efficiency.Productive},
				{"dropbox.app", Efficiency.Productive},
				{"dataminer.exe", Efficiency.Productive},
				{"redgate.sqldatacompare.ui.exe", Efficiency.Productive},
				{"upgradetool.vshost.exe", Efficiency.Productive},
				{"cfapp.exe", Efficiency.Productive},
				{"eszigno3.exe", Efficiency.Productive},
				{"winrar.exe", Efficiency.Productive},
				{"msaccess.exe", Efficiency.Productive},
				{"optionalfeatures.exe", Efficiency.Productive},
				{"kdiff3.app", Efficiency.Productive},
				{"defraggler64.exe", Efficiency.Productive},
				{"devicesetup.exe", Efficiency.Productive},
				{"databasedifferences.exe", Efficiency.Productive},
				{"számológép.app", Efficiency.Productive},
				{"dbcompare.exe", Efficiency.Productive},
				{"upgradetool.exe", Efficiency.Productive},
				{"reservationclient.vshost.exe", Efficiency.Productive},
				{"energy manager.exe", Efficiency.Productive},
				{"hpwucli.exe", Efficiency.Productive},
				{"ssdtsetup.exe", Efficiency.Productive},
				{"tortoiseproc.exe", Efficiency.Productive},
				{"hpscan.exe", Efficiency.Productive},
				{"skypesetup.exe", Efficiency.Productive},
				{"tmclientexecutable.exe", Efficiency.Productive},
				{"ivrsimulator.vshost.exe", Efficiency.Productive},
				{"tmproviderexecutable.exe", Efficiency.Productive},
				{"scenarioengine.exe", Efficiency.Productive},
				{"perfmon.exe", Efficiency.Productive},
				{"uimain.exe", Efficiency.Productive},
				{"datasecure.exe", Efficiency.Productive},
				{"pages.app", Efficiency.Productive},
				{"wireshark.exe", Efficiency.Productive},
				{"anymeeting.exe", Efficiency.Productive},
				{"wcfsvchost.exe", Efficiency.Productive},
				{"profiler.exe", Efficiency.Productive},
				{"tmactpar.exe", Efficiency.Productive},
				{"msdt.exe", Efficiency.Productive},
				{"jobctrl.app", Efficiency.Productive},
				{"mss.exe", Efficiency.Productive},
				{"lsc.exe", Efficiency.Productive},
				{"flashplayerplugin_17_0_0_134.exe", Efficiency.Productive},
				{"feedreader.exe", Efficiency.Productive},
				{"n360.exe", Efficiency.Productive},
				{"seccenter.exe", Efficiency.Productive},
				{"msascui.exe", Efficiency.Productive},
				{"useraccountbroker.exe", Efficiency.Productive},
				{"textedit.app", Efficiency.Productive},
				{"sascan.exe", Efficiency.Productive},
				{"touchcontrol.exe", Efficiency.Productive},
				{"metserver.exe", Efficiency.Productive},
				{"pickerhost.exe", Efficiency.Productive},
				{"googleupdate.exe", Efficiency.Productive},
				{"dexplore.exe", Efficiency.Productive},
				{"unzipbase64string.exe", Efficiency.Productive},
				{"gdbnt.exe", Efficiency.Productive},
				{"sufdesign.exe", Efficiency.Productive},
				{"ipseca.exe", Efficiency.Productive},
				{"reservationhost.vshost.exe", Efficiency.Productive},
				{"numbers.exe", Efficiency.Productive},
				{"flashplayerplugin_14_0_0_125.exe", Efficiency.Productive},
				{"clview.exe", Efficiency.Productive},
				{"numbers.app", Efficiency.Productive},
				{"webdev.webserver40.exe", Efficiency.Productive},
				{"usernotificationcenter.app", Efficiency.Productive},
				{"spritegenerator.exe", Efficiency.Productive},
				{"systempropertiesadvanced.exe", Efficiency.Productive},
				{"wisememoryoptimzer.exe", Efficiency.Productive},
				{"dsmusertask.exe", Efficiency.Productive},
				{"hpdia.exe", Efficiency.Productive},
				{"greenshot.exe", Efficiency.Productive},
				{"acdseeqvpro7.exe", Efficiency.Productive},
				{"wfica32.exe", Efficiency.Productive},
				{"toolbox.exe", Efficiency.Productive},
				{"reservationhost.exe", Efficiency.Productive},
				{"diagnosticoitau (2).exe", Efficiency.Productive},
				{"flashplayerplugin_16_0_0_305.exe", Efficiency.Productive},
				{"installnavi.exe", Efficiency.Productive},
				{"gimp-2.8.exe", Efficiency.Productive},
				{"inilister.exe", Efficiency.Productive},
				{"syncovery.exe", Efficiency.Productive},
				{"outlook.exe", Efficiency.Neutral},
				{"skype.exe", Efficiency.Neutral},
				{"javaw.exe", Efficiency.Neutral},
				{"viber.exe", Efficiency.Neutral},
				{"dllhost.exe", Efficiency.Neutral},
				{"dwm.exe", Efficiency.Neutral},
				{"microsoft outlook.app", Efficiency.Neutral},
				{"wwahost.exe", Efficiency.Neutral},
				{"skype.app", Efficiency.Neutral},
				{"rundll32.exe", Efficiency.Neutral},
				{"wlmail.exe", Efficiency.Neutral},
				{"avpui.exe", Efficiency.Neutral},
				{"msiexec.exe", Efficiency.Neutral},
				{"werfault.exe", Efficiency.Neutral},
				{"avastui.exe", Efficiency.Neutral},
				{"tct.ticketing.recruitment.vshost.exe", Efficiency.Neutral},
				{"setup.exe", Efficiency.Neutral},
				{"sidebar.exe", Efficiency.Neutral},
				{"gta_sa.exe", Efficiency.Neutral},
				{"atmgr.exe", Efficiency.Neutral},
				{"winhlp32.exe", Efficiency.Neutral},
				{"hpscanandcapture.exe", Efficiency.Neutral},
				{"backup_agent.exe", Efficiency.Neutral},
				{"helppane.exe", Efficiency.Neutral},
				{"avgui.exe", Efficiency.Neutral},
				{"foobar2000.exe", Efficiency.Neutral},
				{"tvsukernel.exe", Efficiency.Neutral},
				{"nw.exe", Efficiency.Neutral},
				{"hpqwrg.exe", Efficiency.Neutral},
				{"chrome.exe", Efficiency.NonProductive},
				{"iexplore.exe", Efficiency.NonProductive},
				{"firefox.exe", Efficiency.NonProductive},
				{"vmplayer.exe", Efficiency.NonProductive},
				{"maxthon.exe", Efficiency.NonProductive},
				{"thunderbird.exe", Efficiency.NonProductive},
				{"wmplayer.exe", Efficiency.NonProductive},
				{"vlc.exe", Efficiency.NonProductive},
				{"winamp.exe", Efficiency.NonProductive},
				{"itunes.exe", Efficiency.NonProductive},
				{"quicktimeplayer.exe", Efficiency.NonProductive},
				{"spotify.exe", Efficiency.NonProductive},
				{"vmsal.exe", Efficiency.NonProductive},
				{"utorrent.exe", Efficiency.NonProductive},
				{"bsplayer.exe", Efficiency.NonProductive},
				{"safari.exe", Efficiency.NonProductive},
				{"adobe air installer.exe", Efficiency.NonProductive},
				{"itunes.app", Efficiency.NonProductive},
				{"adobe air updater.exe", Efficiency.NonProductive},
			};
		private readonly static Dictionary<string, Efficiency> urlLookup = new Dictionary<string, Efficiency>(StringComparer.OrdinalIgnoreCase) {
				{"br.jobctrl.com", Efficiency.Productive},
				{"stackoverflow.com", Efficiency.Productive},
				{"www.google.hu", Efficiency.Productive},
				{"localhost:12849", Efficiency.Productive},
				{"support.hosted-contact-center.hu", Efficiency.Productive},
				{"www.google.com", Efficiency.Productive},
				{"webivrdev01.tct.local", Efficiency.Productive},
				{"localhost:9509", Efficiency.Productive},
				{"crm.jobctrl.com", Efficiency.Productive},
				{"docs.google.com", Efficiency.Productive},
				{"msdn.microsoft.com", Efficiency.Productive},
				{"localhost", Efficiency.Productive},
				{"localhost:62400", Efficiency.Productive},
				{"www.linkedin.com", Efficiency.Productive},
				{"ibausrv01:800", Efficiency.Productive},
				{"localhost:2182", Efficiency.Productive},
				{"mvc.backoffice.dev.jobctrl.net", Efficiency.Productive},
				{"drive.google.com", Efficiency.Productive},
				{"dev.jobctrl.net", Efficiency.Productive},
				{"localhost:6827", Efficiency.Productive},
				{"stage.jobctrl.net", Efficiency.Productive},
				{"vmw702.tct.local", Efficiency.Productive},
				{"app.box.com", Efficiency.Productive},
				{"localhost:12069", Efficiency.Productive},
				{"github.com", Efficiency.Productive},
				{"jobctrl.net", Efficiency.Productive},
				{"www.google.com.br", Efficiency.Productive},
				{"fgmccapp1.fogaz.hu", Efficiency.Productive},
				{"newcc:12069", Efficiency.Productive},
				{"fgmccappt.fogaz.hu", Efficiency.Productive},
				{"localhost:5001", Efficiency.Productive},
				{"local.jobctrl.net", Efficiency.Productive},
				{"blogs.msdn.com", Efficiency.Productive},
				{"roslyn.codeplex.com", Efficiency.Productive},
				{"regexhero.net", Efficiency.Productive},
				{"prodapp065:8080", Efficiency.Productive},
				{"accounts.google.com", Efficiency.Productive},
				{"localhost:6645", Efficiency.Productive},
				{"play.google.com", Efficiency.Productive},
				{"dev.wiki.local", Efficiency.Productive},
				{"vimeo.com", Efficiency.Productive},
				{"vmw701.tct.local", Efficiency.Productive},
				{"showcase.jobctrl.com", Efficiency.Productive},
				{"trac.pjsip.org", Efficiency.Productive},
				{"devsrv01", Efficiency.Productive},
				{"jcapp1:222", Efficiency.Productive},
				{"localhost:3000", Efficiency.Productive},
				{"www.rememberthemilk.com", Efficiency.Productive},
				{"www.lampabolt.com", Efficiency.Productive},
				{"translate.google.com.br", Efficiency.Productive},
				{"translate.google.hu", Efficiency.Productive},
				{"en.wikipedia.org", Efficiency.Productive},
				{"translate.google.com", Efficiency.Productive},
				{"tablesorter.com", Efficiency.Productive},
				{"eptk.fair.gov.hu", Efficiency.Productive},
				{"www.booking.com", Efficiency.Productive},
				{"admin.google.com", Efficiency.Productive},
				{"tct_data", Efficiency.Productive},
				{"trello.com", Efficiency.Productive},
				{"ec.europa.eu", Efficiency.Productive},
				{"localhost:1626", Efficiency.Productive},
				{"help.jobctrl.com", Efficiency.Productive},
				{"www.w3schools.com", Efficiency.Productive},
				{"prodapp076.garancia.hu", Efficiency.Productive},
				{"tct.hu", Efficiency.Productive},
				{"jcapp2:222", Efficiency.Productive},
				{"www.codeproject.com", Efficiency.Productive},
				{"talkgadget.google.com", Efficiency.Productive},
				{"www.hwsw.hu", Efficiency.Productive},
				{"social.msdn.microsoft.com", Efficiency.Productive},
				{"callmixtst.tct.local:8888", Efficiency.Productive},
				{"fgmccsql1", Efficiency.Productive},
				{"incidentmanager.jobctrl.com", Efficiency.Productive},
				{"ibausrv01.tct.local:800", Efficiency.Productive},
				{"localhost:5000", Efficiency.Productive},
				{"code.google.com", Efficiency.Productive},
				{"devapp004.garancia.hu", Efficiency.Productive},
				{"support2.microsoft.com", Efficiency.Productive},
				{"dev.spirateam.local", Efficiency.Productive},
				{"www.cupidos.hu", Efficiency.Productive},
				{"leetcode.com", Efficiency.Productive},
				{"developers.google.com", Efficiency.Productive},
				{"developer.android.com", Efficiency.Productive},
				{"developer.apple.com", Efficiency.Productive},
				{"docs.angularjs.org", Efficiency.Productive},
				{"hu.wikipedia.org", Efficiency.Productive},
				{"backoffice.jobctrl.com:4433", Efficiency.Productive},
				{"jobctrl.net:83", Efficiency.Productive},
				{"217.79.135.10", Efficiency.Productive},
				{"support.google.com", Efficiency.Productive},
				{"devcti.tct.local", Efficiency.Productive},
				{"developer.chrome.com", Efficiency.Productive},
				{"www.xianwenchen.com", Efficiency.Productive},
				{"pcottle.github.io", Efficiency.Productive},
				{"technet.microsoft.com", Efficiency.Productive},
				{"antonioleiva.com", Efficiency.Productive},
				{"172.22.1.21", Efficiency.Productive},
				{"tctnagios", Efficiency.Productive},
				{"www.citrix.com", Efficiency.Productive},
				{"sites.google.com", Efficiency.Productive},
				{"jobctrl.net:3000", Efficiency.Productive},
				{"www.tct.hu", Efficiency.Productive},
				{"www.asp.net", Efficiency.Productive},
				{"tctapp1", Efficiency.Productive},
				{"aoc-bp.aegon.hu", Efficiency.Productive},
				{"api.jqueryui.com", Efficiency.Productive},
				{"szotar.sztaki.hu", Efficiency.Productive},
				{"www.mycallmix.com", Efficiency.Productive},
				{"api.jquery.com", Efficiency.Productive},
				{"www.cplusplus.com", Efficiency.Productive},
				{"regex101.com", Efficiency.Productive},
				{"vmxp02.tct.local:8080", Efficiency.Productive},
				{"www.dell.com", Efficiency.Productive},
				{"trinity.interware.hu", Efficiency.Productive},
				{"appleblog.blog.hu", Efficiency.Productive},
				{"www.slideshare.net", Efficiency.Productive},
				{"developer.mozilla.org", Efficiency.Productive},
				{"tbaosapsql2", Efficiency.Productive},
				{"backoffice-br.jobctrl.com", Efficiency.Productive},
				{"web.hosted-contact-center.hu", Efficiency.Productive},
				{"devsrv01:8000", Efficiency.Productive},
				{"bitbucket.org", Efficiency.Productive},
				{"localhost:7893", Efficiency.Productive},
				{"mercurial.selenic.com", Efficiency.Productive},
				{"virtualoso-voicecenter.t-systems.hu", Efficiency.Productive},
				{"info.foldhivatal.hu", Efficiency.Productive},
				{"soffice.bin", Efficiency.Productive},
				{"www.klm.com", Efficiency.Productive},
				{"hu.123rf.com", Efficiency.Productive},
				{"developer.linkedin.com", Efficiency.Productive},
				{"www.apple.com", Efficiency.Productive},
				{"en.community.dell.com", Efficiency.Productive},
				{"jsfiddle.net", Efficiency.Productive},
				{"ux.stackexchange.com", Efficiency.Productive},
				{"wfm.elmu.hu", Efficiency.Productive},
				{"ibausrv01:98", Efficiency.Productive},
				{"www.msn.com", Efficiency.Productive},
				{"developers.facebook.com", Efficiency.Productive},
				{"forums.asp.net", Efficiency.Productive},
				{"www.testepower.com.br", Efficiency.Productive},
				{"groups.google.com", Efficiency.Productive},
				{"meetings.webex.com", Efficiency.Productive},
				{"wwwendt.de", Efficiency.Productive},
				{"secure.booking.com", Efficiency.Productive},
				{"uxmyths.com", Efficiency.Productive},
				{"sandbox.jobctrl.com", Efficiency.Productive},
				{"localhost:2205", Efficiency.Productive},
				{"localhost:83", Efficiency.Productive},
				{"virtual-call-center.hu", Efficiency.Productive},
				{"superuser.com", Efficiency.Productive},
				{"www.befective.com", Efficiency.Productive},
				{"jqueryui.com", Efficiency.Productive},
				{"static.googleusercontent.com", Efficiency.Productive},
				{"www.airfrance.hu", Efficiency.Productive},
				{"www.pjsip.org", Efficiency.Productive},
				{"tortoisehg.bitbucket.org", Efficiency.Productive},
				{"vpn.fogaz.hu", Efficiency.Productive},
				{"pcworld.hu", Efficiency.Productive},
				{"www.solvusoft.com", Efficiency.Productive},
				{"192.168.1.1", Efficiency.Productive},
				{"matplotlib.org", Efficiency.Productive},
				{"www.regular-expressions.info", Efficiency.Productive},
				{"www.sqlsaturday.com", Efficiency.Productive},
				{"online.telenor.hu", Efficiency.Productive},
				{"test-virtualoso-voicecenter.t-systems.hu", Efficiency.Productive},
				{"jobctrl.elmu.hu", Efficiency.Productive},
				{"www.microsoft.com", Efficiency.Productive},
				{"mrccapp5", Efficiency.Productive},
				{"www.otpbankdirekt.hu", Efficiency.Productive},
				{"aapj.bb.com.br", Efficiency.Productive},
				{"www.socialmediatoday.com", Efficiency.Productive},
				{"www.bing.com", Efficiency.Productive},
				{"www.utvonalterv.hu", Efficiency.Productive},
				{"www.edreams.com", Efficiency.Productive},
				{"ibausrv01:810", Efficiency.Productive},
				{"simet.nic.br", Efficiency.Productive},
				{"www.tutorialspoint.com", Efficiency.Productive},
				{"devproconnections.com", Efficiency.Productive},
				{"www.virtuosoft.eu", Efficiency.Productive},
				{"backoffice.br.jobctrl.com", Efficiency.Productive},
				{"ibausrv01:85", Efficiency.Productive},
				{"www.jqueryscript.net", Efficiency.Productive},
				{"ugyfelkapu.graphax.hu", Efficiency.Productive},
				{"pt.wikipedia.org", Efficiency.Productive},
				{"www.cs.dartmouth.edu", Efficiency.Productive},
				{"canvasjs.com", Efficiency.Productive},
				{"file.tavinfo.hu", Efficiency.Productive},
				{"help.linkedin.com", Efficiency.Productive},
				{"www.c-sharpcorner.com", Efficiency.Productive},
				{"backoffice.jobctrl.com", Efficiency.Productive},
				{"answers.microsoft.com", Efficiency.Productive},
				{"www.geeksforgeeks.org", Efficiency.Productive},
				{"stores.office.com", Efficiency.Productive},
				{"support.office.com", Efficiency.Productive},
				{"web.whatsapp.com", Efficiency.Productive},
				{"filedropjs.org", Efficiency.Productive},
				{"possiblemobile.com", Efficiency.Productive},
				{"www.notebookcheck.net", Efficiency.Productive},
				{"mobilarena.hu", Efficiency.Productive},
				{"exceltactics.com", Efficiency.Productive},
				{"localhost:1815", Efficiency.Productive},
				{"prodapp077.garancia.hu", Efficiency.Productive},
				{"logging.apache.org", Efficiency.Productive},
				{"www.stack.nl", Efficiency.Productive},
				{"workplace.stackexchange.com", Efficiency.Productive},
				{"www.t-systems.hu", Efficiency.Productive},
				{"azure.microsoft.com", Efficiency.Productive},
				{"cloud.locaweb.com.br", Efficiency.Productive},
				{"jobctrl.telekom.intra", Efficiency.Productive},
				{"www.processlibrary.com", Efficiency.Productive},
				{"clican-pluto.googlecode.com", Efficiency.Productive},
				{"code.msdn.microsoft.com", Efficiency.Productive},
				{"www.protocall.hu", Efficiency.Productive},
				{"www.mssqltips.com", Efficiency.Productive},
				{"tvvoip1", Efficiency.Productive},
				{"www.duran.hu", Efficiency.Productive},
				{"ng-learn.org", Efficiency.Productive},
				{"net.jogtar.hu", Efficiency.Productive},
				{"www.arukereso.hu", Efficiency.Productive},
				{"iconizer.net", Efficiency.Productive},
				{"extra.unicreditbank.hu", Efficiency.Productive},
				{"www.sql-server-helper.com", Efficiency.Productive},
				{"www.surveymonkey.net", Efficiency.Productive},
				{"wpf.codeplex.com", Efficiency.Productive},
				{"192.168.1.220", Efficiency.Productive},
				{"comunidade.itforum365.com.br", Efficiency.Productive},
				{"doc-00-ao-apps-viewer.googleusercontent.com", Efficiency.Productive},
				{"www.dialogic.com", Efficiency.Productive},
				{"www.airbnb.com.br", Efficiency.Productive},
				{"www.aqua.hu", Efficiency.Productive},
				{"172.22.1.43:5903", Efficiency.Productive},
				{"www.rubular.com", Efficiency.Productive},
				{"www.baguete.com.br", Efficiency.Productive},
				{"tman01:9443", Efficiency.Productive},
				{"serverfault.com", Efficiency.Productive},
				{"www.wikihow.com", Efficiency.Productive},
				{"mrccapp5:8082", Efficiency.Productive},
				{"www.hackerrank.com", Efficiency.Productive},
				{"physics.stackexchange.com", Efficiency.Productive},
				{"www.howtogeek.com", Efficiency.Productive},
				{"support.microsoft.com", Efficiency.Productive},
				{"172.22.1.140", Efficiency.Productive},
				{"www.bbmc.co.kr", Efficiency.Productive},
				{"www.google.com.mx", Efficiency.Productive},
				{"localhost:22870", Efficiency.Productive},
				{"www.erichynds.com", Efficiency.Productive},
				{"doc-0g-80-apps-viewer.googleusercontent.com", Efficiency.Productive},
				{"worldbuilding.stackexchange.com", Efficiency.Productive},
				{"mrccapp3", Efficiency.Productive},
				{"www.jackrabbitmobile.com", Efficiency.Productive},
				{"www.databasejournal.com", Efficiency.Productive},
				{"www.gyakorikerdesek.hu", Efficiency.Productive},
				{"helpdesk.fundamenta.hu", Efficiency.Productive},
				{"dailyjs.com", Efficiency.Productive},
				{"omaralzabir.com", Efficiency.Productive},
				{"www.dotnetcurry.com", Efficiency.Productive},
				{"doc-0s-80-apps-viewer.googleusercontent.com", Efficiency.Productive},
				{"www.abplusz.hu", Efficiency.Productive},
				{"iconmonstr.com", Efficiency.Productive},
				{"www.mozilla.org", Efficiency.Productive},
				{"store.citrix.com", Efficiency.Productive},
				{"www.postgresql.org", Efficiency.Productive},
				{"fgmccsql1.fogaz.hu", Efficiency.Productive},
				{"hgbook.red-bean.com", Efficiency.Productive},
				{"www.bkk.hu", Efficiency.Productive},
				{"www.pinvoke.net", Efficiency.Productive},
				{"www.google.co.kr", Efficiency.Productive},
				{"www.partneringkonferencia.hu", Efficiency.Productive},
				{"www.netcombo.com.br", Efficiency.Productive},
				{"www.speedtest.net", Efficiency.Productive},
				{"tctnas:8080", Efficiency.Productive},
				{"codeblog.jonskeet.uk", Efficiency.Productive},
				{"virtualoso-fax2email.t-systems.hu", Efficiency.Productive},
				{"www.meetup.com", Efficiency.Productive},
				{"prohardver.hu", Efficiency.Productive},
				{"www.wcftutorial.net", Efficiency.Productive},
				{"www.telerik.com", Efficiency.Productive},
				{"www.itpeopleone.com", Efficiency.Productive},
				{"share.szb640.duckdns.org", Efficiency.NonProductive},
				{"bxslider.com", Efficiency.Productive},
				{"wiki.jenkins-ci.org", Efficiency.Productive},
				{"www.notebook.hu", Efficiency.Productive},
				{"www.123rf.com", Efficiency.Productive},
				{"caret.co", Efficiency.Productive},
				{"citrix2008r2-test.tct.local", Efficiency.Productive},
				{"www.nudoq.org", Efficiency.Productive},
				{"console.developers.google.com", Efficiency.Productive},
				{"www.smtpcorp.com", Efficiency.Productive},
				{"www.telenor.hu", Efficiency.Productive},
				{"jsbin.com", Efficiency.Productive},
				{"prodapp065.garancia.hu:8080", Efficiency.Productive},
				{"belepes.telekom.hu", Efficiency.Productive},
				{"www.timeanddate.com", Efficiency.Productive},
				{"www.acate.com.br", Efficiency.Productive},
				{"weblogs.asp.net", Efficiency.Productive},
				{"www.9fruits.com", Efficiency.Productive},
				{"www.search.ask.com", Efficiency.Productive},
				{"keep.google.com", Efficiency.Productive},
				{"localhost:8732", Efficiency.Productive},
				{"www.file.net", Efficiency.Productive},
				{"www.salpinx.com.br", Efficiency.Productive},
				{"flylib.com", Efficiency.Productive},
				{"whois.domaintools.com", Efficiency.Productive},
				{"www.latlong.net", Efficiency.Productive},
				{"support.hp.com", Efficiency.Productive},
				{"kdbe-cti.kdb.hu", Efficiency.Productive},
				{"prodcenter.dialogic.com", Efficiency.Productive},
				{"www.asus.com", Efficiency.Productive},
				{"www.falconi.com", Efficiency.Productive},
				{"www.ciasc.sc.gov.br", Efficiency.Productive},
				{"www.e-cegjegyzek.hu", Efficiency.Productive},
				{"www.dropbox.com", Efficiency.Productive},
				{"www.computerhope.com", Efficiency.Productive},
				{"player.vimeo.com", Efficiency.Productive},
				{"www.fogaz.hu", Efficiency.Productive},
				{"checkin.si.amadeus.net", Efficiency.Productive},
				{"palyazat.gov.hu", Efficiency.Productive},
				{"jakewharton.com", Efficiency.Productive},
				{"ibausrv01.tct.local:810", Efficiency.Productive},
				{"pcforum.hu", Efficiency.Productive},
				{"www.newegg.com", Efficiency.Productive},
				{"social.technet.microsoft.com", Efficiency.Productive},
				{"pubs.vmware.com", Efficiency.Productive},
				{"www.cisco.com", Efficiency.Productive},
				{"www.uangel.com", Efficiency.Productive},
				{"www.msoutlook.info", Efficiency.Productive},
				{"od.jp2.elmu.hu", Efficiency.Productive},
				{"users.telenet.be", Efficiency.Productive},
				{"www.join.me", Efficiency.Productive},
				{"www.telekom.hu", Efficiency.Productive},
				{"devsrv01.tct.local:7100", Efficiency.Productive},
				{"www.royjacobs.org", Efficiency.Productive},
				{"mvccapp7.pgsm.hu", Efficiency.Productive},
				{"www.runtastic.com", Efficiency.Productive},
				{"fgmccapp1", Efficiency.Productive},
				{"backbonejs.org", Efficiency.Productive},
				{"www.doosaninfracore.com", Efficiency.Productive},
				{"www.raywenderlich.com", Efficiency.Productive},
				{"uxmag.com", Efficiency.Productive},
				{"compra.avianca.com", Efficiency.Productive},
				{"www.enom.com", Efficiency.Productive},
				{"doc-04-80-apps-viewer.googleusercontent.com", Efficiency.Productive},
				{"app.mighty.ws", Efficiency.Productive},
				{"fgmccsql2", Efficiency.Productive},
				{"www.dnswatch.info", Efficiency.Productive},
				{"scriptular.com", Efficiency.Productive},
				{"english.stackexchange.com", Efficiency.Productive},
				{"pt.floorplanner.com", Efficiency.Productive},
				{"www.catho.com.br", Efficiency.Productive},
				{"test-virtualoso-fax2email.t-systems.hu", Efficiency.Productive},
				{"notebookstore.hu", Efficiency.Productive},
				{"kdbe-cti2.kdb.hu", Efficiency.Productive},
				{"www.postseek.com", Efficiency.Productive},
				{"ios-blog.co.uk", Efficiency.Productive},
				{"www.windows8downloads.com", Efficiency.Productive},
				{"passwordreset.telekom.hu", Efficiency.Productive},
				{"www.szamlazz.hu", Efficiency.Productive},
				{"try.crashlytics.com", Efficiency.Productive},
				{"qa-uk-pcs-misco.systemax.com", Efficiency.Productive},
				{"programmers.stackexchange.com", Efficiency.Productive},
				{"slashdot.org", Efficiency.Productive},
				{"www.clipconverter.cc", Efficiency.Productive},
				{"trofeagrill.com", Efficiency.Productive},
				{"localhost:37236", Efficiency.Productive},
				{"futar.bkk.hu", Efficiency.Productive},
				{"httpd.apache.org", Efficiency.Productive},
				{"gist.github.com", Efficiency.Productive},
				{"www.cultofandroid.com", Efficiency.Productive},
				{"admin.forpsi.hu", Efficiency.Productive},
				{"lifehacks.stackexchange.com", Efficiency.Productive},
				{"support.sonymobile.com", Efficiency.Productive},
				{"www.hrportal.hu", Efficiency.Productive},
				{"ibau.hu", Efficiency.Productive},
				{"www.gps-coordinates.net", Efficiency.Productive},
				{"www.paypal.com", Efficiency.Productive},
				{"nutshell.prezi.com", Efficiency.Productive},
				{"plot.ly", Efficiency.Productive},
				{"www.mbaexcel.com", Efficiency.Productive},
				{"doc-0o-80-apps-viewer.googleusercontent.com", Efficiency.Productive},
				{"modernuiicons.com", Efficiency.Productive},
				{"voip_trm_web:8083", Efficiency.Productive},
				{"pt.slideshare.net", Efficiency.Productive},
				{"doc-0c-ao-apps-viewer.googleusercontent.com", Efficiency.Productive},
				{"www.opensips.org", Efficiency.Productive},
				{"screen.bbqdroid.org", Efficiency.Productive},
				{"www.samsung.com", Efficiency.Productive},
				{"webivrdev01", Efficiency.Productive},
				{"www.capturedata.com", Efficiency.Productive},
				{"hup.hu", Efficiency.Productive},
				{"haacked.com", Efficiency.Productive},
				{"dev.chromium.org", Efficiency.Productive},
				{"www.pcmag.com", Efficiency.Productive},
				{"ascensus.com.br", Efficiency.Productive},
				{"maps.google.com", Efficiency.Productive},
				{"support.viber.com", Efficiency.Productive},
				{"doc-14-80-apps-viewer.googleusercontent.com", Efficiency.Productive},
				{"blog.jetbrains.com", Efficiency.Productive},
				{"doc-10-ao-apps-viewer.googleusercontent.com", Efficiency.Productive},
				{"odetocode.com", Efficiency.Productive},
				{"localhost:3218", Efficiency.Productive},
				{"www.suntech.com.br", Efficiency.Productive},
				{"sourceforge.net", Efficiency.Productive},
				{"www.yiiframework.com", Efficiency.Productive},
				{"fgmccapp2.fogaz.hu", Efficiency.Productive},
				{"mycallmix.com", Efficiency.Productive},
				{"lists.freeswitch.org", Efficiency.Productive},
				{"www.utdij.hu", Efficiency.Productive},
				{"mathiasbynens.be", Efficiency.Productive},
				{"www.stevefenton.co.uk", Efficiency.Productive},
				{"entityframework.codeplex.com", Efficiency.Productive},
				{"wiki.python.org", Efficiency.Productive},
				{"www.extendoffice.com", Efficiency.Productive},
				{"fgmccapp1:3499", Efficiency.Productive},
				{"www.wcfstorm.com", Efficiency.Productive},
				{"localhost:2000", Efficiency.Productive},
				{"mac.softpedia.com", Efficiency.Productive},
				{"www.sqlteam.com", Efficiency.Productive},
				{"news.microsoft.com", Efficiency.Productive},
				{"products.office.com", Efficiency.Productive},
				{"support.lenovo.com", Efficiency.Productive},
				{"www.sitepoint.com", Efficiency.Productive},
				{"gls-group.eu", Efficiency.Productive},
				{"www.dreherzrt.hu", Efficiency.Productive},
				{"devapp004", Efficiency.Productive},
				{"iphonekozosseg.hu", Efficiency.Productive},
				{"blog.sqlauthority.com", Efficiency.Productive},
				{"sscheroes.com", Efficiency.Productive},
				{"doxygen.10944.n7.nabble.com", Efficiency.Productive},
				{"forum.xda-developers.com", Efficiency.Productive},
				{"www.nngroup.com", Efficiency.Productive},
				{"www.tiobe.com", Efficiency.Productive},
				{"www.viber.com", Efficiency.Productive},
				{"imapnet.codeplex.com", Efficiency.Productive},
				{"doc-10-80-apps-viewer.googleusercontent.com", Efficiency.Productive},
				{"www.sqlpass.org", Efficiency.Productive},
				{"forums.codeguru.com", Efficiency.Productive},
				{"research.microsoft.com", Efficiency.Productive},
				{"backoffice.jobctrl.elmu.hu", Efficiency.Productive},
				{"sqlblog.com", Efficiency.Productive},
				{"www.jsoneditoronline.org", Efficiency.Productive},
				{"executive.mit.edu", Efficiency.Productive},
				{"css-tricks.com", Efficiency.Productive},
				{"www.adweek.com", Efficiency.Productive},
				{"www.argep.hu", Efficiency.Productive},
				{"www.kelleher-international.com", Efficiency.Productive},
				{"unix.stackexchange.com", Efficiency.Productive},
				{"wiki.vtiger.com", Efficiency.Productive},
				{"ccappl2:2222", Efficiency.Productive},
				{"shop.lenovo.com", Efficiency.Productive},
				{"security.stackexchange.com", Efficiency.Productive},
				{"www.vtiger.com", Efficiency.Productive},
				{"217.79.135.3:8083", Efficiency.Productive},
				{"pentelesolar.hu", Efficiency.Productive},
				{"travel.stackexchange.com", Efficiency.Productive},
				{"www.epochtimes.com.br", Efficiency.Productive},
				{"doc-0k-80-apps-viewer.googleusercontent.com", Efficiency.Productive},
				{"ekiga.im", Efficiency.Productive},
				{"www.htcdev.com", Efficiency.Productive},
				{"www.twilio.com", Efficiency.Productive},
				{"backoffice.stage.jobctrl.net", Efficiency.Productive},
				{"doc-00-80-apps-viewer.googleusercontent.com", Efficiency.Productive},
				{"help.adobe.com", Efficiency.Productive},
				{"www.thefreedictionary.com", Efficiency.Productive},
				{"jobctrl.net:2000", Efficiency.Productive},
				{"w3facility.org", Efficiency.Productive},
				{"thestack.com", Efficiency.Productive},
				{"itforum365.com.br", Efficiency.Productive},
				{"store.apple.com", Efficiency.Productive},
				{"www.lan.com", Efficiency.Productive},
				{"www.codersgrid.com", Efficiency.Productive},
				{"pt.bab.la", Efficiency.Productive},
				{"www.thewindowsclub.com", Efficiency.Productive},
				{"www.joystreet.com.br", Efficiency.Productive},
				{"louisem.com", Efficiency.Productive},
				{"www.regexp.com.br", Efficiency.Productive},
				{"java.com", Efficiency.Productive},
				{"forums.motorola.com", Efficiency.Productive},
				{"qapcsmisco.systemax.com", Efficiency.Productive},
				{"techkalauz.hu", Efficiency.Productive},
				{"www.sysmap.com.br", Efficiency.Productive},
				{"dlcdnet.asus.com", Efficiency.Productive},
				{"www.kreativ.hu", Efficiency.Productive},
				{"www.ng-newsletter.com", Efficiency.Productive},
				{"www.yearofmoo.com", Efficiency.Productive},
				{"217.79.135.1:3499", Efficiency.Productive},
				{"tools.cisco.com", Efficiency.Productive},
				{"www.nng.com", Efficiency.Productive},
				{"ark.intel.com", Efficiency.Productive},
				{"data:image", Efficiency.Productive},
				{"prog.hu", Efficiency.Productive},
				{"www.julien-manici.com", Efficiency.Productive},
				{"bugzilla.mozilla.org", Efficiency.Productive},
				{"www.getonsip.com", Efficiency.Productive},
				{"mixpanel.com", Efficiency.Productive},
				{"cisco.pearsoncred.com", Efficiency.Productive},
				{"www.nuget.org", Efficiency.Productive},
				{"erraticdev.blogspot.hu", Efficiency.Productive},
				{"www.zdnet.com", Efficiency.Productive},
				{"kneel", Efficiency.Productive},
				{"b2data.hu", Efficiency.Productive},
				{"selenic.com", Efficiency.Productive},
				{"photoswipe.com", Efficiency.Productive},
				{"myaccount.google.com", Efficiency.Productive},
				{"stefanoricciardi.com", Efficiency.Productive},
				{"gestaoar.certisign.com.br", Efficiency.Productive},
				{"tctapp1:82", Efficiency.Productive},
				{"leftshift.io", Efficiency.Productive},
				{"www.gsmarena.com", Efficiency.Productive},
				{"jsonlint.com", Efficiency.Productive},
				{"coding.abel.nu", Efficiency.Productive},
				{"learnswfobject.com", Efficiency.Productive},
				{"trvoip1", Efficiency.Productive},
				{"www.martinelli.adv.br", Efficiency.Productive},
				{"windows.microsoft.com", Efficiency.Productive},
				{"checkin.avianca.com", Efficiency.Productive},
				{"www.bigresource.com", Efficiency.Productive},
				{"www.sqlservercentral.com", Efficiency.Productive},
				{"tman01:7074", Efficiency.Productive},
				{"brazil.kaspersky.com", Efficiency.Productive},
				{"www.ibausrv01.com:800", Efficiency.Productive},
				{"creatingpersonalflow.com", Efficiency.Productive},
				{"dev.mysql.com", Efficiency.Productive},
				{"dotnetcodr.com", Efficiency.Productive},
				{"underscorejs.org", Efficiency.Productive},
				{"unitywcf.codeplex.com", Efficiency.Productive},
				{"www.istockphoto.com", Efficiency.Productive},
				{"mail.google.com", Efficiency.Neutral},
				{"jobctrl.com", Efficiency.Neutral},
				{"fc8aca3.rbf", Efficiency.Neutral},
				{"www.gmail.com", Efficiency.Neutral},
				{"inbox.google.com", Efficiency.Neutral},
				{"1591ca65.rbf", Efficiency.Neutral},
				{"exchange.piholding.hu", Efficiency.Neutral},
				{"uk-mg42.mail.yahoo.com", Efficiency.Neutral},
				{"xmail.telenor.hu", Efficiency.Neutral},
				{"konica.tct.local", Efficiency.Neutral},
				{"gmail.com", Efficiency.Neutral},
				{"login.live.com", Efficiency.Neutral},
				{"plus.google.com", Efficiency.NonProductive},
				{"arc.sze.hu", Efficiency.NonProductive},
				{"www.facebook.com", Efficiency.NonProductive},
				{"www.youtube.com", Efficiency.NonProductive},
				{"itunesconnect.apple.com", Efficiency.NonProductive},
				{"fabric.io", Efficiency.NonProductive},
				{"szadaandras.de.quickconnect.to", Efficiency.NonProductive},
				{"wwws.minhaseconomias.com.br", Efficiency.NonProductive},
				{"chrome.google.com", Efficiency.NonProductive},
				{"book.tam.com.br", Efficiency.NonProductive},
				{"olx.hu", Efficiency.NonProductive},
				{"www.valor.com.br", Efficiency.NonProductive},
				{"nfse.recife.pe.gov.br", Efficiency.NonProductive},
				{"www.cib.hu", Efficiency.NonProductive},
				{"444.hu", Efficiency.NonProductive},
				{"plnkr.co", Efficiency.NonProductive},
				{"www.update1.hu", Efficiency.NonProductive},
				{"www.priceline.com", Efficiency.NonProductive},
				{"bankline.itau.com.br", Efficiency.NonProductive},
				{"online.keb.co.kr", Efficiency.NonProductive},
				{"www.jofogas.hu", Efficiency.NonProductive},
				{"ww82.itau.com.br", Efficiency.NonProductive},
				{"www.idokep.hu", Efficiency.NonProductive},
				{"neszeszer.blog.hu", Efficiency.NonProductive},
				{"banklineplus.itau.com.br", Efficiency.NonProductive},
				{"www.brutaldeluxe.fr", Efficiency.NonProductive},
				{"ibank.cib.hu", Efficiency.NonProductive},
				{"puzzling.stackexchange.com", Efficiency.NonProductive},
				{"gepjarmu-adasveteli-szerzodes.hu", Efficiency.NonProductive},
				{"sites.icasei.com.br", Efficiency.NonProductive},
				{"gregoryszorc.com", Efficiency.NonProductive},
				{"upcmail.upc.hu", Efficiency.NonProductive},
				{"corvinmozi.hu", Efficiency.NonProductive},
				{"jovok.hu", Efficiency.NonProductive},
				{"iworx.nastron.com", Efficiency.NonProductive},
				{"sajay.com", Efficiency.NonProductive},
				{"ingatlan.com", Efficiency.NonProductive},
				{"soundcloud.com", Efficiency.NonProductive},
				{"www.neurotechnology.com", Efficiency.NonProductive},
				{"academia.stackexchange.com", Efficiency.NonProductive},
				{"itunes.apple.com", Efficiency.NonProductive},
				{"search.naver.com", Efficiency.NonProductive},
				{"www.ongo.hu", Efficiency.NonProductive},
				{"zum.com", Efficiency.NonProductive},
				{"us-mg5.mail.yahoo.com", Efficiency.NonProductive},
				{"ibanq.axabank.hu", Efficiency.NonProductive},
				{"economia.uol.com.br", Efficiency.NonProductive},
				{"millasreggeli.hu", Efficiency.NonProductive},
				{"www.mando.com", Efficiency.NonProductive},
				{"www.uol.com.br", Efficiency.NonProductive},
				{"www.santandernet.com.br", Efficiency.NonProductive},
				{"www.skyscanner.com", Efficiency.NonProductive},
				{"www.itau.com.br", Efficiency.NonProductive},
				{"ayende.com", Efficiency.NonProductive},
				{"netbank.erstebank.hu", Efficiency.NonProductive},
				{"www.hotelnautis.hu", Efficiency.NonProductive},
				{"www.unicreditbank.hu", Efficiency.NonProductive},
				{"www.tam.com.br", Efficiency.NonProductive},
				{"www.gmarket.co.kr", Efficiency.NonProductive},
				{"www.egeszsegkonyha.hu", Efficiency.NonProductive},
				{"disqus.com", Efficiency.NonProductive},
				{"br.westcon.com", Efficiency.NonProductive},
				{"kuruc.info", Efficiency.NonProductive},
				{"ncore.cc", Efficiency.NonProductive},
				{"account.viber.com", Efficiency.NonProductive},
				{"www.ivalua.com", Efficiency.NonProductive},
				{"www.kandallopub.hu", Efficiency.NonProductive},
				{"www.palmajor.com", Efficiency.NonProductive},
				{"mazda323f.ucoz.hu", Efficiency.NonProductive},
				{"trattoriavenezia.hu", Efficiency.NonProductive},
				{"www.matiaslocacao.com.br", Efficiency.NonProductive},
				{"www.szuperstore.com", Efficiency.NonProductive},
				{"ecount.co.kr", Efficiency.NonProductive},
				{"medkorp.com", Efficiency.NonProductive},
				{"www.hometax.go.kr", Efficiency.NonProductive},
				{"kaloriabazis.hu", Efficiency.NonProductive},
				{"www.ebay.com", Efficiency.NonProductive},
				{"travelo.hu", Efficiency.NonProductive},
				{"www.recife.pe.gov.br", Efficiency.NonProductive},
				{"free.notaeletronica.com.br", Efficiency.NonProductive},
				{"www.rentalcars.com", Efficiency.NonProductive},
				{"item2.gmarket.co.kr", Efficiency.NonProductive},
				{"magyarhirlap.hu", Efficiency.NonProductive},
				{"govivace.com", Efficiency.NonProductive},
				{"www.wasabi.hu", Efficiency.NonProductive},
				{"baderfogado.hu", Efficiency.NonProductive},
				{"mixr.hu", Efficiency.NonProductive},
				{"www.pizzaforte.hu", Efficiency.NonProductive},
				{"ilikekillnerds.com", Efficiency.NonProductive},
				{"www.fontepizzeria.hu", Efficiency.NonProductive},
				{"club.kartingmanager.com", Efficiency.NonProductive},
				{"www.quora.com", Efficiency.NonProductive},
				{"hvg.hu", Efficiency.NonProductive},
				{"www.fishelhass.com", Efficiency.NonProductive},
				{"elvira.mav-start.hu", Efficiency.NonProductive},
				{"download.neurotechnology.com", Efficiency.NonProductive},
				{"vod.ebay.com", Efficiency.NonProductive},
				{"www2.camara.leg.br", Efficiency.NonProductive},
				{"www.digiprime.hu", Efficiency.NonProductive},
				{"www.dailymotion.com", Efficiency.NonProductive},
				{"www.camara.gov.br", Efficiency.NonProductive},
				{"apatar.com", Efficiency.NonProductive},
				{"www.bikr.co.kr", Efficiency.NonProductive},
				{"access.enom.com", Efficiency.NonProductive},
				{"webmail.digi.hu", Efficiency.NonProductive},
				{"www.powtoon.com", Efficiency.NonProductive},
				{"www.elevengusto.hu", Efficiency.NonProductive},
				{"centralcob.terra.com.br", Efficiency.NonProductive},
				{"pizzaforte.hu", Efficiency.NonProductive},
				{"us-west-2.console.aws.amazon.com", Efficiency.NonProductive},
				{"www.ne2.bradesconetempresa.b.br", Efficiency.NonProductive},
				{"www.kozelben.hu", Efficiency.NonProductive},
				{"mozi.hir24.hu", Efficiency.NonProductive},
				{"dictzone.com", Efficiency.NonProductive},
				{"www.netpincer.hu", Efficiency.NonProductive},
				{"www.melia.com", Efficiency.NonProductive},
				{"sports.premium.com", Efficiency.NonProductive},
				{"www.goldcenter.hu", Efficiency.NonProductive},
				{"www.naver.com", Efficiency.NonProductive},
				{"www2.jofogas.hu", Efficiency.NonProductive},
				{"mega.co.nz", Efficiency.NonProductive},
				{"alistapart.com", Efficiency.NonProductive},
				{"ugyintezes.magyarorszag.hu", Efficiency.NonProductive},
				{"www.allianz.hu", Efficiency.NonProductive},
				{"play.spotify.com", Efficiency.NonProductive},
				{"mediapedia.hu", Efficiency.NonProductive},
				{"www.amazon.com", Efficiency.NonProductive},
				{"www.f24.com", Efficiency.NonProductive},
				{"www.ivirtuagroup.com.br", Efficiency.NonProductive},
				{"aviation.stackexchange.com", Efficiency.NonProductive},
				{"www.uscis.gov", Efficiency.NonProductive},
				{"comments.gmane.org", Efficiency.NonProductive},
				{"www.forbes.com", Efficiency.NonProductive},
				{"monsooninfo.blog.hu", Efficiency.NonProductive},
				{"www.mkyong.com", Efficiency.NonProductive},
				{"america.lunir.hu", Efficiency.NonProductive},
				{"ied.edu.br", Efficiency.NonProductive},
				{"www.elance.com", Efficiency.NonProductive},
				{"www.produtivoapp.com.br", Efficiency.NonProductive},
				{"juventus.hu", Efficiency.NonProductive},
				{"www.vg.hu", Efficiency.NonProductive},
				{"www.atendebem.com.br", Efficiency.NonProductive},
				{"torbagykert.hu", Efficiency.NonProductive},
				{"vista.hu", Efficiency.NonProductive},
				{"eshop.posta.hu", Efficiency.NonProductive},
				{"www.comedycentral.hu", Efficiency.NonProductive},
				{"isscuritiba.curitiba.pr.gov.br", Efficiency.NonProductive},
				{"www.gottwald.hu", Efficiency.NonProductive},
				{"search.zum.com", Efficiency.NonProductive},
				{"onehungrymind.com", Efficiency.NonProductive},
				{"ogp.me", Efficiency.NonProductive},
				{"www.quart.hu", Efficiency.NonProductive},
				{"www.chungsa.go.kr", Efficiency.NonProductive},
				{"maxcity.mnggurman.com", Efficiency.NonProductive},
				{"divany.hu", Efficiency.NonProductive},
				{"www.di.fm", Efficiency.NonProductive},
				{"www.sef.sc.gov.br", Efficiency.NonProductive},
				{"internetbanking.caixa.gov.br", Efficiency.NonProductive},
				{"www.equalizefitness.com", Efficiency.NonProductive},
				{"comment.blog.hu", Efficiency.NonProductive},
				{"uk.verint.com", Efficiency.NonProductive},
				{"books.google.hu", Efficiency.NonProductive},
				{"nfem.joinville.sc.gov.br", Efficiency.NonProductive},
			};

		public static Efficiency Lookup(string processName, string url)
		{
			Efficiency res;
			if (!string.IsNullOrEmpty(url))
			{
				if (urlLookup.TryGetValue(GetDomain(url), out res))
				{
					return res;
				}
			}

			if (string.IsNullOrEmpty(processName))
			{
				return Efficiency.Unknown;
			}

			if (appLookup.TryGetValue(processName, out res))
			{
				return res;
			}

			return Efficiency.Unknown;
		}

		private static string GetDomain(string url)
		{
			var r = Regex.Match(url, @"http(s{0,1})\://(\w+(\.\w+)*(:\d+){0,1})[/]*");
			return r.Success ? r.Groups[2].Value : "";
		}

		public enum Efficiency
		{
			Productive,
			Neutral,
			NonProductive,
			Unknown
		}
	}
}
