#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JiraSyncTool.Jira
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="JobControl")]
	public partial class SyncDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    #endregion
		
		public SyncDataContext() : 
				base(global::JiraSyncTool.Properties.Settings.Default.JobControlConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public SyncDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public SyncDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public SyncDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public SyncDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.Client_GetJiraEnabledCompanies")]
		public ISingleResult<Client_GetJiraEnabledCompaniesResult> Client_GetJiraEnabledCompanies()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((ISingleResult<Client_GetJiraEnabledCompaniesResult>)(result.ReturnValue));
		}
	}
	
	public partial class Client_GetJiraEnabledCompaniesResult
	{
		
		private System.Nullable<int> _CompanyId;
		
		private string _BaseUrl;
		
		private string _SharedSecret;
		
		private string _ClientKey;
		
		private string _OauthClientId;
		
		private System.Nullable<System.Guid> _JobCtrlAuthCode;
		
		private int _JiraRootTaskId;
		
		public Client_GetJiraEnabledCompaniesResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CompanyId", DbType="Int")]
		public System.Nullable<int> CompanyId
		{
			get
			{
				return this._CompanyId;
			}
			set
			{
				if ((this._CompanyId != value))
				{
					this._CompanyId = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BaseUrl", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
		public string BaseUrl
		{
			get
			{
				return this._BaseUrl;
			}
			set
			{
				if ((this._BaseUrl != value))
				{
					this._BaseUrl = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SharedSecret", DbType="VarChar(200) NOT NULL", CanBeNull=false)]
		public string SharedSecret
		{
			get
			{
				return this._SharedSecret;
			}
			set
			{
				if ((this._SharedSecret != value))
				{
					this._SharedSecret = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ClientKey", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string ClientKey
		{
			get
			{
				return this._ClientKey;
			}
			set
			{
				if ((this._ClientKey != value))
				{
					this._ClientKey = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OauthClientId", DbType="VarChar(200) NOT NULL", CanBeNull=false)]
		public string OauthClientId
		{
			get
			{
				return this._OauthClientId;
			}
			set
			{
				if ((this._OauthClientId != value))
				{
					this._OauthClientId = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_JobCtrlAuthCode", DbType="UniqueIdentifier")]
		public System.Nullable<System.Guid> JobCtrlAuthCode
		{
			get
			{
				return this._JobCtrlAuthCode;
			}
			set
			{
				if ((this._JobCtrlAuthCode != value))
				{
					this._JobCtrlAuthCode = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_JiraRootTaskId", DbType="Int NOT NULL")]
		public int JiraRootTaskId
		{
			get
			{
				return this._JiraRootTaskId;
			}
			set
			{
				if ((this._JiraRootTaskId != value))
				{
					this._JiraRootTaskId = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
