//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tct.ActivityRecorderClient.AppControlServiceReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="AppControlServiceReference.IAppControlServiceService")]
    public interface IAppControlServiceService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAppControlServiceService/RegisterProcess", ReplyAction="http://tempuri.org/IAppControlServiceService/RegisterProcessResponse")]
        void RegisterProcess(int pid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAppControlServiceService/UnregisterProcess", ReplyAction="http://tempuri.org/IAppControlServiceService/UnregisterProcessResponse")]
        void UnregisterProcess(int pid);

		[System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IAppControlServiceService/Ping", ReplyAction = "http://tempuri.org/IAppControlServiceService/PingResponse")]
		void Ping();
	}
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IAppControlServiceServiceChannel : Tct.ActivityRecorderClient.AppControlServiceReference.IAppControlServiceService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class AppControlServiceServiceClient : System.ServiceModel.ClientBase<Tct.ActivityRecorderClient.AppControlServiceReference.IAppControlServiceService>, Tct.ActivityRecorderClient.AppControlServiceReference.IAppControlServiceService {
        
        public AppControlServiceServiceClient() {
        }
        
        public AppControlServiceServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public AppControlServiceServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AppControlServiceServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AppControlServiceServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void RegisterProcess(int pid) {
            base.Channel.RegisterProcess(pid);
        }
        
        public void UnregisterProcess(int pid) {
            base.Channel.UnregisterProcess(pid);
        }

		public void Ping()
		{
			base.Channel.Ping();
		}
	}
}
