//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tct.ActivityRecorderClient.OutlookMailCaptureServiceReference {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="MailCaptures", Namespace="http://jobctrl.com/mail")]
    [System.SerializableAttribute()]
    public partial class MailCaptures : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.Dictionary<int, Tct.ActivityRecorderClient.OutlookMailCaptureServiceReference.MailCapture> MailCaptureByHWndField;

        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsSafeMailItemCommitUsableField;

		[global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order = 1)]
        public System.Collections.Generic.Dictionary<int, Tct.ActivityRecorderClient.OutlookMailCaptureServiceReference.MailCapture> MailCaptureByHWnd {
            get {
                return this.MailCaptureByHWndField;
            }
            set {
                if ((object.ReferenceEquals(this.MailCaptureByHWndField, value) != true)) {
                    this.MailCaptureByHWndField = value;
                    this.RaisePropertyChanged("MailCaptureByHWnd");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order = 2)]
        public bool IsSafeMailItemCommitUsable
        {
            get {
                return this.IsSafeMailItemCommitUsableField;
            }
            set {
                if (this.IsSafeMailItemCommitUsableField.Equals(value) != true) {
                    this.IsSafeMailItemCommitUsableField = value;
                    this.RaisePropertyChanged("IsSafeMailItemCommitUsable");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="MailCapture", Namespace="http://jobctrl.com/mail")]
    [System.SerializableAttribute()]
    public partial class MailCapture : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.List<Tct.ActivityRecorderClient.OutlookMailCaptureServiceReference.MailAddress> CcField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Tct.ActivityRecorderClient.OutlookMailCaptureServiceReference.MailAddress FromField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SubjectField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.List<Tct.ActivityRecorderClient.OutlookMailCaptureServiceReference.MailAddress> ToField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string JcIdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.List<Tct.ActivityRecorderClient.OutlookMailCaptureServiceReference.MailAddress> Cc {
            get {
                return this.CcField;
            }
            set {
                if ((object.ReferenceEquals(this.CcField, value) != true)) {
                    this.CcField = value;
                    this.RaisePropertyChanged("Cc");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Tct.ActivityRecorderClient.OutlookMailCaptureServiceReference.MailAddress From {
            get {
                return this.FromField;
            }
            set {
                if ((object.ReferenceEquals(this.FromField, value) != true)) {
                    this.FromField = value;
                    this.RaisePropertyChanged("From");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Id {
            get {
                return this.IdField;
            }
            set {
                if ((object.ReferenceEquals(this.IdField, value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Subject {
            get {
                return this.SubjectField;
            }
            set {
                if ((object.ReferenceEquals(this.SubjectField, value) != true)) {
                    this.SubjectField = value;
                    this.RaisePropertyChanged("Subject");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.List<Tct.ActivityRecorderClient.OutlookMailCaptureServiceReference.MailAddress> To {
            get {
                return this.ToField;
            }
            set {
                if ((object.ReferenceEquals(this.ToField, value) != true)) {
                    this.ToField = value;
                    this.RaisePropertyChanged("To");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=5)]
        public string JcId {
            get {
                return this.JcIdField;
            }
            set {
                if ((object.ReferenceEquals(this.JcIdField, value) != true)) {
                    this.JcIdField = value;
                    this.RaisePropertyChanged("JcId");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="MailTrackingType", Namespace="http://schemas.datacontract.org/2004/07/Tct.ActivityRecorderClient.Capturing.Mail" +
        "")]
    public enum MailTrackingType : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Disable = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        BodyAndSubject = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        BodyOnly = 2,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="MailAddress", Namespace="http://jobctrl.com/mail")]
    [System.SerializableAttribute()]
    public partial class MailAddress : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Email {
            get {
                return this.EmailField;
            }
            set {
                if ((object.ReferenceEquals(this.EmailField, value) != true)) {
                    this.EmailField = value;
                    this.RaisePropertyChanged("Email");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.FlagsAttribute()]
    [System.Runtime.Serialization.DataContractAttribute(Name="MailTrackingSettings", Namespace="http://schemas.datacontract.org/2004/07/Tct.ActivityRecorderClient.Capturing.Mail" +
        "")]
    public enum MailTrackingSettings : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        None = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ReadId = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        WriteIdToMail = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ShowPopupWindow = 4,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        All = -1,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="OutlookMailCaptureServiceReference.IOutlookMailCaptureService")]
    public interface IOutlookMailCaptureService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMailCaptureService/GetMailCaptures", ReplyAction="http://tempuri.org/IMailCaptureService/GetMailCapturesResponse")]
        Tct.ActivityRecorderClient.OutlookMailCaptureServiceReference.MailCaptures GetMailCaptures();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMailCaptureService/StopService", ReplyAction="http://tempuri.org/IMailCaptureService/StopServiceResponse")]
        void StopService();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOutlookMailCaptureService/SetMailTracking", ReplyAction="http://tempuri.org/IOutlookMailCaptureService/SetMailTrackingResponse")]
        void SetMailTracking(Tct.ActivityRecorderClient.OutlookMailCaptureServiceReference.MailTrackingType trackingType, Tct.ActivityRecorderClient.OutlookMailCaptureServiceReference.MailTrackingSettings trackingSettings, bool isSafeMailItemCommitUsable);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IOutlookMailCaptureServiceChannel : Tct.ActivityRecorderClient.OutlookMailCaptureServiceReference.IOutlookMailCaptureService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class OutlookMailCaptureServiceClient : System.ServiceModel.ClientBase<Tct.ActivityRecorderClient.OutlookMailCaptureServiceReference.IOutlookMailCaptureService>, Tct.ActivityRecorderClient.OutlookMailCaptureServiceReference.IOutlookMailCaptureService {
        
        public OutlookMailCaptureServiceClient() {
        }
        
        public OutlookMailCaptureServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public OutlookMailCaptureServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public OutlookMailCaptureServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public OutlookMailCaptureServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public Tct.ActivityRecorderClient.OutlookMailCaptureServiceReference.MailCaptures GetMailCaptures() {
            return base.Channel.GetMailCaptures();
        }
        
        public void StopService() {
            base.Channel.StopService();
        }
        
        public void SetMailTracking(Tct.ActivityRecorderClient.OutlookMailCaptureServiceReference.MailTrackingType trackingType, Tct.ActivityRecorderClient.OutlookMailCaptureServiceReference.MailTrackingSettings trackingSettings, bool isSafeMailItemCommitUsable) {
            base.Channel.SetMailTracking(trackingType, trackingSettings, isSafeMailItemCommitUsable);
        }
    }
}
