//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.225
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ActivityStatsTester.ActivityStatsServiceReference {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DailyStats", Namespace="http://schemas.datacontract.org/2004/07/Tct.ActivityRecorderService.Stats")]
    [System.SerializableAttribute()]
    public partial class DailyStats : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime DateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.List<ActivityStatsTester.ActivityStatsServiceReference.UserStats> UsersField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime Date {
            get {
                return this.DateField;
            }
            set {
                if ((this.DateField.Equals(value) != true)) {
                    this.DateField = value;
                    this.RaisePropertyChanged("Date");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.List<ActivityStatsTester.ActivityStatsServiceReference.UserStats> Users {
            get {
                return this.UsersField;
            }
            set {
                if ((object.ReferenceEquals(this.UsersField, value) != true)) {
                    this.UsersField = value;
                    this.RaisePropertyChanged("Users");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UserStats", Namespace="http://schemas.datacontract.org/2004/07/Tct.ActivityRecorderService.Stats")]
    [System.SerializableAttribute()]
    public partial class UserStats : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CompanyIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ActivityStatsTester.ActivityStatsServiceReference.UserWorkStats CurrentWorkField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int GroupIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ActivityStatsTester.ActivityStatsServiceReference.ActiveWindow LastActiveWindowField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int LastKeyboardActivityField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int LastMouseActivityField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.List<ActivityStatsTester.ActivityStatsServiceReference.ScreenShot> LastScreenShotsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime LastUpdateDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.List<ActivityStatsTester.ActivityStatsServiceReference.UserWorkStats> RecentWorksField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ActivityStatsTester.ActivityStatsServiceReference.UserStatus StatusField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int UserIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private float AverageKeyboardActivityField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private float AverageMouseActivityField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ActivityStatsTester.ActivityStatsServiceReference.WorkTimeStats WorkTimeStatsField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CompanyId {
            get {
                return this.CompanyIdField;
            }
            set {
                if ((this.CompanyIdField.Equals(value) != true)) {
                    this.CompanyIdField = value;
                    this.RaisePropertyChanged("CompanyId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ActivityStatsTester.ActivityStatsServiceReference.UserWorkStats CurrentWork {
            get {
                return this.CurrentWorkField;
            }
            set {
                if ((object.ReferenceEquals(this.CurrentWorkField, value) != true)) {
                    this.CurrentWorkField = value;
                    this.RaisePropertyChanged("CurrentWork");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int GroupId {
            get {
                return this.GroupIdField;
            }
            set {
                if ((this.GroupIdField.Equals(value) != true)) {
                    this.GroupIdField = value;
                    this.RaisePropertyChanged("GroupId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ActivityStatsTester.ActivityStatsServiceReference.ActiveWindow LastActiveWindow {
            get {
                return this.LastActiveWindowField;
            }
            set {
                if ((object.ReferenceEquals(this.LastActiveWindowField, value) != true)) {
                    this.LastActiveWindowField = value;
                    this.RaisePropertyChanged("LastActiveWindow");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int LastKeyboardActivity {
            get {
                return this.LastKeyboardActivityField;
            }
            set {
                if ((this.LastKeyboardActivityField.Equals(value) != true)) {
                    this.LastKeyboardActivityField = value;
                    this.RaisePropertyChanged("LastKeyboardActivity");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int LastMouseActivity {
            get {
                return this.LastMouseActivityField;
            }
            set {
                if ((this.LastMouseActivityField.Equals(value) != true)) {
                    this.LastMouseActivityField = value;
                    this.RaisePropertyChanged("LastMouseActivity");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.List<ActivityStatsTester.ActivityStatsServiceReference.ScreenShot> LastScreenShots {
            get {
                return this.LastScreenShotsField;
            }
            set {
                if ((object.ReferenceEquals(this.LastScreenShotsField, value) != true)) {
                    this.LastScreenShotsField = value;
                    this.RaisePropertyChanged("LastScreenShots");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime LastUpdateDate {
            get {
                return this.LastUpdateDateField;
            }
            set {
                if ((this.LastUpdateDateField.Equals(value) != true)) {
                    this.LastUpdateDateField = value;
                    this.RaisePropertyChanged("LastUpdateDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.List<ActivityStatsTester.ActivityStatsServiceReference.UserWorkStats> RecentWorks {
            get {
                return this.RecentWorksField;
            }
            set {
                if ((object.ReferenceEquals(this.RecentWorksField, value) != true)) {
                    this.RecentWorksField = value;
                    this.RaisePropertyChanged("RecentWorks");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ActivityStatsTester.ActivityStatsServiceReference.UserStatus Status {
            get {
                return this.StatusField;
            }
            set {
                if ((this.StatusField.Equals(value) != true)) {
                    this.StatusField = value;
                    this.RaisePropertyChanged("Status");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int UserId {
            get {
                return this.UserIdField;
            }
            set {
                if ((this.UserIdField.Equals(value) != true)) {
                    this.UserIdField = value;
                    this.RaisePropertyChanged("UserId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=11)]
        public float AverageKeyboardActivity {
            get {
                return this.AverageKeyboardActivityField;
            }
            set {
                if ((this.AverageKeyboardActivityField.Equals(value) != true)) {
                    this.AverageKeyboardActivityField = value;
                    this.RaisePropertyChanged("AverageKeyboardActivity");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=12)]
        public float AverageMouseActivity {
            get {
                return this.AverageMouseActivityField;
            }
            set {
                if ((this.AverageMouseActivityField.Equals(value) != true)) {
                    this.AverageMouseActivityField = value;
                    this.RaisePropertyChanged("AverageMouseActivity");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=13)]
        public ActivityStatsTester.ActivityStatsServiceReference.WorkTimeStats WorkTimeStats {
            get {
                return this.WorkTimeStatsField;
            }
            set {
                if ((object.ReferenceEquals(this.WorkTimeStatsField, value) != true)) {
                    this.WorkTimeStatsField = value;
                    this.RaisePropertyChanged("WorkTimeStats");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UserWorkStats", Namespace="http://schemas.datacontract.org/2004/07/Tct.ActivityRecorderService.Stats")]
    [System.SerializableAttribute()]
    public partial class UserWorkStats : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime StartDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int WorkIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.TimeSpan WorkTimeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime StartDate {
            get {
                return this.StartDateField;
            }
            set {
                if ((this.StartDateField.Equals(value) != true)) {
                    this.StartDateField = value;
                    this.RaisePropertyChanged("StartDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int WorkId {
            get {
                return this.WorkIdField;
            }
            set {
                if ((this.WorkIdField.Equals(value) != true)) {
                    this.WorkIdField = value;
                    this.RaisePropertyChanged("WorkId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.TimeSpan WorkTime {
            get {
                return this.WorkTimeField;
            }
            set {
                if ((this.WorkTimeField.Equals(value) != true)) {
                    this.WorkTimeField = value;
                    this.RaisePropertyChanged("WorkTime");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ActiveWindow", Namespace="http://schemas.datacontract.org/2004/07/Tct.ActivityRecorderService")]
    [System.SerializableAttribute()]
    public partial class ActiveWindow : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime CreateDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ProcessNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TitleField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime CreateDate {
            get {
                return this.CreateDateField;
            }
            set {
                if ((this.CreateDateField.Equals(value) != true)) {
                    this.CreateDateField = value;
                    this.RaisePropertyChanged("CreateDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ProcessName {
            get {
                return this.ProcessNameField;
            }
            set {
                if ((object.ReferenceEquals(this.ProcessNameField, value) != true)) {
                    this.ProcessNameField = value;
                    this.RaisePropertyChanged("ProcessName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Title {
            get {
                return this.TitleField;
            }
            set {
                if ((object.ReferenceEquals(this.TitleField, value) != true)) {
                    this.TitleField = value;
                    this.RaisePropertyChanged("Title");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="WorkTimeStats", Namespace="http://schemas.datacontract.org/2004/07/Tct.ActivityRecorderService.Stats")]
    [System.SerializableAttribute()]
    public partial class WorkTimeStats : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.TimeSpan ComputerWorkTimeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.TimeSpan IvrWorkTimeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.TimeSpan SumWorkTimeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.TimeSpan ComputerWorkTime {
            get {
                return this.ComputerWorkTimeField;
            }
            set {
                if ((this.ComputerWorkTimeField.Equals(value) != true)) {
                    this.ComputerWorkTimeField = value;
                    this.RaisePropertyChanged("ComputerWorkTime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.TimeSpan IvrWorkTime {
            get {
                return this.IvrWorkTimeField;
            }
            set {
                if ((this.IvrWorkTimeField.Equals(value) != true)) {
                    this.IvrWorkTimeField = value;
                    this.RaisePropertyChanged("IvrWorkTime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.TimeSpan SumWorkTime {
            get {
                return this.SumWorkTimeField;
            }
            set {
                if ((this.SumWorkTimeField.Equals(value) != true)) {
                    this.SumWorkTimeField = value;
                    this.RaisePropertyChanged("SumWorkTime");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ScreenShot", Namespace="http://schemas.datacontract.org/2004/07/Tct.ActivityRecorderService")]
    [System.SerializableAttribute()]
    public partial class ScreenShot : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime CreateDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private byte ScreenNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ExtensionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ActivityStatsTester.ActivityStatsServiceReference.Binary DataField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime CreateDate {
            get {
                return this.CreateDateField;
            }
            set {
                if ((this.CreateDateField.Equals(value) != true)) {
                    this.CreateDateField = value;
                    this.RaisePropertyChanged("CreateDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public byte ScreenNumber {
            get {
                return this.ScreenNumberField;
            }
            set {
                if ((this.ScreenNumberField.Equals(value) != true)) {
                    this.ScreenNumberField = value;
                    this.RaisePropertyChanged("ScreenNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public string Extension {
            get {
                return this.ExtensionField;
            }
            set {
                if ((object.ReferenceEquals(this.ExtensionField, value) != true)) {
                    this.ExtensionField = value;
                    this.RaisePropertyChanged("Extension");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public ActivityStatsTester.ActivityStatsServiceReference.Binary Data {
            get {
                return this.DataField;
            }
            set {
                if ((object.ReferenceEquals(this.DataField, value) != true)) {
                    this.DataField = value;
                    this.RaisePropertyChanged("Data");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UserStatus", Namespace="http://schemas.datacontract.org/2004/07/Tct.ActivityRecorderService.Stats")]
    public enum UserStatus : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        None = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Online = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        OnlineIdle = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        OnlineNotWorking = 3,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Offline = 4,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Binary", Namespace="http://schemas.datacontract.org/2004/07/System.Data.Linq")]
    [System.SerializableAttribute()]
    public partial class Binary : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private byte[] BytesField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public byte[] Bytes {
            get {
                return this.BytesField;
            }
            set {
                if ((object.ReferenceEquals(this.BytesField, value) != true)) {
                    this.BytesField = value;
                    this.RaisePropertyChanged("Bytes");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ActivityStatsServiceReference.IActivityStats")]
    public interface IActivityStats {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IActivityStats/GetDailyStats", ReplyAction="http://tempuri.org/IActivityStats/GetDailyStatsResponse")]
        ActivityStatsTester.ActivityStatsServiceReference.DailyStats GetDailyStats();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IActivityStats/GetDailyStatsByUserId", ReplyAction="http://tempuri.org/IActivityStats/GetDailyStatsByUserIdResponse")]
        ActivityStatsTester.ActivityStatsServiceReference.DailyStats GetDailyStatsByUserId(int userId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IActivityStats/GetDailyStatsByUserIds", ReplyAction="http://tempuri.org/IActivityStats/GetDailyStatsByUserIdsResponse")]
        ActivityStatsTester.ActivityStatsServiceReference.DailyStats GetDailyStatsByUserIds(System.Collections.Generic.List<int> userIds);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IActivityStats/GetDailyStatsByGroupId", ReplyAction="http://tempuri.org/IActivityStats/GetDailyStatsByGroupIdResponse")]
        ActivityStatsTester.ActivityStatsServiceReference.DailyStats GetDailyStatsByGroupId(int groupId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IActivityStats/GetDailyStatsByCompanyId", ReplyAction="http://tempuri.org/IActivityStats/GetDailyStatsByCompanyIdResponse")]
        ActivityStatsTester.ActivityStatsServiceReference.DailyStats GetDailyStatsByCompanyId(int companyId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IActivityStats/SendDailyEmails", ReplyAction="http://tempuri.org/IActivityStats/SendDailyEmailsResponse")]
        void SendDailyEmails(System.DateTime date, System.Collections.Generic.List<int> userIds);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IActivityStats/SendWeeklyEmails", ReplyAction="http://tempuri.org/IActivityStats/SendWeeklyEmailsResponse")]
        void SendWeeklyEmails(System.DateTime date, System.Collections.Generic.List<int> userIds);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IActivityStats/SendMonthlyEmails", ReplyAction="http://tempuri.org/IActivityStats/SendMonthlyEmailsResponse")]
        void SendMonthlyEmails(System.DateTime date, System.Collections.Generic.List<int> userIds);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IActivityStats/SendProjectEmails", ReplyAction="http://tempuri.org/IActivityStats/SendProjectEmailsResponse")]
        void SendProjectEmails(System.DateTime utcStartDate, System.DateTime utcEndDate, int reportUserId, bool isInternal, System.Collections.Generic.List<int> projectRootIds, System.Collections.Generic.List<string> toAddresses);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IActivityStatsChannel : ActivityStatsTester.ActivityStatsServiceReference.IActivityStats, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ActivityStatsClient : System.ServiceModel.ClientBase<ActivityStatsTester.ActivityStatsServiceReference.IActivityStats>, ActivityStatsTester.ActivityStatsServiceReference.IActivityStats {
        
        public ActivityStatsClient() {
        }
        
        public ActivityStatsClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ActivityStatsClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ActivityStatsClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ActivityStatsClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public ActivityStatsTester.ActivityStatsServiceReference.DailyStats GetDailyStats() {
            return base.Channel.GetDailyStats();
        }
        
        public ActivityStatsTester.ActivityStatsServiceReference.DailyStats GetDailyStatsByUserId(int userId) {
            return base.Channel.GetDailyStatsByUserId(userId);
        }
        
        public ActivityStatsTester.ActivityStatsServiceReference.DailyStats GetDailyStatsByUserIds(System.Collections.Generic.List<int> userIds) {
            return base.Channel.GetDailyStatsByUserIds(userIds);
        }
        
        public ActivityStatsTester.ActivityStatsServiceReference.DailyStats GetDailyStatsByGroupId(int groupId) {
            return base.Channel.GetDailyStatsByGroupId(groupId);
        }
        
        public ActivityStatsTester.ActivityStatsServiceReference.DailyStats GetDailyStatsByCompanyId(int companyId) {
            return base.Channel.GetDailyStatsByCompanyId(companyId);
        }
        
        public void SendDailyEmails(System.DateTime date, System.Collections.Generic.List<int> userIds) {
            base.Channel.SendDailyEmails(date, userIds);
        }
        
        public void SendWeeklyEmails(System.DateTime date, System.Collections.Generic.List<int> userIds) {
            base.Channel.SendWeeklyEmails(date, userIds);
        }
        
        public void SendMonthlyEmails(System.DateTime date, System.Collections.Generic.List<int> userIds) {
            base.Channel.SendMonthlyEmails(date, userIds);
        }
        
        public void SendProjectEmails(System.DateTime utcStartDate, System.DateTime utcEndDate, int reportUserId, bool isInternal, System.Collections.Generic.List<int> projectRootIds, System.Collections.Generic.List<string> toAddresses) {
            base.Channel.SendProjectEmails(utcStartDate, utcEndDate, reportUserId, isInternal, projectRootIds, toAddresses);
        }
    }
}
